.title		UAFMSG -- Run Time Messages for AUTHORIZE Facility
.ident		'V04-000'

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

.facility	UAF,1009/system

!
!	Facility:	AUTHORIZE
!	Abstract:	Manage User Authorization Files: Messages
!	Author:		John R. Lawson, Jr.
!	Date:		15-June-1984 13:21
!

.severity	information

ADDMSG		"user record successfully added"
COPMSG		"user record copied"
DONEMSG		"system authorization file modified"
GRANTMSG	"identifier !AS granted to !AS"/fao_count=2
LSTMSG1		"writing listing file"
LSTMSG2		"listing file SYSUAF.LIS complete"
MDFYMSG		"user record(s) updated"
NAFADDMSG	"record successfully added to NETUAF.DAT"
NAFDONEMSG	"network authorization file modified"
NAFNOMODS	"no modifications made to network authorization file"
NETLSTMSG	"listing file NETUAF.LIS complete"
NOIDNAME	"no ID name was specified"
NOMODS		"no modifications made to system authorization file"
PREMMSG		"record removed from NETUAF.DAT"
RDBADDMSG	"identifier !AS value: %X!XL added to RIGHTSLIST.DAT"/fao_count=2
RDBADDMSGU	"identifier !AS value: [!OW,!OW] added to RIGHTSLIST.DAT"/fao_count=3
RDBCREMSG	"RIGHTSLIST.DAT created"
RDBDONEMSG	"rights database modified"
RDBMDFYMSG	"identifier !AS modified"/fao_count=1
RDBNOMODS	"no modifications made to rights database"
RDBREMMSG	"identifier !AS value: %X!XL removed from RIGHTSLIST.DAT"/fao_count=2
RDBREMMSGU	"identifier !AS value: [!OW,!OW] removed from RIGHTSLIST.DAT"/fao_count=3
REMMSG		"record removed from SYSUAF.DAT"
RENMSG		"user record renamed"
REVOKEMSG	"identifier !AS revoked from !AS"/fao_count=2
RLSTMSG		"listing file RIGHTSLIST.LIS complete"
RONLY		"read-only access"
SYSMSG1		"!AS"/fao_count=1
ZZPRACREN	"proxies to !AD renamed"/fao_count=1

.severity	warning

BADNODFORM	"improper node::remoteuser format"
BADSPC		"no user matched specification"
BADUSR		"username does not exist \!AD\"/fao_count=1
CLIWARNMSG	"Warning: /CLITABLES field may need to reflect changes to /CLI field"
DEFPWD		"Warning: copied or renamed records must receive new password"
EXTRAPARM	"superfluous parameter detected \!AD\"/fao_count=1
IDOUTRNG	"identifier value is not within legal range"
INVDEV		"device name too long to add trailing ':'!/\!AD\"/fao_count=1
INVSTR		"string too long for field \!AD\"/fao_count=1
KEYNOTFND	"invalid option name \!AD\"/fao_count=1
KEYNOTUNQ	"option name not unique \!AD\"/fao_count=1
NAFAEX 		"NETUAF.DAT already exists"
NAFUAEERR	"entry already exists in NETUAF.DAT"
NAFDNE		"NETUAF.DAT does not exist"
NODEFPWD	"Warning: DEFAULT password change has no effect on ADDed records"
NODTOOBIG	"node name too long"
NOGRPWILD	"wild card group numbers not allowed"
NOTIDFMT 	"id name parameter does not translate to ID format"
NOTUICFMT 	"user id parameter does not translate to UIC format"
PWDNCH		"!AD password not changed"/fao_count=1
SYSMSG2		"ERROR CODE %X'!XL'"/fao_count=1
WLDNOTALWD	"wild card user specs not allowed"

.severity	error

ADDERR		"unable to add user record"
BADVALUE	"error in value specification \!AD\"/fao_count=1
CMDTOOLONG	"command line exceeds maximum length of !4UL"/fao_count=1
CONERR		"connect error"
CREERR		"unable to create SYSUAF.DAT"
DEFERR		"unable to obtain DEFAULT record"
GETERR		"get error"
GRANTERR	"unable to grant identifier !AS to !AS"/fao_count=2
HELPERR 	"error finding or outputting HELP information"
INVCMD		"invalid command"
INVRSP		"invalid response"
INVUSERNAME	"username syntax error"
INVUSERSPEC	"error in user specification \!AD\"/fao_count=1
LSTERR		"error generating listing file"
MDFYERR		"unable to update record"
NAFADDERR	"unable to add record to NETUAF.DAT"
NAFCONERR	"connect error on NETUAF.DAT"
NAFCREERR	"unable to create NETUAF.DAT"
NAMETOOBIG	"username too long"
NAOFIL		"unable to open SYSUAF.DAT"
NAONAF		"unable to open NETUAF.DAT"
NOARG		"missing argument for option \!AD\"/fao_count=1
NOQUOTE		"quoted string missing end quote \!AD\"/fao_count=1
NOTUNQ		"command is not unique"
NOUSERNAME	"missing username"
NOUSERSPEC	"missing user specification"
PRVNOTFND	"invalid privilege name \!AD\"/fao_count=1
PRVNOTUNQ	"privilege name not unique \!AD\"/fao_count=1
PUTERR		"put error"
PWDNOL		"password not on list; try again"
PWDSYNTAX	"invalid password syntax"
RDBADDERR	"unable to add !AS to RIGHTSLIST.DAT"/fao_count=1
RDBADDERRU	"unable to add !AS value: [!OW,!OW] to RIGHTSLIST.DAT"/fao_count=3
RDBADDERRV	"unable to add !AS value: %X!XL to RIGHTSLIST.DAT"/fao_count=2
RDBCREERR	"unable to create RIGHTSLIST.DAT"
RDBMDFYERR	"unable to modify identifier !AS"/fao_count=1
RDBMDFYERRU	"unable to modify identifier [!OW,!OW]"/fao_count=2
RDBREMERR	"unable to remove !AS from RIGHTSLIST.DAT"/fao_count=1
REMDEF		"the DEFAULT record may not be removed"
REMERR		"unable to delete record"
REMSYS		"the SYSTEM record may not be removed"
RENDEF		"the DEFAULT record may not be renamed"
RENSYS		"the SYSTEM record may not be renamed"
REVOKEERR	"unable to revoke identifier !AS from !AS"/fao_count=2
SHOWERR		"unable to complete show command"
SHOW_ERR	"error during SHOW"
UAEERR		"invalid username, username already exists"
UICERR		"error in UIC specification \!AD\"/fao_count=1
VALTOOBIG	"value too large for field \!AD\"/fao_count=1
ZCONFLICT	"/PASSWORD and /GENERATE_PASSWORD are mutually exclusive"
ZISQUAL		"qualifier required; not found"

