!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! AUTHOR: Elliott A. Drayton		Creation date: 10-Feb-1983
!
! Modified by:
!
!	V03-008	EAD0118		Elliott A. Drayton	21-Mar-1984
!		Add a prameter to the HERALD.
!
!	V03-007 EAD0077		Elliott A. Drayton	21-Feb-1984
!		Added a another parameter to BADEVTYP message.
!
!	V03-006 SAR0191		Sharon A. Reynolds	14-Feb-1984
!		- Added the NOTFOUND message.
!
!		JMG0009		Joel M. Gringorten	 6-Feb-1984
!		Added NOSTATS and GETJPIERR messages.
!
!	V03-005	SAR0183		Sharon A. Reynolds	19-Dec-1983
!		Added INCENTRY message.
!
!	V03-004	SAR0170		Sharon A. Reynolds	3-Nov-1983
!		Removed NOREP and added INVREPTYP.
!
!	V03-003 SAR0154		Sharon A. Reynolds	7-Oct-1983
!		Added UNKCPU, UNKENTRY, and UNKTYPE messages.
!
!	V03-002	SAR0132		Sharon A. Reynolds	9-Sep-1983
!		Added new error messages.
!
!---

!
! DEFINE ERF ERROR MESSAGES
!

.Facility	ERF,8

.Severity	INFORMATIONAL
INPUT		<!AS, !SL selected, !SL rejected>/fao=3
HERALD		<Error Log Report Generator!5(_)Version !AS>/fao=1
TOTAL		<!SL selected, !SL rejected, !SL input files>/fao=3
UNKCLASS	<unknown device class found, !SL>/fao=1
UNKCPU		<unknown cpu type, !SL>/fao=1
UNKENTRY	<unknown entry type, !SL>/fao=1
UNKTYPE		<unknown device type, !SB>/fao=1
LOADERR		<error loading image, !AS>/fao=1
INCENTRY	<incomplete entry type, !SL>/fao=1
NOSTATS		<run-time statistics not available>
NOTFOUND	<specified entry(s) not found>

.Severity	ERROR
OPENIN		<error opening !AS as input>/FAO=1
READERR		<error reading !AS>/FAO=1
OPENOUT		<error opening !AS as output>/FAO=1
WRITEERR	<error writing !AS>/FAO=1
INVDEVICE	<invalid or unsupported device !AS>/FAO=1
CNFQUAVAL	<conflicting qualifier values for !AS, !AS>/FAO=3
DEVSELREQ	<device selection required>
INVKEYWRD	<invalid keyword !AS>/FAO=1
GETJPIERR	<error from SYS$GETJPI>

.Severity	FATAL
CVTERR		<error converting to decimal value, !AD>/FAO=1
CLSTBLERR	<device class value, !SW not in class tables>/FAO=1
BADEVVAL	<bad device table value, !SL in text library module, !AS>/FAO=2
BADEVTYP	<bad device type, !SL in text library module, !AS>/FAO=2
BADMODNAM	<bad module name key !AS>/FAO=1
INVREPTYP	<invalid report type>
TOOMANCLS	<number of classes in text library module greater then allowable classes>

.End
