! VAX-11 RPGII Run-Time error condition values/message IDs
! File: RPGMSG.MSG, Edit: DG1002
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
!
! Edit History:
!
! 1-001 - Original.						DG   8-Mar-1983
! 1-002 - Changed wording of INVNUMENT.				DG  17-Aug-1983
!
!+
! Symbols are defined following the standard for global names:
!
!	RPG$_abcmnoxyz
!
! In addition, the library standards specify that the letters "abc", "mno",
! and "xyz" are the first three letters of the first three words of the error
! message, not counting articles and prepositions.
!
!

! MACRO-32 Programming:
!
! The macro call:
!
!	$RPGDEF
!
! will cause all symbols to be made available to the module.
! The Run-time Library declares these symbols as EXTERNAL;
! the macros are provided only for the convenience of the user.

!-



!
!
!			; Note: Error codes must not overlap success codes!!!

	.TITLE		RPG$MSGDEF
	.IDENT		'1-001'
	.FACILITY	RPG,249 /SYSTEM


	.SEVERITY	INFORMATION
	.BASE		0

	FORFILE		<for file !AS>/FAO = 1
	INVNUMENT	<Numeric entry is invalid or out of range.  Re-enter: >

	.SEVERITY	FATAL

	ENDOF_FIL	<End of file encountered on a READ operation with no resulting indicator specified>
	ERRDURDSP	<An error was detected during a DSPLY operation>
	EXESUBALR	<An attempt was made to execute a subroutine that is already being executed>
	EXTINDOFF	<An attempt was made to perform I/O to a file conditioned by an external indicator that is off>
	FATINTERR	<Fatal internal error>
	FLDOUTSEQ	<One of the matching fields in the current record is not in the specified sequence>
	HLTINDON	<Halt indicator H!UB is on>/FAO = 1
	INVARG		<Invalid argument>
	INVARRIND	<An array index is greater than the number of elements in the array or less than 1>
	INVNUMFLD	<A numeric field contains invalid data>
	INVUDATE	<When you assign the logical RPG$UDATE, it must be in the format dd-mmm-yyyy>
	KEYNOTFND	<The key value specified by a CHAIN operation could not be found with no resulting indicator specified>
	KEYNOTMAT	<Record key specified does not match any of the key(s) in the file>
	LESIN_TAB	<A pre-execution-time table or array file contains less entries than the specified sequenced table or array>
	MORIN_TAB	<A pre-execution-time table or array file contains more entries than the specified table or array>
	NONASCKEY	<The record being written has a nonascending primary key value>
	ORGNOTIND	<File organization is not indexed as specified>
	RECEXCMAX	<The relative record number exceeds the maximum allowed value>
	RECNOTDET	<The record type of the current record could not be determined>
	RECOUTSEQ	<The current record is not in the specified sequence>
	TABOUTSEQ	<The pre-execution-time table or array is not in the specified sequence>
	UPDNO_CUR	<An update or delete was attempted with no current input record>

	.END

!	[End of file RPGMSG.MSG]
