!
! Macros to define VAX/VMS UETP message codes.
!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!  LAST MODIFIED BY:
!
!	V03-003	RNH0006		Richard N. Holstein,	17-Feb-1984
!		Change the text of ERBOXPROC and COPY_LOG to be more readable.
!
!	V03-002	RNH0005		Richard N. Holstein,	21-Jul-1983
!		Add UETP$_DATADEVERR, UETP$_COPY_LOG, UETP$_COPY_LOG_LINE,
!		UETP$_COPY_LOG_ENDED and UETP$_ERBOXPROC.
!
!	V03-001	RNH0004		Richard N. Holstein,	13-Jul-1982
!		Add UETP$_FINISHED and UETP$_NORMAL.
!
!	V02-003	RNH0003		Richard N. Holstein,	13-Jan-1982
!		Set up BASEs such that even though message codes were deleted,
!		the new codes are the same as the old codes.
!
!	V02-001	RNH0002		Richard N. Holstein,	30-Nov-1981
!		RNH0001 broke SATSSS10 which depends on UETP$_DDB.  Put it back
!		in, but comment that it's only a dummy and not to be used.
!
!	V02-001	RNH0001		Richard N. Holstein,	30-Nov-1981
!		Remove obsolete UETP$_CONF, UETP$_DDB and UETP$_UCB.
!
!

	.FACILITY	UETP,116 /SYSTEM

!  *****  WARNINGS  *****
	.SEVERITY	WARNING

	ERBOX		<!/********************!/* Error count = !2UW *!/********************> /FAO=1
	DATAER		<data error on !AS unit !UW byte #!XW good data= !XB bad data= !XB> /FAO=5
	DATADEVERR	<data error on !AS byte #!XW good data= !XB bad data= !XB> /FAO=4
	ERBOXPROC	"!/**********************!/*  !15<!AS!>   *!/*  Error count = !2UW  *!/**********************" /FAO=2

!  *****  SUCCESS  *****
	.SEVERITY	SUCCESS
	.BASE		22

	COPY_LOG	<Copy of log from !AS follows:> /FAO=1
	COPY_LOG_LINE	<!#* !AS> /FAO=2
	COPY_LOG_ENDED	<End of log file from !AS> /FAO=1
	NORMAL		<Normal successful operation> /FAO=0
	FINISHED	<Task completed> /FAO=0
	SATSMS		<test module !AC !AC> /FAO=2
! The DDB message is a dummy that remains only for the benefit of SATSSS10, the
! $GETMSG checking System Service UETP.
	DDB		<UETINIT00 DDB 0 !AS 00000000 00000000> /FAO=1
	.BASE		30

!  *****  ERRORS  *****

	.SEVERITY	ERROR
	.BASE		51

	DEUNUS		<!AS device !AS is unusable, error code= !XL> /FAO=3
	DESTP		<!AS stopped testing !AS unit !UB at !%T> /FAO=4
!  *****  INFO  *****
!

	.SEVERITY	INFORMATIONAL
	.BASE		101

	ABORTC		<!AS to abort this test, type ^C> /FAO=1
	DENOSU		<!AS device !AS is not supported> /FAO=2
	USER		<!AS !UW user!%S running> /FAO=2
	.END
