!---
!
!	Error messages for the MONITOR utility
!
! Version:	'V04-000'
!
!---

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:  VAX/VMS MONITOR Utility
!
! ABSTRACT:
!
!	These are the error messages used by the MONITOR utility.
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, user mode utility,
!	operates in EXEC and KERNEL modes to collect
!	data from protected data bases.
!	Operates at both AST and non-AST level.
!
!	This module contains only non-executable message
!	definitions.
!
! AUTHOR:  Tom Cafarella, Aug, 1981.
!
! MODIFIED BY:
!
!
!	V03-009	PRS1016		Paul R. Senn		4-Apr-1984	14:00
!		Add FILSYNERR message for SHOW DEF.
!
!	V03-009	PRS1012		Paul R. Senn		23-Mar-1984	14:00
!		Add too many files error for MF summary.
!
!	V03-008	TLC1056		Thomas L. Cafarella	22-Mar-1984	11:00
!		Disable journaling classes and exclude class which is disabled.
!
!	V03-007	TLC1053		Thomas L. Cafarella	07-Mar-1984	11:00
!		Add support to ignore unused files for multi-file summary.
!
!	V03-007	PRS1011		Paul R. Senn		29-Feb-1984	14:00
!		add /FLUSH_INTERVAL qualifier
!
!	V03-006	TLC1052		Thomas L. Cafarella	17-Feb-1984	11:00
!		Add multi-file summary capability.
!
!	V03-005	SPC0007		Stephen P. Carney	24-Jun-1983	16:00
!		Add EXECUTE subcommand.
!
!	V03-004	TLC1042		Thomas L. Cafarella	19-Jun-1983	15:00
!		Add /ITEM qualifier for homogeneous classes.
!
!	V03-003	TLC1035		Thomas L. Cafarella	06-Jun-1983	15:00
!		Add homogeneous class type and DISK class.
!
!	V03-002	TLC1028		Thomas L. Cafarella	14-Apr-1983	16:00
!		Add interactive user interface.
!
!	V03-002	TLC1027		Thomas L. Cafarella	14-Apr-1983	16:00
!		Enhance file compatibility features.
!
!	V03-001	TLC1011		Thomas L. Cafarella	29-Mar-1982	20:00
!		Move system service names for SSERROR msg to static storage.
!
!----

!
!	**** NOTE ****	The MONITOR facility number is defined here and in
!			MONITOR.MAR. Any change needs to be made in BOTH places.
!

.LITERAL	MNR$_FACNO = 206	! Define global symbol for facility no.

.FACILITY	MONITOR,MNR$_FACNO /SYSTEM /PREFIX=MNR$_

.SEVERITY	WARNING

CLASNP		<some requested class(es) not present in /INPUT file>
CLASUNK		<some requested class(es) have file structure levels incompatible with the current version of MONITOR>
FILSYNERR	</!AS file specification contains a syntax error>/FAO_COUNT=1

.SEVERITY	ERROR

ERRINPFIL	<error processing /INPUT file>
ERRRECFIL	<error processing /RECORD file>
UNEXPERR	<unexpected error>
SSERROR		<!AC system service error>/FAO_COUNT=1
COLLERR		<error during data collection>
DISPERR		<error during display or summary output>
NOCLASS		<requested /INPUT file classes not found or are incompatible>
CLASDISAB	<class disabled>
SQUALERR	<more than one statistic qualifier specified for !AC class>/FAO=1
PDQUALERR	<more than one display type qualifier specified for !AC class>/FAO=1
QUALINV		</!AS qualifier not valid for !AC class>/FAO_COUNT=2
BEGRAN		<requested beginning time beyond range of /INPUT file>
PREMEOF		<premature end-of-file on /INPUT file>
INVINPFIL	</INPUT file is not a valid MONITOR recording file>
UNSTLEV		</INPUT file has an unsupported MONITOR file structure level>
CLASMISS	<requested class record missing from /INPUT file>
INVBTIMSP	<invalid /BEGINNING time specification>
INVETIMSP	<invalid /ENDING time specification>
INVINTSP	<invalid /INTERVAL specification>
INVVIEWSP	<invalid /VIEWING_TIME specification>
INVCLSNM	<class-name "!AS" is invalid or not uniquely identified>/FAO_COUNT=1
BEGNLEND	<beginning time not earlier than ending time>
NOOUTPUT	<no output selected ... specify /DISPLAY, /RECORD or /SUMMARY>
NOCLASSES	<no classes specified>
ERRPARSE	<error parsing command>
ERRPROMPT	<error prompting for input>
SHOWERR		<SHOW command error>
HELPERR		<HELP command error>
TABLEFULL	<element ID table overflow>
INVITEMNM	</ITEM name "!AS" is invalid or not uniquely identified>/FAO_COUNT=1
ITMNOTDEF	<item requested with the /ITEM qualifier not defined for this revision level>
ERREXECOM	<EXECUTE subcommand is not allowed in execute command file>
ERREXEFIL	<error returning execute command filename from DCL>
ERREXEOPN	<error opening execute command file>
ERREXEREA	<error reading execute command file>
ERREXEREP	<error replacing "@" with "EXECUTE ">
NOCOMMSTLEV	</INPUT files do not have a common file structure level>
NOSUMM		<an input file list may be specified only when /SUMMARY is present>
NOINPFILES	<no useable input files>
TOOMNYFILES	<too many input files specified>
INVFLUSHSP	<invalid /FLUSH_INTERVAL specification>

.SEVERITY	INFORMATIONAL

HIB		<hibernating until requested beginning time....>
IGNFIL		<ignoring input file: !AS>
CONT		<continuing....>

.SEVERITY	FATAL


.END
