	.TITLE	PLI$MSGDEF	PL/I Error Messages
	.IDENT	'1-003'					! Edit: CGN1003
							! Edit: CGN1002
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! 1-002 - Add overflow messages.  CGN 9-AUG-1982
!
! 1-003	- Add NOSELECT message	  CGN 30-DEC-1982
!
! PLIMSG.MSG
!
! These messages are used by programs compiled by the VAX-11 PL/I
! compiler. They are output because of unfielded exceptions which
! occur during execution.
!
 
!	Facility code=30 (PLI)
!	Error number=0
!	Severity=0 (Warning)
	.FACILITY	PLI,30 /SYSTEM /PREFIX=PLI$_ /MACRO=$PLIDEF 

	.SEVERITY	WARNING
	.BASE		0
	VAXCOND	<User defined condition, !XL.> /FAO=1
	ENDPAGE	<PL/I ENDPAGE condition on file '!AD'> /FAO=1
	.severity	fatal
	.base		2
	ENDFILE	<PL/I ENDFILE condition on file '!AD'> /FAO=1
	UNDFILE	<PL/I UNDEFINEDFILE condition on file '!AD'> /FAO=1
	KEY	<PL/I KEY condition on file '!AD'> /FAO=1
	ERROR	<PL/I ERROR condition.>
	ANYCOND	<PL/I ANYCONDITION condition.>
	ZERODIV	<PL/I ZERODIVIDE condition.>
	FIXOVF	<PL/I FIXEDOVERFLOW condition.>
	.severity success
	FINISH	<PL/I Program FINISH condition.>

	.SEVERITY	INFORMATIONAL
	.BASE		10
	PARM	<PL/I compiler/run-time error. Please submit an SPR.>
	CONATTR	<Conflicting attributes specified while opening file.>
	FILEIDENT <PL/I compiler/run-time error. Please submit an SPR.>
	LINESIZE <Invalid LINESIZE specified.>
	PAGESIZE <Invalid PAGESIZE specified.>
	NOVIRMEM <Virtual memory overflow.>
	TITLE	<Invalid TITLE specified.>
	RMSF	<>
	RMSR	<>
	READOP	<PL/I compiler/run-time error. Please submit an SPR.>
	NOTKEYD	<Not a KEYED file.>
	VIRMEMDEAL <PL/I compiler/run-time error. Please submit an SPR.>
	NOKEY	<No KEY or KEYFROM specified.>
	NOTREC	<Not a RECORD file.>
	NOTSQL	<Not a SEQUENTIAL file.>
	OPEN	<Open failure.>
	BADATTR	<File attributes conflict with request.>
	NOCURREC <No current record.>
	NOFROM	<No FROM specified or buffer not allocated.>
	INVDATYP <Invalid data type for record I/O.>
	INVDFNAM <Invalid DEFAULT_FILE_NAME.>
	CONAPPSUP <APPEND and SUPERSEDE conflict.>
	BADRTL	<Invalid file control block or un-initialized FILE VARIABLE.>
	CONPRTFRM <PRINTER_FORMAT conflicts with other attributes or options.>
	INVFORGKEY <Invalid file organization for KEYED access.>
	READOUT	<Attempting to READ from an OUTPUT file.>
	RECORD	<Record length does not match target length.>
	NOTUPDATE <Attempting to REWRITE or DELETE an INPUT or OUTPUT file.>
	WRITEIN	<Attempting to WRITE to an INPUT file.>
	STROVFL	<Stream item too big. Must be less than 1000 characters.>
	RECURSIO <Illegal recursive I/O attempted.>
	NOTOUT	<Attempting to PUT to an INPUT or UPDATE file.>
	NOTSTREAM <Stream I/O attempted on RECORD file.>
	CNVERR	<Conversion error.>
	PROMPTOBIG <PROMPT option too long. Must be < 254 characters.>
	NOTINPUT <Attempting to GET from an OUTPUT or UPDATE file.>
	INVFORMAT <PL/I compiler/run-time error. Please submit an SPR.>
	FORMATOVFL <Too many iteration factors or remote formats.>
	INVFMTPARM <Invalid format parameter specified.>
	INVNUMOPT <PL/I compiler/run-time error. Please submit an SPR.>
	NOTINDEXED <Requested operation requires an INDEXED file.>
	RECIDKEY <RECORD_ID_FROM conflicts with KEY or KEYFROM.>
	IOERROR	<I/O error on file '!AD'> /FAO=1
	NOTPRINT <PAGE or LINE specified for non-PRINT file.>
	INVINDNUM <Invalid INDEX_NUMBER specified.>
	RECID <File not open for RECORD_ID_ACCESS.>
	FXCSIZ <FIXED_CONTROL_SIZE incorrect.>
	INV_KEY <Invalid KEY data type.>
	FILENAME <File name: '!AD'> /FAO=1
	CVTPICERR <Error in picture conversion.>
	CONBLOKIO <BLOCK_IO conflicts with other attributes or options.>
	INVRTVPTR <Invalid RETRIEVAL_POINTERS specified.>
	NOSHARE	<SHARED_READ or SHARED_WRITE conflict with NO_SHARE.>
	INVPROT	<Invalid protection string specified.>
	INVMLTBLK <Invalid MULTIBLOCK_COUNT specified.>
	INVMLTBUF <Invalid MULTIBUFFER_COUNT specified.>
	CONFIXLEN <FIXED_LENGTH_RECORDS conflicts with other attributes or options.>
	INVBLKSIZ <Invalid BLOCK_SIZE specified.>
	INVBKTSIZ <Invalid BUCKET_SIZE specified.>
	INVEXTSIZ <Invalid EXTENSION_SIZE specified.>
	INVFXCSIZ <Invalid FIXED_CONTROL_SIZE specified.>
	CONENVOPT <DECLARED option conflicts with OPEN option.>
	CONPRINTCR <CARRIAGE_RETURN_FORMAT conflicts with PRINT attribute.>
	INVOWNGRP <Invalid OWNER_GROUP specified.>
	INVOWNMEM <Invalid OWNER_MEMBER specified.>
	ENVPARM	<PL/I compiler/run-time error. Please submit an SPR.>
	ENDSTRING <End of string encountered during GET STRING or PUT STRING.>
	INVSTRFMT <Ivalid format item for STRING I/O.>
	CREINDEX  <Attempting to create an indexed file. Use RMS Define.>

	.severity fatal
	INCRETURN	<RETURN statement is incompatible with ENTRY.>
	.severity informational
	INVSKIP		<Invalid value for SKIP option specified.>
	.severity	severe
	SUBRANGE	<Subscript range check error.>
	SUBRANGE1	<Subscript one range check error.>
	SUBRANGE2	<Subscript two range check error.>
	SUBRANGE3	<Subscript three range check error.>
	SUBRANGE4	<Subscript four range check error.>
	SUBRANGE5	<Subscript five range check error.>
	SUBRANGE6	<Subscript six range check error.>
	SUBRANGE7	<Subscript seven range check error.>
	SUBRANGE8	<Subscript eight range check error.>
	SUBSTR2		<Operand two of a SUBSTR is out of range.>
	SUBSTR3		<Operand three of a SUBSTR is out of range.>

	.severity	fatal
	LABELRANGE	<Uninitialized label subscript used.>

	.severity informational
	INVMAXREC	<Invalid MAXIMUM_RECORD_SIZE specified.>

	.severity	severe
	AUTOINIT	<Error in automatic initialization.>

	.severity	informational
	LINOVRFLO	<Line number overflow.>
	PAGOVRFLO	<Page number overflow.>

	.severity	fatal

	NOSELECT	<No WHEN clause selected and no OTHERWISE specified.>

	.END

