.TITLE	CNTVMSMSG - Messages for Documentation Tools CONTENTS Utility
.IDENT	'V04-000'

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:
!   DSR (Digital Standard RUNOFF) /DSRPLUS DSRTOC/CONTENTS Utility
!
! ABSTRACT:
!   This file contains the error message definitions for DSRTOC/CONTENTS
! 
!   New messages are defined in the following manner:
!	1. Enter the message id and text under the appropriate severity level
!	   for DSRTOCSHR below.
!	2. Enter the appropriate literal definition under CONTENTS below
!	3. Enter the appropriate literal definition under DSRTOC below
!	4. Enter the appropriate MACRO definition in the file CNTVMSREQ.R32
!	5. Enter the appropriate EXTERNAL LITERAL reference in the file
!	   CNTVMSREQ.R32
!
! ENVIRONMENT:	 VAX/VMS User Mode
!
! AUTHOR:	 JPK
!
! CREATION DATE: June 1982
!
! MODIFIED BY:
!
!	003	JPK00007	14-Feb-1983
!		Global edit of all sources for CONTENTS/DSRTOC:
!		- module names are now consistant with file names
!		- copyright dates have been updated
!		- facility names have been updated
!		- revision history was updated to be consistant with DSR/DSRPLUS
!
!	002	JPK00006	14-Feb-1983
!		Modified CNTVMS, CONTENTS, FORMAT and CNTVMSMSG to generate
!		error messages for DSRTOC or CONTENTS depending on the 
!		compiletime variant for DSRPLUS (/VARIANT:8192)
!
!--

.FACILITY	DSRTOCSHR,0/SYSTEM/SHARED

.SEVERITY	ERROR

BADVALUE	<'!AS' is an invalid keyword value>		/FAO_COUNT = 1
OPENIN		<error opening '!AS' for input>			/FAO_COUNT = 1
OPENOUT		<error opening '!AS' for output>		/FAO_COUNT = 1
VALERR		<specified value is out of legal range>

.SEVERITY	WARNING

CAPTIONS	<both ".HEADER x" and ".SEND TOC n" captions encountered>
CLOSEQUOT	<the following line is missing a close quote>
CONFQUAL	<conflicting qualifiers>
CTRLCHAR	<the following line contains control characters - ignored>
EMPTYIN		<empty input file '!AS'>			/FAO_COUNT = 1
IGNORED		<'!AS' ignored>					/FAO_COUNT = 1
INVINPUT	<invalid input file format in file '!AS'>	/FAO_COUNT = 1
INVRECORD	<invalid record type in file '!AS'>		/FAO_COUNT = 1
OVERSTRK	<the following line contains an overstrike sequence>

.SEVERITY	SUCCESS

COMPLETE	<processing complete '!AS'>			/FAO_COUNT = 1
CREATED		<'!AS' created>					/FAO_COUNT = 1

.SEVERITY	INFORMATIONAL

IGNORENEW	<".HEADER x" captions will be ignored>
IGNOREOLD	<".SEND TOC n" captions will be ignored>
PROCFILE	<processing file '!AS'>				/FAO_COUNT = 1
TEXTD		<!AD>						/FAO_COUNT = 2 /IDENTIFICATION=TEXT_IS
TMS11		<output file full - continuing with file '!AS'>	/FAO_COUNT = 1


.FACILITY	CONTENTS, 230 /SYSTEM

.SEVERITY	INFORMATIONAL

IDENT		<CONTENTS version !AD>/FAO_COUNT = 2

.LITERAL CONTENTS$_BADVALUE  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_BADVALUE
.LITERAL CONTENTS$_OPENIN    = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_OPENIN
.LITERAL CONTENTS$_OPENOUT   = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_OPENOUT
.LITERAL CONTENTS$_VALERR    = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_VALERR
.LITERAL CONTENTS$_CAPTIONS  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_CAPTIONS
.LITERAL CONTENTS$_CLOSEQUOT = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_CLOSEQUOT
.LITERAL CONTENTS$_CONFQUAL  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_CONFQUAL
.LITERAL CONTENTS$_CTRLCHAR  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_CTRLCHAR
.LITERAL CONTENTS$_EMPTYIN   = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_EMPTYIN
.LITERAL CONTENTS$_IGNORED   = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_IGNORED
.LITERAL CONTENTS$_INVINPUT  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_INVINPUT
.LITERAL CONTENTS$_INVRECORD = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_INVRECORD
.LITERAL CONTENTS$_OVERSTRK  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_OVERSTRK
.LITERAL CONTENTS$_COMPLETE  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_COMPLETE
.LITERAL CONTENTS$_CREATED   = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_CREATED
.LITERAL CONTENTS$_IGNORENEW = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_IGNORENEW
.LITERAL CONTENTS$_IGNOREOLD = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_IGNOREOLD
.LITERAL CONTENTS$_PROCFILE  = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_PROCFILE
.LITERAL CONTENTS$_TEXTD     = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_TEXTD
.LITERAL CONTENTS$_TMS11     = CONTENTS$_FACILITY @ 16 + DSRTOCSHR$_TMS11


.FACILITY	DSRTOC, 202 /SYSTEM

.SEVERITY	INFORMATIONAL

IDENT		<DSRTOC version !AD>/FAO_COUNT = 2

.LITERAL DSRTOC$_BADVALUE  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_BADVALUE
.LITERAL DSRTOC$_OPENIN    = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_OPENIN
.LITERAL DSRTOC$_OPENOUT   = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_OPENOUT
.LITERAL DSRTOC$_VALERR    = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_VALERR
.LITERAL DSRTOC$_CAPTIONS  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_CAPTIONS
.LITERAL DSRTOC$_CLOSEQUOT = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_CLOSEQUOT
.LITERAL DSRTOC$_CONFQUAL  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_CONFQUAL
.LITERAL DSRTOC$_CTRLCHAR  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_CTRLCHAR
.LITERAL DSRTOC$_EMPTYIN   = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_EMPTYIN
.LITERAL DSRTOC$_IGNORED   = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_IGNORED
.LITERAL DSRTOC$_INVINPUT  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_INVINPUT
.LITERAL DSRTOC$_INVRECORD = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_INVRECORD
.LITERAL DSRTOC$_OVERSTRK  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_OVERSTRK
.LITERAL DSRTOC$_COMPLETE  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_COMPLETE
.LITERAL DSRTOC$_CREATED   = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_CREATED
.LITERAL DSRTOC$_IGNORENEW = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_IGNORENEW
.LITERAL DSRTOC$_IGNOREOLD = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_IGNOREOLD
.LITERAL DSRTOC$_PROCFILE  = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_PROCFILE
.LITERAL DSRTOC$_TEXTD     = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_TEXTD
.LITERAL DSRTOC$_TMS11     = DSRTOC$_FACILITY @ 16 + DSRTOCSHR$_TMS11

.END
