.TITLE	NDXVMSMSG -- DSRINDEX/INDEX error messages
.IDENT	'V04-000'

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:
!   DSR (Digital Standard RUNOFF) /DSRPLUS DSRINDEX/INDEX Utility
!
! ABSTRACT:
!   This file contains the error message definitions for DSRINDEX/INDEX
! 
!   New messages are defined in the following manner:
!	1. Enter the message id and text under the appropriate severity level
!	   for INDEXSHR below.
!	2. Enter the appropriate literal definition under INDEX below
!	3. Enter the appropriate literal definition under DSRINDEX below
!	4. Enter the appropriate MACRO definition in the file NDXVMSREQ.R32
!	5. Enter the appropriate EXTERNAL LITERAL reference in the file
!	   NDXVMSREQ.R32
!
! ENVIRONMENT:	 VAX/VMS User Mode
!
! AUTHOR:	 JPK
!
! CREATION DATE: June 1982
!
! MODIFIED BY:
!
!	004	JPK00022	30-Mar-1983
!		Modified NDXVMS, NDXFMT, NDXPAG, NDXVMSMSG and NDXVMSREQ 
!		to generate TEX output. Added module NDXTEX.
!
!	003	JPK00015	04-Feb-1983
!		Cleaned up module names, modified revision history to
!		conform with established standards. Updated copyright dates.
!
!	002	JPK00012	24-Jan-1983
!		Modified NDXVMSMSG.MSG to define error messages for both
!		DSRINDEX and INDEX.
!		Added require of NDXVMSREQ.R32 to NDXOUT, NDXFMT, NDXDAT,
!		INDEX, NDXMSG, NDXXTN, NDXTMS, NDXVMS and NDXPAG for BLISS32. 
!		Since this file defines the error message literals, 
!		the EXTERNAL REFERENCEs for the error message literals 
!		have been removed.
!
!--

.FACILITY	INDEXSHR,0/SYSTEM/SHARED

.SEVERITY	ERROR

BADLOGIC	<internal logic error detected>
BADVALUE	<'!AS' is an invalid keyword value>		/FAO_COUNT = 1
INSVIRMEM	<insufficient virtual memory>
LINELENG	<maximum line length is 120>
NOREF		<page reference not found>
OPENIN		<error opening '!AS' for input>			/FAO_COUNT = 1
OPENOUT		<error opening '!AS' for output>		/FAO_COUNT = 1
TOOMANY		<too many values supplied>
VALERR		<specified value is out of legal range>

.SEVERITY	WARNING

CANTBAL		<can't balance last page>
CLOSEQUOT	<missing close quote>
CONFQUAL	<conflicting qualifiers>
CTRLCHAR	<the following line contains control characters - ignored>
DOESNTFIT	<'!AD' will not fit at the current indentation level>	/FAO_COUNT = 2
DUPBEGIN	<duplicate .XPLUS (BEGIN) - inserted as .XPLUS ()>
EMPTYIN		<empty input file '!AS'>			/FAO_COUNT = 1
IGNORED		<'!AS' ignored>					/FAO_COUNT = 1
INVINPUT	<invalid input file format in file '!AS'>	/FAO_COUNT = 1
INVRECORD	<invalid record type in file '!AS'>		/FAO_COUNT = 1
LASTCONT	<can't generate continuation heading on last page>
NOBEGIN		<.XPLUS (END) with no .XPLUS (BEGIN) - inserted as .XPLUS ()>
NOEND		<.XPLUS (BEGIN) has no corresponding .XPLUS (END)>
NOINDEX		<no index information in file '!AS'>		/FAO_COUNT = 1
NOLIST		<parameter list not allowed>
OVERSTRK	<the following line contains an overstrike sequence>
SKIPPED		<!UL reference!%S inside page range - ignored>	/FAO_COUNT = 1
SYNTAX		<error parsing '!AS'>				/FAO_COUNT = 1
TEXFILE		<error processing line !UL of TEX character file '!AS'>	/FAO_COUNT = 2
TOODEEP		<maximum subindex depth exceeded>
TOOFEW		<not enough values supplied>
TRUNCATED	<string too long - truncated>

.SEVERITY	SUCCESS

COMPLETE	<processing complete '!AS'>			/FAO_COUNT = 1
CREATED		<'!AS' created>					/FAO_COUNT = 1

.SEVERITY	INFORMATIONAL

PROCFILE	<processing file '!AS'>				/FAO_COUNT = 1
TEXT		<!AS>						/FAO_COUNT = 1
TEXTD		<entry text: '!AD'>				/FAO_COUNT = 2 /IDENTIFICATION=TEXT_IS
TMS11		<output file full - continuing with file '!AS'>	/FAO_COUNT = 1


.FACILITY	INDEX, 229 /SYSTEM

.SEVERITY	INFORMATIONAL

IDENT		<INDEX version !AD>/FAO_COUNT = 2

.LITERAL INDEX$_BADLOGIC = INDEX$_FACILITY @ 16 + INDEXSHR$_BADLOGIC
.LITERAL INDEX$_BADVALUE = INDEX$_FACILITY @ 16 + INDEXSHR$_BADVALUE
.LITERAL INDEX$_INSVIRMEM= INDEX$_FACILITY @ 16 + INDEXSHR$_INSVIRMEM
.LITERAL INDEX$_LINELENG = INDEX$_FACILITY @ 16 + INDEXSHR$_LINELENG
.LITERAL INDEX$_NOREF    = INDEX$_FACILITY @ 16 + INDEXSHR$_NOREF
.LITERAL INDEX$_OPENIN   = INDEX$_FACILITY @ 16 + INDEXSHR$_OPENIN
.LITERAL INDEX$_OPENOUT  = INDEX$_FACILITY @ 16 + INDEXSHR$_OPENOUT
.LITERAL INDEX$_TOOMANY  = INDEX$_FACILITY @ 16 + INDEXSHR$_TOOMANY
.LITERAL INDEX$_VALERR   = INDEX$_FACILITY @ 16 + INDEXSHR$_VALERR
.LITERAL INDEX$_CANTBAL  = INDEX$_FACILITY @ 16 + INDEXSHR$_CANTBAL
.LITERAL INDEX$_CLOSEQUOT= INDEX$_FACILITY @ 16 + INDEXSHR$_CLOSEQUOT
.LITERAL INDEX$_CONFQUAL = INDEX$_FACILITY @ 16 + INDEXSHR$_CONFQUAL
.LITERAL INDEX$_CTRLCHAR = INDEX$_FACILITY @ 16 + INDEXSHR$_CTRLCHAR
.LITERAL INDEX$_DOESNTFIT= INDEX$_FACILITY @ 16 + INDEXSHR$_DOESNTFIT
.LITERAL INDEX$_DUPBEGIN = INDEX$_FACILITY @ 16 + INDEXSHR$_DUPBEGIN
.LITERAL INDEX$_EMPTYIN  = INDEX$_FACILITY @ 16 + INDEXSHR$_EMPTYIN
.LITERAL INDEX$_IGNORED  = INDEX$_FACILITY @ 16 + INDEXSHR$_IGNORED
.LITERAL INDEX$_INVINPUT = INDEX$_FACILITY @ 16 + INDEXSHR$_INVINPUT
.LITERAL INDEX$_INVRECORD= INDEX$_FACILITY @ 16 + INDEXSHR$_INVRECORD
.LITERAL INDEX$_LASTCONT = INDEX$_FACILITY @ 16 + INDEXSHR$_LASTCONT
.LITERAL INDEX$_NOBEGIN  = INDEX$_FACILITY @ 16 + INDEXSHR$_NOBEGIN
.LITERAL INDEX$_NOEND    = INDEX$_FACILITY @ 16 + INDEXSHR$_NOEND
.LITERAL INDEX$_NOINDEX  = INDEX$_FACILITY @ 16 + INDEXSHR$_NOINDEX
.LITERAL INDEX$_NOLIST   = INDEX$_FACILITY @ 16 + INDEXSHR$_NOLIST
.LITERAL INDEX$_OVERSTRK = INDEX$_FACILITY @ 16 + INDEXSHR$_OVERSTRK
.LITERAL INDEX$_SKIPPED  = INDEX$_FACILITY @ 16 + INDEXSHR$_SKIPPED
.LITERAL INDEX$_SYNTAX   = INDEX$_FACILITY @ 16 + INDEXSHR$_SYNTAX
.LITERAL INDEX$_TEXFILE  = INDEX$_FACILITY @ 16 + INDEXSHR$_TEXFILE
.LITERAL INDEX$_TOODEEP  = INDEX$_FACILITY @ 16 + INDEXSHR$_TOODEEP
.LITERAL INDEX$_TOOFEW   = INDEX$_FACILITY @ 16 + INDEXSHR$_TOOFEW
.LITERAL INDEX$_TRUNCATED= INDEX$_FACILITY @ 16 + INDEXSHR$_TRUNCATED
.LITERAL INDEX$_COMPLETE = INDEX$_FACILITY @ 16 + INDEXSHR$_COMPLETE
.LITERAL INDEX$_CREATED  = INDEX$_FACILITY @ 16 + INDEXSHR$_CREATED
.LITERAL INDEX$_PROCFILE = INDEX$_FACILITY @ 16 + INDEXSHR$_PROCFILE
.LITERAL INDEX$_TEXT     = INDEX$_FACILITY @ 16 + INDEXSHR$_TEXT
.LITERAL INDEX$_TEXTD    = INDEX$_FACILITY @ 16 + INDEXSHR$_TEXTD
.LITERAL INDEX$_TMS11    = INDEX$_FACILITY @ 16 + INDEXSHR$_TMS11


.FACILITY	DSRINDEX, 201/SYSTEM

.SEVERITY	INFORMATIONAL

IDENT		<DSRINDEX version !AD>/FAO_COUNT = 2

.LITERAL DSRINDEX$_BADLOGIC = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_BADLOGIC
.LITERAL DSRINDEX$_BADVALUE = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_BADVALUE
.LITERAL DSRINDEX$_INSVIRMEM= DSRINDEX$_FACILITY @ 16 + INDEXSHR$_INSVIRMEM
.LITERAL DSRINDEX$_LINELENG = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_LINELENG
.LITERAL DSRINDEX$_NOREF    = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_NOREF
.LITERAL DSRINDEX$_OPENIN   = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_OPENIN
.LITERAL DSRINDEX$_OPENOUT  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_OPENOUT
.LITERAL DSRINDEX$_TOOMANY  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TOOMANY
.LITERAL DSRINDEX$_VALERR   = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_VALERR
.LITERAL DSRINDEX$_CANTBAL  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_CANTBAL
.LITERAL DSRINDEX$_CLOSEQUOT= DSRINDEX$_FACILITY @ 16 + INDEXSHR$_CLOSEQUOT
.LITERAL DSRINDEX$_CONFQUAL = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_CONFQUAL
.LITERAL DSRINDEX$_CTRLCHAR = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_CTRLCHAR
.LITERAL DSRINDEX$_DOESNTFIT= DSRINDEX$_FACILITY @ 16 + INDEXSHR$_DOESNTFIT
.LITERAL DSRINDEX$_DUPBEGIN = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_DUPBEGIN
.LITERAL DSRINDEX$_EMPTYIN  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_EMPTYIN
.LITERAL DSRINDEX$_IGNORED  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_IGNORED
.LITERAL DSRINDEX$_INVINPUT = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_INVINPUT
.LITERAL DSRINDEX$_INVRECORD= DSRINDEX$_FACILITY @ 16 + INDEXSHR$_INVRECORD
.LITERAL DSRINDEX$_LASTCONT = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_LASTCONT
.LITERAL DSRINDEX$_NOBEGIN  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_NOBEGIN
.LITERAL DSRINDEX$_NOEND    = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_NOEND
.LITERAL DSRINDEX$_NOINDEX  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_NOINDEX
.LITERAL DSRINDEX$_NOLIST   = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_NOLIST
.LITERAL DSRINDEX$_OVERSTRK = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_OVERSTRK
.LITERAL DSRINDEX$_SKIPPED  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_SKIPPED
.LITERAL DSRINDEX$_SYNTAX   = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_SYNTAX
.LITERAL DSRINDEX$_TEXFILE  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TEXFILE
.LITERAL DSRINDEX$_TOODEEP  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TOODEEP
.LITERAL DSRINDEX$_TOOFEW   = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TOOFEW
.LITERAL DSRINDEX$_TRUNCATED= DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TRUNCATED
.LITERAL DSRINDEX$_COMPLETE = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_COMPLETE
.LITERAL DSRINDEX$_CREATED  = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_CREATED
.LITERAL DSRINDEX$_PROCFILE = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_PROCFILE
.LITERAL DSRINDEX$_TEXT     = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TEXT
.LITERAL DSRINDEX$_TEXTD    = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TEXTD
.LITERAL DSRINDEX$_TMS11    = DSRINDEX$_FACILITY @ 16 + INDEXSHR$_TMS11

.END
