	.TITLE	INSMSG
	.IDENT "V04-000"
! 
! INSTALL UTILITY MESSAGES 
! 
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!  AUTHOR:	Bob Grosso
!
!  DATE:	23-Jun-1983
!
!  MODIFIED BY:
!
!	V03-012	MSH0065		Michael S. Harvey	17-Jul-1984
!		Add IMGTRACED message.
!
!	V03-011	MSH0048		Michael S. Harvey	15-May-1984
!		Add NOPREV and DELETED messages for improved REPLACE status
!		processing.
!
!	V03-010	MSH0047		Michael S. Harvey	14-May-1984
!		Add SYSVERDIF message.
!
!	V03-009	MSH0024		Michael S. Harvey	31-Mar-1984
!		Eliminate obsolete error message. Enhance NOHDRRES message.
!
!	V03-008	MSH0015		Michael S. Harvey	23-Mar-1984
!		Clarify NOGBLSEC message by including image name.
!
!	V03-007	MSH0018		Michael S. Harvey	7-Mar-1984
!		Remove NAMTOOLNG error message. It's obsolete now that
!		global sections can handle 39 character file names.
!
!	V03-006	MSH0017		Michael S. Harvey	7-Mar-1984
!		Modify EXISTS message to clarify why certain images cannot
!		be installed.
!
!	V03-005	MSH0015		Michael S. Harvey	6-Mar-1984
!		Add NOGBLSEC message to be used to warn the user when a
!		shareable image has no global sections created for it upon
!		installation.
!
!	V03-004	BLS0256		Benn Schreiber		27-Dec-1983
!		First letter of each message should not be uppercased.
!		Delete obsolete messages.  Add new message for not enough
!		paged dynamic memory.
!
!	V03-003	RPG0003		Bob Grosso		15-Sep-1983
!		Add NAMTOOLNG message when an image with a name
!		longer than 11 characters is installed /SHARED.
!
!	V03-002	RPG0002		Bob Grosso		20-Aug-1983
!		Change removed message to include file spec.
!		Fill in some missing explainations.
!
!	V03-001	RPG0001		Bob Grosso		29-July-1983
!		Add better explainations.
!		Add new messages, FAIL and FAILGETVM.
! 
!--------------------------------------------------------------------

	.FACILITY	INSTALL,123 /SYSTEM /PREFIX=INS$_


	.SEVERITY	INFORMATION


	EMPTYLST		<Known File Entry List is empty>
	!
	!	There are no Known Files in the Known File Entry List.
	!	Therefore LIST, DELETE, and PURGE won't accomplish anything.

	HELP			<enter /HELP for INSTALL help>
	!	To obtain help from INSTALL, enter the command /HELP.
	!	Entering HELP will cause INSTALL to attempt to install
	!	the image SYS$SYSTEM:HELP.EXE.

	NOLIST			<there is no Known File Entry List>
	!
	!	The Known File Entry List has not yet been created.
	!	It will be created when the first image is installed.

	REMOVED/FAO_COUNT = 1	<entry for !AS has been removed>
	!
	!	A Known File Entry for a file which had been
	!	deleted was successfully removed.  No user action is
	!	required.


	.SEVERITY	WARNING


	DELETED			<previous Known File Entry has been deleted>
	!
	!	Message indicating that first half of REPLACE command has
	!	succeeded, despite any subsequent command failure or success.

	HDRNOTRES		<unable to make image header resident>

	NOGBLSEC/FAO_COUNT=1	<no global sections created for !AS>
	!
	!	A shareable image is installed that doesn't have any ISDs that can be
	!	converted into global sections.

	NOHDRRES/FAO_COUNT=1	<compatibility mode image, !AS, can not be header resident>
	!
	!	The /HEADER qualifier was ignored since there is no gain 
	!	in making Compatability Mode Images header resident.

	NOPREV/FAO_COUNT = 1	<no previous entry exists - new entry created for !AS>
	!
	!	A Known File Entry was created via the REPLACE command, but
	!	no previous entry had been there to be deleted first.

	NOSHRD			<file can not be made shared>
	!
	!	The /SHARED qualifier was ignored since this file requires
	!	an AME other than the RSX AME.


	.SEVERITY	ERROR


	CONFQUAL		<conflicting qualifiers>
	!
	!
	!	One or more of the qualifiers conflicted.  Check to see
	!	that only one operation is requested.

	EXISTS			<Known File Entry for a version of this file already exists>
	!
	!	Failed to create an entry since one already exists.

	FAIL/FAO_COUNT=2	<failed to !AS entry for !AS>
	!
	!	The requested operation was not completed.
	!	An accompanying message should contain the explanation

	FAILED/FAO_COUNT=1	<failed to perform !AS operation>
	!
	!	The requested operation was not completed.
	!	An accompanying message should contain the explanation

	FAILGETVM/FAO_COUNT=1	<failed to allocate !UL bytes of virtual memory>
	!
	! An error occurred when INSTALL attempted to allocate virtual memory.
	! Check the accompanying error message to determine whether
	! the virtual address space has been exceeded, or whether
	! a program error has been uncovered. 


	IMGHDR			<error while accessing image header>
	!
	!	An error was returned by one of the shared routines
	!	which INSTALL uses to access the image header.  An 
	!	accompanying message should explain the problem.

	IMGTRACED  </TRACEBACK image cannot be privileged or execute_only>
	!
	!	An image linked with /TRACEBACK is specified for a
	!	CREATE or REPLACE command and either the /PRIVILEGED
	!	or /EXECUTE_ONLY qualifier also had been specified.

	INTRNLERR/FAO_COUNT=1	<Internal Error: !AS>
	!
	!	An inconsistent program or data state was encountered
	!	indicating a logic error in INSTALL.  Please submit an 
	!	SPR with a machine readable system crash dump.

	INVPRVNAM/FAO_COUNT=1	<!AS is not a valid privilege>
	!
	!	The named privilege is not recognized.  Check the spelling
	!	and re-enter.

	IVQUAL			<invalid qualifier>
	!
	!	One of the qualifiers is not permitted for the specified 
	!	operation.

	NOCMK			<operation requires CMKRNL privilege>
	!
	!	Even if INSTALL is installed with the CMKRNL privilege,
	!	the process executing INSTALL must have CMKRNL privilege
	!	to execute the requested function.

	NOKFEFND		<Known File Entry not found>
	!
	!	The requested operation could not be performed because
	!	a Known File Entry could not be found for this file.

	NOLOAD			<network and sequentially loaded files are not installable>
	!
	!	Network or other sequentially loaded files such as files 
	!	residing on magtape, may not be installed.

	NOPAGEDYN		<unable to allocate enough paged dynamic memory>

	NOVER/FAO_COUNT=1	<no file version obtained for !AS>
	!
	!	During a LIST operation, the attempt to look up the version
	!	number for the file failed.  The reason for failure should
	!	appear in an accompanying message.

	PRVNOTUNQ/FAO_COUNT=1	<privilege name !AS is not unique>
	!
	!	One of the privileges listed did not contain enough characters
	!	to make it unique.  Spell it out.

	SYSVERDIF		<system version mismatch - please relink>
	!
	!	The image was not linked against the current version of
	!	the system. It should be relinked.

	.END
