.TITLE		EDFMSG	Messages for the FDL Editor
!
! Version:	'V04-000'
!
! ++
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!
! FACILITY:		VAX/VMS EDF (EDIT/FDL) UTILITY
!
! ABSTRACT:		This facility is used to create, modify, and optimize
!			FDL specification files.
!
! ENVIRONMENT:		NATIVE/USER MODE
!
! AUTHOR:		Ken F. Henderson Jr.
!
! CREATION DATE:	27-Mar-1981
!
! MODIFIED BY:
!
!			V03-004 RRB0018	   Rowland R. Bradley	10 Mar 1984
!				Added FNF message
!
!			V03-003	KFH0003		Ken Henderson	14 Apr 1983
!				Added INSFANL message
!
!			V03-002	KFH0002		Ken Henderson	26 Jan 1983
!				Shortened text of messages that
!				user never sees
!
!			V03-001	KFH0001		Ken Henderson	18 Nov 1982
!				Removed INTSWERR error
!
! --


.FACILITY	EDF, 	179	/SYSTEM		/PREFIX=EDF$_

.SEVERITY	SEVERE

DEVCLASS	<device class of SYS$INPUT must be terminal> /FAO=0
SMALLPAGE	<terminal size (!UL columns by !UL lines) is too small> /FAO=2
INSFANL		<insufficient data in Definition and/or Analysis files>
FNF		<error opening AS!> /FAO=1

.SEVERITY	WARNING

AMBIG		<ambig> /FAO=0
BADSYNTAX	<syn err> /FAO=0
BADVALUE	<bad val> /FAO=0
NODEFAULT	<no dflt> /FAO=0

.SEVERITY	INFORMATIONAL
CTRLZ		<^Z> /FAO=0

.END
