!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

! MODIFIED BY:
!
!	V03-010	JAK0217		J A Krycka	06-Jul-1984
!		Minor edits to message text for completeness.
!		Add JBC$_DIAG_DATA and JBC$_DIAG_TEXT messages.
!
!	V03-009	JAK0209		J A Krycka	08-May-1984
!		Add JBC$_STRUCT_LEVEL and JBC$_DIAGNOSTIC messages.
!
!	V03-008	MLJ0115		Martin L. Jack,	30-Jul-1983
!		Changes for job controller baselevel.
!
!	V03-007	MLJ0114		Martin L. Jack,	23-Jun-1983
!		Changes for job controller baselevel.
!
!	V03-006	MLJ0113		Martin L. Jack,	26-May-1983
!		Changes for job controller baselevel.
!
!	V03-005	MLJ0109		Martin L. Jack,	14-Apr-1983
!		Changes for job controller baselevel.
!
!	V03-004	MLJ0107		Martin L. Jack,	04-Mar-1983
!		Put back JBC$_NORMAL.
!
!	V03-003	MLJ0106		Martin L. Jack,	01-Mar-1983
!		Changes for job controller baselevel.
!
!	V03-002	MLJ0103		Martin L. Jack,	07-Jan-1983
!		Changes for job controller baselevel.
!
!	V03-001	MLJ0086		Martin L. Jack,	03-Apr-1982
!		Clarify text of TRMMBXUSE, QUEERR, CREQERR.  Delete INIQERR,
!		QUESHRKERR, QUEEXPAERR, QUECHKPERR.  Add NEWQUEUE.

.facility JBC,4/system/macro=$JBCMSGDEF
.severity warning
.base 0
!
! Codes returned by $SNDSMB, $SNDACC, $SNDJBC services, or placed in the
! accounting file.  These values are public and must not change from release
! to release.
!
.literal	JBC$_NORMAL=262145
ILLDEVNAM	<>
UNSDEVTYP	<>
ILLFILNAM	<>
INVQUENAM	<invalid queue name>
NOPRIV		<insufficient privilege or queue protection violation>
NOQUEHDR	<>
NOQUESPACE	<no space in system job queue file>
NOSUCHQUE	<no such queue>
NOSUCHJOB	<no such job>
NOOPENJOB	<no open job for requesting process>
REFERENCED	<existing references prevent deletion>
STARTED		<queue already started>
INVITMCOD	<invalid item code or option code>
INVFUNCOD	<invalid function code>
EMPTYJOB	<no files specified in job request>
JOBQUEDIS	<system job queue manager is not running>
JOBABORT	<job aborted during execution>
ACMINVOP	<>
INVPARLEN	<invalid parameter length>
TRMMBXUSE	<>
MAXSYMEXD	<>
SCTTABFUL	<>
CREPRCFAL	<>
SYMNTBFUL	<>
NODSTQUE	<no such destination queue>
INVDSTQUE	<invalid destination queue>
JOBDELETE	<job deleted before execution>
NORESTART	<job not restartable>
JOBREQUEUE	<job requeued during execution>
QUERESET	<queue was reset during execution>
SYSFAIL		<system failed during execution>
EXECUTING	<job executing on queue prevents requested operation>
INVMSGBUF	<invalid message buffer>
MISREQPAR	<missing required parameter>
INVPARVAL	<invalid parameter value>
INCQUETYP	<inconsistent queue type>
INCDSTQUE	<inconsistent destination queue type>
JOBQUEENA	<system job queue manager is already running>
NOTASSIGN	<queue not assigned>
INCOMPLETE	<previous incomplete operation prevents execution>
INVCHANAM	<invalid characteristic name>
INVFORNAM	<invalid form name>
NOSUCHCHAR	<no such characteristic>
NOSUCHFORM	<no such form>
DUPFORM		<duplicate form number>
INCFORMPAR	<inconsistent form parameters>
NOSUCHFILE	<no such file>
DELACCESS	<file protection does not allow delete access>
!
! Messages signalled by job controller.  These values may change.
!
.severity warning
.base 128
ACCDISERR	<accounting disabled due to file errors>
ALLOCMEM	<error allocating virtual memory>
COMREMJBC	<error communicating with another job controller>
INVBLOCK	<invalid operation on queue block !UL>/FAO=1
INVMSG		<invalid mailbox message received>
NEWQUEUE	<new system job queue file !AS created>/FAO=1
OPEJBCMBX	<error opening job controller mailbox>
PRCREAT		<error creating process>
QUEFORMAT	<system job queue file has invalid format>
REAJBCMBX	<error reading job controller mailbox>
REQUEST		<service required on queue !AC for job !AC user !AD!/!AF>/FAO=4
SETIMR		<error setting timer>
SYMCREPRC	<error creating symbiont process for !AS>/FAO=1
SYMDEL		<unexpected symbiont process termination>
WRIRSPMSG	<error writing system service response message>
WRISMBMBX	<error writing symbiont mailbox>
NFY_COMPLETE	<Job !AC (queue !AC, entry !UL) completed>/FAO=3
NFY_CURRENT	<Job !AC (queue !AC, entry !UL) started on !AC>/FAO=4
NFY_HOLD	<Job !AC (queue !AC, entry !UL) holding>/FAO=3
NFY_PENDING	<Job !AC (queue !AC, entry !UL) pending>/FAO=3
NFY_TIMER	<Job !AC (queue !AC, entry !UL) holding until !17%D>/FAO=4
STRUCT_LEVEL	<system job queue file has incompatible structure level of !XW>/FAO=1
DIAGNOSTIC	<!AS>/FAO=1
DIAG_TEXT	<diagnostic (!UL): !AS !XL !XL>/FAO=4
DIAG_DATA	<diagnostic (!UL): !XL !XL !XL !XL>/FAO=5
.end
