	.TITLE	VAX$STATUS - Status Definitions for VAX-11 Instruction Emulator
	.IDENT	"V04-000"

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! Facility:
!
!	VAX-11 Instruction Emulator
!
! Abstract:
!
!	This file contains status codes for exceptions that are specific
!	to the VAX-11 instruction emulator.
!
! Author:
!
!	Lawrence J. Kenah
!
! Creation Date:
!
!	23 March 1983
!
!	V01-002	LJK0021		Lawrence J. Kenah	17-Mar-1984
!		Add status code for DIVP internal error
!
!	V01-001	Original	Lawrence J. Kenah	23-Mar-1983
!		Original version of this module
!--


	.FACILITY	VAX , 19 /SYSTEM /PREFIX=VAX$_

	.SEVERITY	FATAL		! All of these are fatal

! The first two codes merely define exception names that are associated with 
! the two exceptions defined in the microVAX architecture to support 
! software emulation of the decimal and string instructions.

	OPCDEC		<reserved opcode (code=!XL) attempted at PC=!XL> /FAO=2

	OPCDEC_FPD	<reserved opcode (code=!XL) attempted with FPD set at PC=!XL> /FAO=2

! If an exception occurs and the exception dispatch logic determines that the
! emulator was not entered in a standard way, this code is appended to the
! beginning of the signal array and the new exception is reflected back to
! the VMS exception dispatcher. 

	ABORT		<exception (name=!XL) occurred after nonstandard entry into emulator> /FAO=1

! There are currently two consistency check made by the emulator that can
! result in conditions not already covered by the VAX Architecture. Both
! exceptions consist of the VAX$_INTERNAL status code followed by a longword
! code that indicates the particular consistency check that failed. Note that
! if the assumptions made by the logic in the emulator are correct, these
! errors will NEVER be generated. 

	INTERNAL	<internal consistency error (type=!XL) detected by emulator> /FAO=1

! The algorithm used in the subtraction of packed decimal strings makes a
! decision about the sign of the final result. This choice demands that the
! final subtraction NOT produce a borrow. If a borrow results from the final
! subtraction, this error is generated to indicate that the algorithm is in
! error. 

	.LITERAL	VAX$_SUBPx_ERROR	

! There are two indepdent counts of the byte count in the divisor string in 
! VAX$DIVP. If these counts are inconsistent, the following error is 
! generated.

	.LITERAL	VAX$_DIVP_ERROR	

	.END
