	.TITLE	UTIL$LNK_MSGS Error messages for obj module dissector
	.IDENT	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!

.FACILITY	UTIL,286/SYSTEM /PREFIX=LNK$_

.SEVERITY	ERROR

BADCCC		<illegal compilation code (!UL.) in module !AC>/FAO=2
EOMERROR	<compilation errors in module !AC>/FAO=1
EOMFATAL	<fatal compilation errors in module !AC>/FAO=1
EOMWARN		<compilation warnings in module !AC>/FAO=1
GSDTYP		<illegal GSD record type (!UL.) in module !AC>/FAO=2
ILLFMLCNT	<minimum argument count exceeds maximum for procedure !AC in module !AC>/FAO=2
ILLMODNAM	<illegal module name length (!UL.) for module !AC>/FAO=2
ILLPSCLEN	<psect !AC has illegal length (!UL.) in module !AC>/FAO=3
ILLRECLEN	<illegal record length (!UL.) in module !AC>/FAO=2
ILLRECLN2	<illegal record length (!UL)>/FAO=1/ID=ILLRECLEN
ILLRECTYP	<illegal record type (!UL.) in module !AC>/FAO=2
ILLRECTY2	<illegal record type (!UL)>/FAO=1/ID=ILLRECTYP
ILLSYMLEN	<symbol !AC has illegal length (!UL.) in module !AC>/FAO=3
NOEOM		<module !AC does not contain end of module record>/FAO=1
RECTOOSML	<data overflows object record in module !AC>/FAO=1
SEQUENCE	<illegal record sequence in module !AC>/FAO=1
SEQUENCE2	<illegal record sequence>/ID=SEQUENCE
STRLVL		<illegal object language structure level in module !AC>/FAO=1

	.END
