! OPCMSG.MSG - system definition file for OPCOM
!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the source for OPCOM messages.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  1-Aug-1976
!
! MODIFIED BY:
!
!	V03-013	CWH3013		CW Hobbs			2-Sep-1984
!		Restore the embedded <CR><LF> in RQST_PROMPT which was
!		removed in ACG0449.
!
!	V03-012	ACG0449		Andrew C. Goldstein,	31-Aug-1984  13:41
!		Fix text of "counterfeit security alarm" message
!
!	V03-011	CWH3011		CW Hobbs			18-May-1984
!		Change the <CR> in OPREPLY to a !/ directive.
!
!	V03-010	MHB0158		Mark Bramhall			 7-May-1984
!		Fix up the security alarm message.
!
!	V03-009	CWH3169		CW Hobbs			5-May-1984
!		Second pass for cluster-wide OPCOM:
!		 - Change several messages to use the standard header, only
!		   a few still use the short header.
!		 - Change the format of the header slightly, make it more
!		   clear when messages come from other nodes.
!		 - Remove the UDA50MVER and TM78MVER messages and replace
!		   them with the single, generic CTLRUCODE message.
!		 - Add the CLU_NOQUORUM connection manager message - it
!		   was apparently never put in.
!
!	V03-008	CWH3008		CW Hobbs			12-Apr-1984
!		Change some of the connection manager messages
!
!	V03-007	RSH0114		R. Scott Hanna			12_Mar-1984
!		Change the OPC$_COUNTERFEIT message.
!
!	V03-006	RSH0110		R. Scott Hanna			28-Feb-1984
!		Change the FAO arguments in the OPC$_SECUR_ALARM message.
!
!	V03-005	CWH3005		CW Hobbs			27-Sep-1983
!		Improve connection manager messages.
!
!	V03-004	CWH3004		CW Hobbs			16-Sep-1983
!		Shorten HEADER
!
!	V03-003	CWH3003		CW Hobbs			16-Sep-1983
!		Add connection manager messages.
!
!	V03-002	CWH3001		CW Hobbs			30-Jul-1983
!		Various and sundry things to make OPCOM distributed
!		across the cluster.
!
!	V03-001	RLRV3A1		Robert L. Rappaport	5-Apr-1982
!		Added MSG$_UDA50MVER and MSG$_DUPUNITNO.
!
! V02-006	STJ0180		Steven T. Jeffreys,	07-Jan-1981
!		Added MVCOMPLETE and MVABORTED messages, and slightly
!		change the test of the existing mount verification messages.
!
! V02-005	STJ0079		Steven T. Jeffreys,	31-Jul-1981
!		Added BLANK message for the mag. tape ACP.
!
! V02-004	STJ0063		Steven T. Jeffreys,	14-Jul-1981
!		Added an alternate CANCEL message.
!		Added an INITIALIZE message for the mag. tape ACP.
!		Added messages for mount verification support.
!
! V02-003	STJ0042		Steven T. Jeffreys,	22-May-1981
!		Change format of RQSTCMPLTE, RQSTABORT, and RQSTPEND
!		to be enable existing code to parse the messages.
!
! V02-002	STJ0028		Steven T. Jeffreys,	29-Mar-1981
!		Modify existing messages and add new ones as part of
!		the support for the new OPCOM.

!+
! OPERATOR COMMUNICATIONS MESSAGES 
!-
 
	.FACILITY	OPCOM,5 /SYSTEM /PREFIX=OPC$_ /MACRO=$OPCMSG
	.SEVERITY	SUCCESS
	.BASE		0

	TERMENAB	<%D%Operator !AS has been enabled, username !AF> /FAO=3
	LOGINIT		<%D%Logfile has been initialized by operator !AS!/Logfile is !AS> /FAO=2
	TERMDSBL	<%D%Operator !AS has been disabled, username !AF> /FAO=3

	.SEVERITY	FATAL

	RQSTABORT	<!AS!/!%T, request !UL was aborted by operator !AS> /FAO=3

	.SEVERITY	SUCCESS

	RQSTPEND	<!AS!/!%T, request !UL is pending by operator !AS> /FAO=3
	RQSTCMPLTE	<!AS!/!%T, request !UL was completed by operator !AS> /FAO=3

	.SEVERITY	FATAL

	LOGFAIL		<%D%Failed logfile operation on file !AS!/!AS> /FAO=2
	TERMFAIL	<%D%Failed to enable terminal> /FAO=1
	NOSUCHRQST	<%D%No such request> /FAO=1
	DEVOFFLINE	<%D%Device !AS is offline> /FAO=1
	DEVONLINE	<%D%Device !AS is online> /FAO=1
	NOCLI		<no command interpreter>

	.SEVERITY	SUCCESS

	NOPERATOR	<%D%No operator coverage> /FAO=1

	.SEVERITY	FATAL

	UNKNOPR		<unknown operator>
	DEVNOTERM	<illegal source operator device>
	ILLRQST		<%D%An illegal operator request was made> /FAO=1
	RQSTCAN		<%D%Request !UL was canceled> /FAO=2

	.SEVERITY	SUCCESS

	OPRNOTIF	<operator has been notified, waiting... !%T> /FAO=1
	OPREPLY		<!/!AD> /FAO=2
	LOGTIME		<%D%Logfile time stamp> /FAO=1

	.SEVERITY	FATAL

	LOGCLOS		<%D%Logfile was closed by operator !AS!/Logfile was !AS> /FAO=3

	.SEVERITY	INFORMATIONAL

	USERQST		<%D%Request !UL, from user !AF!AS!AF!/!AS> /FAO=6
	USERMSG		<%D%Message from user !AF!AS!AF!/!AS> /FAO=6
	LOGSTS		<%D%Logfile status for file !AS!/!AS> /FAO=3
	OPERSTS		<%D%Operator status for operator !AS!/!AS> /FAO=4
	RQSTSTST	<%D%Request status for request !UL!/!AS> /FAO=3
	SHUTDOWN	<%D%OPCOM shutting down.   Requested by operator !AS> /FAO=2

	SYSTEMOPER	<SYSTEM>
	GROUPOPER	<GROUP>
	USEROPER	<USER>

	NOTENABLED	<!8* *** disabled ***>
	!
	! The following messages give the ASCII text for the operator types.  It is
	! possible to change the message text to anything desired.  For example, an
	! installation might want to call OPER12 by another name, say FRONT_DESK.
	! That installation would change the line with OPER12 to read:
	!
	!			OPER12	<FRONT_DESK>
	!
	! Afterwards, users on that system could REPLY /ENABLE=FRONT_DESK, REQUEST /TO=FRONT,
	! a FRONT_DESK operator could do a REPLY /STAT and see that FRONT_DESK was enabled.
	! Of course, a programmer on that system would use the symbol OPC$_OPER12 to send
	! a message to the FRONT_DESK, since the message name can NOT be changed.
	!
	CENTRL		<CENTRAL>
	PRINT		<PRINTER>
	TAPES		<TAPES>
	DISKS		<DISKS>
	DEVICE		<DEVICES>
	CARDS		<CARDS>
	NTWORK		<NETWORK>
	CLUSTER		<CLUSTER>
	SECURITY	<SECURITY>
	REPLY		<REPLY>
	SOFTWARE	<SOFTWARE>
	FILL_11		<FILL_11>
	OPER1		<OPER1>
	OPER2		<OPER2>
	OPER3		<OPER3>
	OPER4		<OPER4>
	OPER5		<OPER5>
	OPER6		<OPER6>
	OPER7		<OPER7>
	OPER8		<OPER8>
	OPER9		<OPER9>
	OPER10		<OPER10>
	OPER11		<OPER11>
	OPER12		<OPER12>
	!
	DEVOFFLINX	<%D%Device !AS is offline.!/Mount verification is in progress.>/FAO=1
	WRONGVOL	<%D%Device !AS contains the wrong volume.!/Mount verification is in progress.>/FAO=1
	DEVWRTLCK	<%D%Device !AS has been write locked.!/Mount verification is in progress.>/FAO=1
	!
	INITAPE		<!AS!/!%T, request !UL was completed by operator !AS> /FAO=3
	RQSTDONE	<%D%Request !UL was satisfied.> /FAO=1
	BLANKTAPE	<!AS!/!%T, request !UL was completed by operator !AS> /FAO=3
	!
	MVCOMPLETE	<%D%Mount verification has completed for device !AS> /FAO=1
	MVABORTED	<%D%Mount verification has aborted for device !AS> /FAO=1
	CTLRUCODE	<%D%Microcode for device !AS (!AC controller) is not up to the current revision level> /FAO=3
	DUPUNITNO	<%D%MSCP controller - duplicate unit number !AS> /FAO=1
	SECUR_ALARM	<%D%Security alarm!AS!AF!AS> /FAO=4
	COUNTERFEIT	<%D%Invalid security alarm from !AF!AS!AF> /FAO=5

	.SEVERITY	INFORMATIONAL

	NODE_ACTIVE	"%D%OPCOM on !AS is activating !AS, csid !XL, system !UL!/Have established communications, placing node in ACTIVE state." /FAO=6
	NODE_DELETE	"%D%OPCOM on !AS deleting !AS, csid !XL, system !UL!/Node has not been visible for longer than maximum time allowed." /FAO=6
	NODE_DEPARTED	"%D%OPCOM on !AS is deactivating !AS, csid !XL, system !UL!/Node is no longer with us, placing node in DEPARTED state." /FAO=6
	NODE_INIT	"%D%OPCOM on !AS is initializing the local node !AS, csid !XL, system !UL" /FAO=6
	NODE_RETRY	"%D%OPCOM on !AS is trying again to talk to !AS, csid !XL, system !UL" /FAO=6
	NODE_START	"%D%OPCOM on !AS recognizes node !AS, csid !XL, system !UL!/Attempting to establish communications, placing node in STARTING state." /FAO=6
	UNKNOWN		<unknown request: msgtyp !XW, rqstcode !XB!/"!AF"> /FAO=4
	CLUSCOMM	"%D%OPCOM on !AS is unable to communicate with !AS, csid !XL, system !UL" /FAO=6

	.SEVERITY	FATAL

	VALUERR		<error occurred while processing the command item "!AS"> /FAO=1
	NOTRQCB		<data structure is not an RQCB>

	.SEVERITY	INFORMATIONAL

	REPLY_GENERAL	<!/!ADReply received!AS!AF from user !AF at !AS   !AS!AD!/!AS!AD!/> /FAO=13
	REPLY_SHUTDOWN	<!/!ADSHUTDOWN message!AS!AF from user !AF at !AS   !AS!AD!/!AS!AD!/> /FAO=13
	REPLY_URGENT	<!/!AD*URGENT* message!AS!AF from user !AF at !AS   !AS!AD!/!AS!AD!/> /FAO=13
	REPLY_NOTALL	<!UL terminal has been notified!AS!AF.> /FAO=4
	REPLY_NOTALLn	<!UL terminals have been notified!AS!AF.> /FAO=4
	REPLY_NOTDEV	<Terminal !AS has been notified.> /FAO=1
	REPLY_NOTUSE	<User !AS has been notified!AS!AF.> /FAO=4
	REPLY_NOTUSEn	<User !AS has been notified!AS!AF (!UL terminals).> /FAO=5

	ON_NODE		< on >	! Preposition for "on nodename"  ("on ATHENS") messages
	HEADER		<%%%%%%%%%%%  OPCOM  !%D  %%%%%%%%%%%!/>
	RQST_PROMPT	<REQUEST - Enter message or cancel request with control/Z.
REQUEST - Message? >

	.SEVERITY	WARNING

	NOLCLBROAD	<no terminals were notified>
	NOREMBROAD	<no VAXcluster terminals were notified because OPCOM is not available>
	NOREMWAIT	</WAIT requested, therefore no VAXcluster terminals notified>

	.SEVERITY	INFORMATION
	!
	! Cluster mailbox messages
	!   FAO parameter list is:
	!
	!	timestamp - pointer to quadword time
	!	lsysnaml  - length of name of local system
	!	lsysnama  - address of name of local system
	!	lsysidw   - high order word of local system id
	!	lsysidl   - low order longword of local system id
	!	lcsid     - local system csid
	!	rsysnaml  - length of name of remote system
	!	rsysnama  - address of name of remote system
	!	rsysidw   - high order word of remote system id
	!	rsysidl   - low order longword of remote system id
	!	rcsid     - remote system csid
	!
	! Messages use the "!+" directive to skip over items which
	! are not meaningful or useful for a particular message.
	!
	CLU_NEWSYS	<%D%!%T Node !AD (sysid !+!UL!+) discovered node !AD (sysid !+!UL!+)> 			/FAO=11
	CLU_CNX		<%D%!%T Node !AD (csid !+!+!XL) established connection to node !AD> 			/FAO=11
	CLU_RECNX	<%D%!%T Node !AD (csid !+!+!XL) re-established connection to node !AD> 			/FAO=11
	CLU_LOSTCNX	<%D%!%T Node !AD (csid !+!+!XL) lost connection to node !AD> 				/FAO=11
	CLU_TIMCNX	<%D%!%T Node !AD (csid !+!+!XL) timed-out lost connection to node !AD> 			/FAO=11
	CLU_INIFORM	<%D%!%T Node !AD (csid !+!+!XL) proposed formation of a VAXcluster> 			/FAO=11 
	CLU_INIADD	<%D%!%T Node !AD (csid !+!+!XL) proposed addition of node !AD> 				/FAO=11
	CLU_INIRECNFIG	<%D%!%T Node !AD (csid !+!+!XL) proposed reconfiguration of the VAXcluster> 		/FAO=11 
	CLU_MEMREQ	<%D%!%T Node !AD (csid !+!+!XL) received VAXcluster membership request from node !AD>	/FAO=11
	CLU_ABORT	<%D%!%T Node !AD (csid !+!+!XL) aborted VAXcluster state transition> 			/FAO=11 
	CLU_ADD		<%D%!%T Node !+!+!+!+!+!AD (csid !+!+!XL) is now a VAXcluster member> 			/FAO=11
	CLU_DROPNODE	<%D%!%T Node !+!+!+!+!+!AD (csid !+!+!XL) has been removed from the VAXcluster> 	/FAO=11
	CLU_FORNCLUS	<%D%!%T Node !AD (csid !+!+!XL) detected node !AD, a member of another VAXcluster> 	/FAO=11
	CLU_INQUORUM	<%D%!%T Node !AD (csid !+!+!XL) regained quorum, proceeding> 				/FAO=11 
	CLU_LOSTDISK	<%D%!%T Node !AD (csid !+!+!XL) lost "connection" to quorum disk> 			/FAO=11 
	CLU_GAINDISK	<%D%!%T Node !AD (csid !+!+!XL) re-established "connection" to quorum disk> 		/FAO=11 
	CLU_DISKRDERR	<%D%!%T Node !AD (csid !+!+!XL) failed to read quorum disk> 				/FAO=11 
	CLU_DISKWRERR	<%D%!%T Node !AD (csid !+!+!XL) failed to write quorum disk> 				/FAO=11 
	CLU_DISKINVDAT	<%D%!%T Node !AD (csid !+!+!XL) read invalid data from quorum disk> 			/FAO=11 
	CLU_DISKTIMEOUT	<%D%!%T Node !AD (csid !+!+!XL) timed-out operation to quorum disk> 			/FAO=11 
	CLU_LOSTMSG	<%D%!%T Node !AD (csid !+!+!XL) lost one or more messages> 				/FAO=11 
	CLU_NOQUORUM	<%D%!%T Node !AD (csid !+!+!XL) lost quorum, blocking activity>				/FAO=11 
	CLU_FORNDISK	<%D%!%T Node !AD (csid !+!+!XL) detected another VAXcluster via the quorum disk> 	/FAO=11 
	CLU_COMPLETE	<%D%!%T Node !AD (csid !+!+!XL) completed VAXcluster state transition>		 	/FAO=11 
	CLU_QUORUM	<%D%!%T Node !AD (csid !+!+!XL) proposed modification of quorum or quorum disk membership> /FAO=11 

	.END
