!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! MODIFIED BY:
!
!
!+++
!
! Return status codes for DCX (Data Compression / Expansion Facility)
!
!******************************************************************
!*								  *
!*  Any changes here must be reflected in [dcx.com]dcxshrlnk.com  *
!*								  *
!******************************************************************
!---

	.FACILITY	DCX,246 /SYSTEM /MACRO=$DCXMSG

!
! Success codes		(Severity level 1)
!
	.SEVERITY	SUCCESS
	.BASE		0

	NORMAL		<success>


!
! Informational codes		(Severity level 3)
!
	.SEVERITY	INFORMATIONAL
	.BASE		128

	AGAIN		<another data analysis pass is needed>

!
! Warning codes
!

	.SEVERITY	WARNING
	.BASE		256

	TRUNC		<data truncated>

!
! Error codes		(Severity level 2)
!

	.SEVERITY	ERROR
	.BASE		512

	INVARG		<invalid argument>
	INVDATA		<invalid data presented for expansion or bounded compression>
	INVCTX		<invalid context block>
	INVITEM		<invalid item code or list>
	INVMAP		<invalid map>

	.END
