.TITLE	exch$message
.IDENT	'V04-000'
.FACILITY	EXCHANGE,248 /PREFIX=EXCH$_

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:	EXCHANGE - Foreign volume interchange facility
!
! ABSTRACT:	Error message definitions
!
! ENVIRONMENT:	VAX/VMS User mode
!
! AUTHOR:	CW Hobbs		CREATION DATE: 15-July-1982
!
! MODIFIED BY:
!
!	V03-002	CWH3002		CW Hobbs		18-Mar-1984
!		Add EXCH$_NOREMOTE, EXCH$_NOTSAMEDEV and EXCH$_RT11_DIRSIZE
!		messages
!
!--

.SEVERITY	FATAL

.SEVERITY	ERROR

BADLOGIC	<internal logic error detected, please report error !UL>/FAO_COUNT=1
BLOCKCHECK	<block check, please report error !UL and the following:!/        address = !XL,  size (found,expected) = !UL,!UL  type = !UL,!UL>/FAO_COUNT=6
BLOCKCHECK0	<block check, please report error !UL>/FAO_COUNT=1

.SEVERITY	WARNING

ACCESSFAIL	<access has failed for !AS>/FAO_COUNT=1
BADFILENAME	<name !AS not suitable for !AF volume>/FAO_COUNT=3
BADPAD		<bad format for PAD keyword on /RECORD_FORMAT qualifier>
BINCHKSUM	<a binary record failed checksum in !AF>/FAO_COUNT=2
BINRECFMT	<an illegal binary record found in !AF>/FAO_COUNT=2
CANCELED	<command was canceled by keyboard action>
CLOSEERR	<an error occurred closing !AS>/FAO_COUNT=1
CLOSEFOREIGN	<an error occurred closing the volume !AS>/FAO_COUNT=1
CREATEVIRT	<error creating the virtual volume !AS>/FAO_COUNT=1
DEVNOTSUIT	<the device !AS is not suitable for operations>/FAO_COUNT=1
DIRE_ERROR	<above error occurred writing directory, volume might be corrupted>
DOS11_BADLABEL	<volume on !AF has label with invalid format>/FAO_COUNT=2
DOS11_BLOCKSIZE	<volume on !AF has block larger than 512 bytes>/FAO_COUNT=2
DOS11_IOERROR	<error during I/O on volume !AF>/FAO_COUNT=2
FILENOTFOUND	<unable to locate file !AS>/FAO_COUNT=1
ILLMTCOPY	<cannot specify same magtape for both input and output>
INVRECFMT	<record format specified inconsistent with volume format>
INVVOLFMT	<volume format specified is not consistent with file spec>
MANY_TO_ONE	<input specifies multiple files, output a single file>
MOUNTERROR	<error occurred during VMS mount on !AS>/FAO_COUNT=1
NOCOPBAD	<cannot create .BAD file with wildcard names>
NOCOPBADDEL	<cannot delete existing .BAD file>
NOCOPDUP	<already copied file with same output name in this command>
NOCOPLOCK	<cannot create files, volume !AF is write-locked>/FAO_COUNT=2
NOCOPNODEL	<file already exists and /NODELETE requested>
NOCOPPROT	<file with same name is protected against modification>
NOCOPSAMDEV	<illegal wildcard copy to same device>
NOCOPSYSDEL	<cannot delete existing .SYS file without /SYSTEM>
NOCOPYBOOT	<unable to copy boot information>
NODELLOCK	<file !AF not deleted, volume is write-locked>/FAO_COUNT=2
NODEVICE	<missing or incorrect device name in !AS>/FAO_COUNT=1
NOREMOTE	<remote node name not permitted in !AS>/FAO_COUNT=1
NORENDEV	<cannot RENAME to a different device>
NORENEXISTS	<file !AF not renamed, !AF already exists>/FAO_COUNT=4
NORENLOCK	<file !AF not renamed, volume is write-locked>/FAO_COUNT=2
!\ NOTIMPLEMENT	<feature not yet implemented, sorry>
NOTMOUNTED	<volume !AS has not been mounted on EXCHANGE>/FAO_COUNT=1
NOTSAMEDEV	<input and output must be same device for boot copy>
OPENFOREIGN	<unable to open !AS as a foreign volume>/FAO_COUNT=1
OPENVIRTUAL	<unable to open !AS as a virtual volume>/FAO_COUNT=1
OPNOTPERDOS	<operation not permitted on DOS-11 volume !AS>/FAO_COUNT=1
OPNOTPERF11	<operation not permitted on Files-11 volume !AS>/FAO_COUNT=1
!\ OPNOTPERRT11	<operation not permitted on RT-11 volume !AS>/FAO_COUNT=1
!\ OPNOTPERRTMT	<operation not permitted on RT-11 tape volume !AS>/FAO_COUNT=1
PARSEERR	<unable to parse input name !AS>/FAO_COUNT=1
READCHECK	<read error detected during check on volume !AS>/FAO_COUNT=1
RECOVER		<to save volume, follow procedure outlined by the
    HELP RECOVER command BEFORE dismounting volume or exiting EXCHANGE!>
RECTOOBIG	<record too large in !AF>/FAO_COUNT=2
RT11_BADDIRECT	<volume !AF has invalid RT-11 directory>/FAO_COUNT=2
RT11_DIRSIZE	<volume !AF has directory showing !UL blocks on a !UL block device>/FAO_COUNT=4
RT11_ERRLOCK	<volume will be write-locked to prevent corruption>
RT11_NOEND	<segment end marker is missing from RT-11 directory>
RT11_OVERFLOW	<directory is full, unable to add file>
RT11_STBLOCK	<file start block - segment header inconsistent>
RT11_UNKENT	<entry with unknown format in directory>
RTOUTEOF	<end-of-file on output !AF, insufficient space on volume>/FAO_COUNT=2
RTPROTECT	<file is protected against modification>
STMRECFMT	<illegal stream record format in !AF>/FAO_COUNT=2
STNOTAVAIL	<requested starting block number is not available>
STRTNOMULTI	<cannot request /START_BLOCK with multiple input files>
TOOMANYCOL	<too many columns, reduced number to fit listing width>
VOLMOUNT	<the volume !AS is already mounted>/FAO_COUNT=1
VOLUME_FULL	<volume is full (insufficient space for the request)>
WAITERR		<error waiting for RMS operation to complete>
WRITECHECK	<write error detected during check on volume !AS>/FAO_COUNT=1

.SEVERITY	INFORMATION

DEVONLY		<using device name only, ignoring parts of !AS>/FAO_COUNT=1
DOS11_POSITION	<rewinding tape to recover correct positioning>
FIL11_NOREC	<ignoring /RECORD_FORMAT for Files-11 output>
IGNORE_DIRE	<directory name ignored, not used for this volume type>
IGNORE_VERS	<file version ignored, not used for this volume type>
NOALLOC		<ignoring /ALLOCATION, not valid for output volume>
NOCARRIAGE	<ignoring /CARRIAGE_CONTROL, not valid for output volume>
NOSYSACT	<no action on .SYS file(s)>
NOTCOPIED	<file !AF not copied to !AF>/FAO_COUNT=4
NOTCOP_RETRY	<error copying !AF, will retry>/FAO_COUNT=2
NOTDELETED	<file !AF not deleted>/FAO_COUNT=2
NOTVALLEN	<fixed record length of !UL is too large>/FAO_COUNT=1
NOVOLUMES	<no volumes are currently mounted>
PARTCOPIED	<file !AF partially copied to !AF, !UL !AS!%S>/FAO_COUNT=6
READCHECKREC	<read check error recovered on volume !AF>/FAO_COUNT=2
READERRREC	<read error recovered on volume !AF>/FAO_COUNT=2
RT11_BADFILE	<bad block file created to cover bad block !UL>/FAO_COUNT=1
RT11_BIGBADFILE	<directory segment full, file has some good blocks>
RT11_EXTRA	<extra words set to maximum of 119>
RT11_TOOMANYBLK	<too many blocks, using maximum allocation of !UL>/FAO_COUNT=1
RT11_TOOMANYSEG	<too many segments, reducing to !UL>/FAO_COUNT=1
TRACE		<status code is !XL>/FAO_COUNT=1
VIRTNOCHANGE	<allocation of virtual device cannot be changed>
VMSMOUNT	<a "$ MOUNT /FOREIGN !AS" command was done by Exchange>/FAO_COUNT=1
WRITECACHE	<writing directory cache for volume !AF>/FAO_COUNT=2
WRITECHECKREC	<write check error recovered on volume !AF>/FAO_COUNT=2
WRITEERRREC	<write error recovered on volume !AF>/FAO_COUNT=2
WRITELOCK	<volume !AF is write-locked>/FAO_COUNT=2

.SEVERITY	SUCCESS

COPIED		<!AF copied to !AF, !UL !AS!%S>/FAO_COUNT=6
COPYBOOT	<bootstrap data from !AF copied to !AF>/FAO_COUNT=4
COPNEWNAME	<!AF copied to !AF (new name), !UL !AS!%S>/FAO_COUNT=6
DELETED		<file !AF deleted>/FAO_COUNT=2
DELETEPREV	<previous copy of !AF deleted>/FAO_COUNT=2
DISMOUNTED	<the !AF volume !AF has been dismounted>/FAO_COUNT=4
INITIALIZED	<the !AF volume !AF has been initialized>/FAO_COUNT=4
MOUNTED		<the !AF volume !AF has been mounted>/FAO_COUNT=4
MOUNTVIR	<the RT-11 virtual volume !AF has been mounted!/          using the file !AF>/FAO_COUNT=4
RENAMED		<file !AF renamed to !AF>/FAO_COUNT=4
TYPED		<file !AF typed, !UL record!%S>/FAO_COUNT=3

.END
