	.TITLE	PAS$MSGDEF VAX-11 Pascal Run-Time Messages
	.IDENT	'1-004'		! File PASMSG.MSG, Edit: SBL1004

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:	VAX-11 Pascal Run-Time Library
!
! ABSTRACT:
!
!	This module contains the message definitions for VAX-11 Pascal V2
!	Run-Time messages.
!
! AUTHOR: Steven B. Lionel, CREATION DATE: 1-April-1981
!
! MODIFIED BY:
!
! 1-001	- Original.  SBL 1-April-1981
! 1-002 - Remove PAS$_INVFIESPE since it is no longer used.  SBL 2-July-1982
! 1-003 - Reserve message numbers 3000-3999 for SeaPascal.  SBL 25-Mar-1983
! 1-004 - Change text of BUGCHECK to refer to User's Guide.  SBL 17-Aug-1983
!--

	.FACILITY	PAS,33 /SYSTEM

!+
!  NOTE: The VAX-11 Pascal V1 Run-Time Library used message numbers between
!  32 and 128.  To avoid conflicts, start VAX-11 Pascal V2 numbers at 200.
!-

!+
!  Messages 201 to 999 are I/O errors which can be continued by means of
!  Error:=Continue in the Pascal statement.
!
!  The STATUS return value is <message_number - 200> 
!
!  ********************* NOTE *************************
!  *   For messages 201-999, which all have the PFV   *
!  *   address placed as the first FAO argument, the  *
!  *   FAO control string MUST include the "!+" edit  *
!  *   directive as the first directive in the string.*
!  *   Failure to do this will result in the PFV      *
!  *   being used incorrectly in the result text.     *
!  ****************************************************
!
!-
	.SEVERITY	FATAL

!+
! Messages from OPEN and CLOSE.
!-
	.BASE		200
	BASE		<>	! Never signalled

	FILALROPE	<file is already open!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILALROPE=(PAS$_FILALROPE-PAS$_BASE)@-3

	ERRDUROPE	<error during OPEN!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDUROPE=(PAS$_ERRDUROPE-PAS$_BASE)@-3

	FILNOTFOU	<file not found!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTFOU=(PAS$_FILNOTFOU-PAS$_BASE)@-3

	INVFILSYN	<invalid filename syntax!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_INVFILSYN=(PAS$_INVFILSYN-PAS$_BASE)@-3

	ACCMETINC	<ACCESS_METHOD specified is incompatible with this file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ACCMETINC=(PAS$_ACCMETINC-PAS$_BASE)@-3

	RECLENINC	<RECORD_LENGTH specified is inconsistent with this file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_RECLENINC=(PAS$_RECLENINC-PAS$_BASE)@-3

	RECTYPINC	<RECORD_TYPE specified is inconsistent with this file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_RECTYPINC=(PAS$_RECTYPINC-PAS$_BASE)@-3

	ORGSPEINC	<ORGANIZATION specified is inconsistent with this file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ORGSPEINC=(PAS$_ORGSPEINC-PAS$_BASE)@-3

	INVKEYDEF	<invalid key definition!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_INVKEYDEF=(PAS$_INVKEYDEF-PAS$_BASE)@-3

	KEYDEFINC	<KEY(!+!UL) definition is inconsistent with this file!/  File "!AC"  Filename "!AS">/FAO_COUNT=4
	.LITERAL	PAS$K_KEYDEFINC=(PAS$_KEYDEFINC-PAS$_BASE)@-3

	KEYNOTDEF	<KEY(!+!UL) is not defined in this file!/  File "!AC"  Filename "!AS">/FAO_COUNT=4
	.LITERAL	PAS$K_KEYNOTDEF=(PAS$_KEYNOTDEF-PAS$_BASE)@-3

	INVRECLEN	<invalid record length of !+!UL!/  File "!AC"  Filename "!AS">/FAO_COUNT=4
	.LITERAL	PAS$K_INVRECLEN=(PAS$_INVRECLEN-PAS$_BASE)@-3

	TEXREQSEQ	<textfiles require sequential organization and access!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_TEXREQSEQ=(PAS$_TEXREQSEQ-PAS$_BASE)@-3

	FILNAMREQ	<FILE_NAME required for this HISTORY or DISPOSITION!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNAMREQ=(PAS$_FILNAMREQ-PAS$_BASE)@-3

	FILALRCLO	<file is already closed!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILALRCLO=(PAS$_FILALRCLO-PAS$_BASE)@-3

	ERRDURCLO	<error during CLOSE!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURCLO=(PAS$_ERRDURCLO-PAS$_BASE)@-3

!+
! Textfile READ errors.
!-
	.BASE		230

	AMBVALENU	<!+"!AS" is an ambiguous value for enumerated type "!AC"!/  Record !UL  File "!AC"  Filename "!AS">/FAO_COUNT=6
	.LITERAL	PAS$K_AMBVALENU=(PAS$_AMBVALENU-PAS$_BASE)@-3

	INVSYNENU	<!+"!AD" is invalid syntax for an enumerated value!/  Record !UL  File "!AC"  Filename "!AS">/FAO_COUNT=5
	.LITERAL	PAS$K_INVSYNENU=(PAS$_INVSYNENU-PAS$_BASE)@-3

	INVSYNINT	<!+"!AS" is invalid syntax for an integer value!/  Record !UL  File "!AC"  Filename "!AS">/FAO_COUNT=4
	.LITERAL	PAS$K_INVSYNINT=(PAS$_INVSYNINT-PAS$_BASE)@-3

	INVSYNREA	<!+"!AS" is invalid syntax for a real value!/  Record !UL  File "!AC"  Filename "!AS">/FAO_COUNT=4
	.LITERAL	PAS$K_INVSYNREA=(PAS$_INVSYNREA-PAS$_BASE)@-3

	INVSYNUNS	<!+"!AD" is invalid syntax for an unsigned value!/  Record !UL  File "!AC"  Filename "!AS">/FAO_COUNT=5
	.LITERAL	PAS$K_INVSYNUNS=(PAS$_INVSYNUNS-PAS$_BASE)@-3

	NOTVALTYP	<!+"!AS" is not a value of type "!AC"!/  Record !UL  File "!AC"  Filename "!AS">/FAO_COUNT=6
	.LITERAL	PAS$K_NOTVALTYP=(PAS$_NOTVALTYP-PAS$_BASE)@-3

	ERRDURPRO	<error during prompting!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURPRO=(PAS$_ERRDURPRO-PAS$_BASE)@-3


!+
! Textfile WRITE errors.
!-
	.BASE		250

	ERRDURWRI	<error during WRITELN!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURWRI=(PAS$_ERRDURWRI-PAS$_BASE)@-3

	! Message 251 is no longer used - available for reuse

	.BASE		252

	LINTOOLON	<line is too long, exceeded record length by !+!UL character!%S!/  File "!AC"  Filename "!AS">/FAO_COUNT=4
	.LITERAL	PAS$K_LINTOOLON=(PAS$_LINTOOLON-PAS$_BASE)@-3

	NEGWIDDIG	<negative Width or Digits specification is not allowed!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_NEGWIDDIG=(PAS$_NEGWIDDIG-PAS$_BASE)@-3

	WRIINVENU	<WRITE of an invalid enumerated value!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_WRIINVENU=(PAS$_WRIINVENU-PAS$_BASE)@-3


!+
! Direct and Keyed access errors.
!-
	.BASE		270

	KEYVALINC	<key value is incompatible with this file's key !+!UL!/  File "!AC"  Filename "!AS">/FAO_COUNT=4
	.LITERAL	PAS$K_KEYVALINC=(PAS$_KEYVALINC-PAS$_BASE)@-3

	KEYDUPNOT	<key field duplication is not allowed!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_KEYDUPNOT=(PAS$_KEYDUPNOT-PAS$_BASE)@-3

	KEYCHANOT	<key field change is not allowed!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_KEYCHANOT=(PAS$_KEYCHANOT-PAS$_BASE)@-3

	CURCOMUND	<current component is undefined for DELETE or UPDATE!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_CURCOMUND=(PAS$_CURCOMUND-PAS$_BASE)@-3

	FAIGETLOC	<failed to GET locked component!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FAIGETLOC=(PAS$_FAIGETLOC-PAS$_BASE)@-3


!+
! Miscellaneous errors.
!-
	.BASE		300

	DELNOTALL	<DELETE is not allowed for a sequential organization file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_DELNOTALL=(PAS$_DELNOTALL-PAS$_BASE)@-3

	ERRDURDEL	<error during DELETE!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURDEL=(PAS$_ERRDURDEL-PAS$_BASE)@-3

	ERRDURFIN	<error during FIND or FINDK!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURFIN=(PAS$_ERRDURFIN-PAS$_BASE)@-3

	ERRDURGET	<error during GET!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURGET=(PAS$_ERRDURGET-PAS$_BASE)@-3

	ERRDURPUT	<error during PUT!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURPUT=(PAS$_ERRDURPUT-PAS$_BASE)@-3

	ERRDURRES	<error during RESET or RESETK!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURRES=(PAS$_ERRDURRES-PAS$_BASE)@-3

	ERRDURREW	<error during REWRITE!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURREW=(PAS$_ERRDURREW-PAS$_BASE)@-3

	ERRDURTRU	<error during TRUNCATE!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURTRU=(PAS$_ERRDURTRU-PAS$_BASE)@-3

	ERRDURUNL	<error during UNLOCK!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURUNL=(PAS$_ERRDURUNL-PAS$_BASE)@-3

	ERRDURUPD	<error during UPDATE!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_ERRDURUPD=(PAS$_ERRDURUPD-PAS$_BASE)@-3

	FILNOTDIR	<file is not opened for direct access!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTDIR=(PAS$_FILNOTDIR-PAS$_BASE)@-3

	FILNOTGEN	<file is not in Generation mode!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTGEN=(PAS$_FILNOTGEN-PAS$_BASE)@-3

	FILNOTINS 	<file is not in Inspection mode!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTINS =(PAS$_FILNOTINS -PAS$_BASE)@-3

	FILNOTKEY	<file is not opened for keyed access!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTKEY=(PAS$_FILNOTKEY-PAS$_BASE)@-3

	FILNOTOPE	<file is not open!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTOPE=(PAS$_FILNOTOPE-PAS$_BASE)@-3

	FILNOTSEQ	<file is not sequential organization!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTSEQ=(PAS$_FILNOTSEQ-PAS$_BASE)@-3

	FILNOTTEX	<file is not a textfile!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_FILNOTTEX=(PAS$_FILNOTTEX-PAS$_BASE)@-3

	GENNOTALL	<Generation mode is not allowed for a READONLY file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_GENNOTALL=(PAS$_GENNOTALL-PAS$_BASE)@-3

	GETAFTEOF	<GET attempted after end-of-file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_GETAFTEOF=(PAS$_GETAFTEOF-PAS$_BASE)@-3

	INSNOTALL	<Inspection mode is not allowed for a WRITEONLY file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_INSNOTALL=(PAS$_INSNOTALL-PAS$_BASE)@-3

	INSVIRMEM	<insufficient virtual memory!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_INSVIRMEM=(PAS$_INSVIRMEM-PAS$_BASE)@-3

	INVARGPAS	<invalid argument to Pascal Run-Time Library!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_INVARGPAS=(PAS$_INVARGPAS-PAS$_BASE)@-3

	LINVALEXC	<LINELIMIT value exceeded!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_LINVALEXC=(PAS$_LINVALEXC-PAS$_BASE)@-3

	REWNOTALL	<REWRITE is not allowed for a shared file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_REWNOTALL=(PAS$_REWNOTALL-PAS$_BASE)@-3

	RESNOTALL	<RESET is not allowed on an unopened internal file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_RESNOTALL=(PAS$_RESNOTALL-PAS$_BASE)@-3

	TRUNOTALL	<TRUNCATE is not allowed for a shared file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_TRUNOTALL=(PAS$_TRUNOTALL-PAS$_BASE)@-3

	UPDNOTALL	<UPDATE is not allowed for a sequential organization file!+!/  File "!AC"  Filename "!AS">/FAO_COUNT=3
	.LITERAL	PAS$K_UPDNOTALL=(PAS$_UPDNOTALL-PAS$_BASE)@-3


	
	
!+
!  Message numbers 1000-1999 are for messages without a valid PFV.
!-

	.BASE		1000
	INVFILVAR	<invalid file variable at location !XL>/FAO_COUNT=1
	FILALRACT	<file "!AC" is already active>/FAO_COUNT=1
	ERRDURNEW	<error during NEW>
	ERRDURDIS	<error during DISPOSE>
	ERRDURMAR	<error during MARK>
	ERRDURREL	<error during RELEASE>
	GOTO		<non-local GOTO requested!+!+>/FAO=2
	GOTOFAILED	<non-local GOTO failed>
	HALT		<HALT procedure called>
	BUGCHECK	<internal consistency failure !UL in Pascal Run-Time Library!/       Please see User's Guide>/FAO=1
	NEGDIGARG	<negative Digits argument to BIN, HEX or OCT is not allowed>
	CONTINUE	<I/O error dismissed by user handler!+>/FAO=1

!+
! Messages 2000 and up are for errors detected in the compiled code at
! run-time.  The compiled code has in the instruction stream a byte value
! (0-63) which denotes the specific message to signal (2000-2063).  The
! particular exception conditions recognized by PAS$HANDLER as being
! run-time error checking exceptions, and the locations of the code byte,
! are as follows:
!
!	Exception	Instruction	Code byte location
!	---------	-----------	------------------
!	SS$_OPCDEC	HALT		.BYTE after HALT
!	SS$_SUBRNG	INDEX		TSTB #x (current instruction)
!	SS$_INTOVF	any		TSTB #x (current instruction)
!-

	.BASE		2000

	ARRINDVAL	<array index value is out of range>
	ARRNOTCOM	<conformant array is not compatible>
	ARRNOTSTR	<conformant array is not a string>
	CASSELVAL	<CASE selector value is out of range>
	CONCATLEN	<string concatenation has more than 65535 characters>
	PADLENERR	<PAD length error>
	PTRREFNIL	<pointer reference to NIL>
	SETASGVAL	<set assignment value has element out of range>
	SETCONVAL	<set constructor value is out of range>
	STRASGLEN	<string assignment length error>
	STRCOMLEN	<strings comparison length error>
	SUBASGVAL	<subrange assignment value is out of range>
	SUBSTRSEL	<SUBSTR selection error>
	VARINDVAL	<varying index value is greater than current length>
	ORDVALOUT	<ordinal value is out of range>

!+
! If the byte code in the instruction stream is PAS$K_IGNORE, PAS$HANDLER
! simply does a CONTINUE.
!-

	.LITERAL	PAS$K_IGNORE=63

!+
! *****************************************************
! Message numbers 3000-3999 are reserved for SeaPascal.
! *****************************************************
!-

!+
! Define literals which can be used to test for specific groups of messages.
!-

	.LITERAL	PAS$$K_MSGV2LO=200	! Lowest V2 message number
	.LITERAL	PAS$$K_MSGCONTLO=200	! Lowest continuable error
	.LITERAL	PAS$$K_MSGCONTHI=999	! Highest continuable error
	.LITERAL	PAS$$K_MSGPFVHI=999	! Highest message with a valid PFV
	.LITERAL	PAS$$K_MSGCHKBAS=2000	! Base of run-time checking messages

!+
! Define STATUS codes for EOF and SUCCESS
!-

	.LITERAL	PAS$K_EOF = -1
	.LITERAL	PAS$K_SUCCESS = 0

	.END

