! MAILMSG.MSG - system definition file for MAIL messages
!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	This file contains the MDL source for MAIL messages
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  The VMS Group	 CREATION DATE:  8-Jun-1978
!
! MODIFICATION HISTORY:
!
!	V03-015	ROP0004		Robert Posniak		6-JUN-1984
!		New messge for oversized record.  New message for
!		reentering line.
!
!	V03-014	BLS0272		Benn Schreiber		18-FEB-1984 13:36:12 
!		New message for incorrect protocol version.
!
!	V03-013	BLS0263		Benn Schreiber		 5-FEB-1984
!		New message for Captive account trying to SPAWN.
!
!	V03-012	BLS0255		Benn Schreiber		28-Dec-1983
!		New messages for SHOW KEY, and for time in notify message
!
!	V03-011	BLS0250		Benn Schreiber		 8-Dec-1983
!		New message for editor not callable.  New message for
!		isam file found when sequential expected.
!
!	V03-010	BLS0246		Benn Schreiber		28-Nov-1983
!		New message asking if want to create new folder.
!
!	V03-009	BLS0229		Benn Schreiber		16-Jul-1983
!		New message "you have new mail".
!
!	V03-008	BLS0227		Benn Schreiber		 1-Jul-1983
!		New messages for SENDERR and NOSUCHUSR that include
!		the node name.
!
!	V03-007	BLS0225		Benn Schreiber		17-Jun-1983
!		New message for better personal name checking
!
!	V03-006	BLS0222		Benn Schreiber		15-May-1983
!		New message for reclaiming space
!
!	V03-005	BLS0220		Benn Schreiber		30-Apr-1983
!		New messages for new features
!
!	V03-004	BLS0217		Benn Schreiber		12-Apr-1983
!		Change text of DELSPACE.  Add new message for non-existant
!		folder selected.  Add message for external message text.
!
!	V03-003	BLS0211		Benn Schreiber		13-Mar-1983
!		New messages for ISAM files, and text that used to
!		be embedded in the program.
!
!	V03-002	BLS0202		Benn Schreiber		 5-Jan-1983
!		New messages for illegal string length and illegal
!		character in string
!
!	V03-001	BLS0177		Benn Schreiber		24-Jun-1982
!		New message for user who has DISMAIL set.  New message
!		if loop detected in forwarding via logical names or
!		SET FORWARD.
!

!
! DEFINE MAIL RELATED ERROR/STATUS VALUES
!
 
 
 
!
! DEFINE ERROR MESSAGES
!
	.FACILITY	MAIL,126 /SYSTEM /MACRO=$MAILMSGDEF

	.SEVERITY	ERROR

	UAFGETERR	<error reading user authorization file>
	UAFOPNERR	<error opening user authorization file>
	NOSUCHUSR	<no such user !AS> /FAO=1
	NOTREADIN	<you aren't reading a message>
	LOGLINK		<error creating network link to node !AS> /FAO=1
	CREPRIJOB	<error creating print job on queue !AS> /FAO=1
	SENDERR		<error sending to user !AS> /FAO=1
	NOMOREMSG	<no more messages>
	NOMSGS		<no messages>
	USERSPEC	<invalid user specification '!AS'> /FAO=1
	SENDABORT	<no message sent>
	EDITPROC	<error creating or executing editor subprocess>
	INVCMD		<unrecognized command '!AS'> /FAO=1
	NOTFOUND	<no messages containing '!AS' found> /FAO=1
	NETIOERR	<network I/O error>
	USERDSABL	<user !AS cannot receive new mail> /FAO=1
	FORWLOOP	<infinite forwarding detected sending to user !AS> /FAO=1
	NAMTOOBIG	<name '!AS' is too long> /FAO=1
	ILLCHAR		<Illegal character (%X'!XB') in string '!AF'> /FAO=3
	DATIMUSED	<message date/time (!20%D) in use!/!_in file !AS>/FAO=2
	NOTISAM		<operation cannot be performed on non-ISAM message file>
	DELMSG		<message is deleted>
	DELWASTE	<you cannot delete messages from the wastebasket folder!/!_Use the PURGE command to empty the wastebasket folder>
	NOFOLDER	<no folder is currently selected.>
	NOTEXIST	<folder !AS does not exist>/FAO=1
	NOTSUBDIR	<parameter !AS does not specify a subdirectory>/FAO=1
	ILLSUBDIR	<subdirectory specification !AS is illegal>/FAO=1
	ILLFOLNAM	<!AS is an illegal folder name>/FAO=1
	NOMSGPRI	<no messages printed>
	ALTPRIJOB	<error altering parameters of job !UL queue !AS>/FAO=2
	ILLPERNAM	<"!AS" is an illegal personal name>/FAO=1
	NOSUCHUSRAT	<no such user !AS at node !AS> /FAO=2 /ID=NOSUCHUSR
	SENDERRAT	<error sending to user !AS at !AS> /FAO=2 /ID=SENDERR
	CONABORT	<connection to node !AS aborted by CTRL/C>/FAO=1
	NOTCALEDT	<this command cannot be executed.!/!_MAIL$EDIT does not specify a callable editor.>
	FILECONFUSED <file !AS!/!_is an ISAM file; expected a sequential file.!/!_A higher version exists that is sequential.>/FAO=1
	CAPTIVE		<this command cannot be executed.!/!_Your account is CAPTIVE.>
	IVPROTVAL	<invalid value of universal symbol !AS (!UL) in !AS>/FAO=3
	RECTOBIG	<!UL byte record too large for MAIL buffer>/FAO=1

	.BASE		2000

	.SEVERITY	INFORMATION

	SELECTED	<!UL message!%S selected> /FAO=1
	DELMSGS		<!UL message!%S deleted> /FAO=1
	CVTFILE		<converting message file !AS!/!_to ISAM message file !AS> /FAO=2
	RECLSTAT	<Reclaim statistics:!/!_Data buckets scanned:    !UL!/!_Data buckets reclaimed:  !UL!/!_Index buckets reclaimed: !UL!/!_Total buckets reclaimed: !UL>/FAO=4
	DELSPACE	<mail file !AS!/!_contains !UL deleted message byte!%S.>/FAO=2
	NEWFOLDER	<folder !AS created>/FAO=1
	RECLPLSWAIT	<reclaiming deleted file space.  Please wait...>
	REENTER		<please reenter last line as it was ignored>

	.BASE	3000

	.SEVERITY WARNING

	MOREMSG		<!/Press RETURN for more...>/FAO=0
	DIRHD0		<    # From                 Date         Subject>/FAO=0
	DIRHD10		<Listing of folders in !AS>/FAO=1
	DIRHD20		<     Press CTRL/C to cancel listing>/FAO=0
	DIRDEL10	<!5UL (Deleted)>/FAO=1
	ISUB10		<From:	>/FAO=0
	ISUB20		<To:	>/FAO=0
	ISUB30		<Subj:	>/FAO=0
	PRESRET		<!/Press RETURN to return to reading your mail>/FAO=0
	YOUHAVENEW	<You have !UL new message!%S.>/FAO=1
	MAIL10		<To:	!AS>/FAO=1
	MAIL20		<Subj:	!AS>/FAO=1
	WANTOSEND	<Do you want to send anyway (Y/N, default is N)? >/FAO=0
	NOTIFY10	<!ACNew mail on node !AS from !AS>/FAO=3
	NOTIFY20	<!ACNew mail from !AS>/FAO=2
	JOBENTERED	<  Job !UL entered on queue !AS>/FAO=2
	SHOW10		<!AS has mail forwarded to !AC>/FAO=2
	SHOW20		<You have not set a forwarding address.>/FAO=0
	SHOW30		<Your mail is being forwarded to !AC.>/FAO=1
	SHOW40		<!AS has not set a forwarding address>/FAO=1
	SHOW50		"!31<Username!> Forwarding address"/FAO=0
	SHOW60		<You have not set a personal name.>/FAO=0
	SHOW70		<Your personal name is "!AD".>/FAO=1
	SHOW80		<!AS has not set a personal name>/FAO=1
	SHOW90		<!AS has set a personal name of "!AD">/FAO=2
	SHOW100		"!31<Username!> Full name"/FAO=0
	SHOW110		<The wastebasket folder name is !AS.>/FAO=1
	EDIT10		<Enter your message below. Press CTRL/Z when complete, or CTRL/C to quit:>/FAO=0
	INFO10		< New message>
	INFO20		< Replied>
	INFO30		< !UL record!%S>/FAO=1
	SEND		<SEND>
	REPLY		<REPLY>
	SHOW120		<Automatic copy to yourself on !AS.>
	SHOW130		<Automatic copies to yourself are disabled.>
	INFO50		< External message id = '!XL!XL'>
	SHOW140		<Automatic deleted message purge is >
	SHOW150		<enabled.>
	SHOW160		<disabled.>
	ISUB50		<CC:	>
	MAIL30		<CC:	!AS>/FAO=1
	RETCONT		"Press RETURN to continue> "/FAO=0
	NEWSEQ/ID=YOUHAVENEW <You have new mail.>
	MAILDIR		<Your mail file directory is !AS.>/FAO=1
	MAILFILE	<Your current mail file is !AS.>/FAO=1
	MAILFOLDER	<Your current mail folder is !AS.>/FAO=1
	MAIL40		<Subj:	!AF>/FAO=1
	CRENEWFOLD	<Folder !AS does not exist.!/Do you want to create it (Y/N, default is N)? >/FAO=1
	NONEWMAIL	<no new messages>
	SHOWKEY10	<  !AS = "!AS">/FAO=2
	SHOWKEY20	<  !AS = "!AS" (!AS)>/FAO=3
	SHOWKEY30	<!AS keypad definitions:>
	SHOWKEY40	<echo>
	SHOWKEY50	<terminate>
	SHOWKEY60	<state=!AS>
	SHOWKEY70	<lock>
	NOTIFY30	<!ACNew mail on node !AS from !AS (!8%T)>/FAO=4
	NOTIFY40	<!ACNew mail from !AS (!8%T)>/FAO=3
	NOPARENT	<there is no parent to which to attach>
	FILEMPTY	<file !AS has no folders>
	NONEFOUND	<no folders found in file !AS!/!_with a folder name greater than !AS>

	.END

