!	INPSMBMSG.MSG - Input Symbiont Messages
!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
!
! FACILITY:
!	Input symbiont.
!
! ABSTRACT:
!	This file contains the messages for the input symbiont.
!
! ENVIRONMENT:
!	VAX/VMS user mode.
!
!--
!
! AUTHOR: M. Jack, CREATION DATE: 30-Apr-1982
!
! MODIFIED BY:
!
!	V03-001	MLJ0113		Martin L. Jack,	26-May-1983  10:21
!		Complete implementation.
!
!**

.title INPSMBMSG
.facility INPSMB,261/system
.severity error
ENTFIL		<error entering file on queue>
INVCONT		<invalid line continuation>
INVLOGFIL	<invalid log file specification>
INVPASS		<invalid password '!AS'>/FAO=1
INVUSER		<invalid username '!AS'>/FAO=1
JOBCARD		<job beginning '!AS'>/FAO=1
MISSPASS	<missing PASSWORD command>
OPENUAF		<error opening user authorization file>
USERVAL		<user validation error>
.end
