	.TITLE	badmsg -- Diagnostic messages for Analyze/Media (aka BAD)
	.IDENT	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!++
!
! Facility:
!
!	Analyze/Media
!
! Abstract:
!
!	This module defines the utility specific diagnostic messages.
!
! Author:
!
!	Michael T. Rhodes			Creation Date:	August, 1982
!
! Modified By:
!
!	V03-001	MTR0005		Michael T. Rhodes		28-Apr-1983
!		Modify LSTTOTBK message text.
!
!--

	.FACILITY BAD, 250	/PREFIX=BAD$_

	.SEVERITY WARNING

	blk0bad		<block 0 is bad, do not use !AS as a system device>/FAO=1
	rebldwarn	<insufficient number of new detected bad sector files were written to !AS>/FAO=1

	.SEVERITY INFORMATIONAL

	dupblknum	<duplicate block number !UL, already exists in !AS>/FAO=2
	heading1	"!42<Analyze Media!>   !%D   Page !UL"/FAO=1
	heading2	<!AS (!AS), Serial Number: !UL>/FAO=3
	lstmdbsf	<!3UB!_!3UB!_!5UW>/FAO=3
	lstmdbs1	<Manufacturer Detected Bad Sectors!_!_Software Detected Bad Sectors>
	lstmdbs2	<Sector!_Track!_Cylinder!_!_!_Sector!_Track!_Cylinder>
	lstmdbs3	<!3UB!_!3UB!_!5UW!_!_!_!_!3UB!_!3UB!_!5UW>/FAO=6
	lstmdbs4	<Count: !UW!_!_!_!_!_Count: !UW>/FAO=2
	lstsdbsf	<!_!_!_!_!_!_!3UB!_!3UB!_!5UW>/FAO=3
	lstsdbs1	<Software Detected Bad Blocks>
	lstsdbs2	<Logical Block Number!_Count>
	lstsdbs3	<!8UL!_!_!3UB>/FAO=2
	lststring	<!AS>/FAO=1
	lsttotbk	<Device !AS contains a total of !UL blocks; !UW defective block!%S detected>/FAO=3
	nobadinfo	<no bad block information available for !AS>/FAO=1
	srclin		<the source input entry was !AS>/FAO=1

	.SEVERITY ERROR

	bbfwrt		<failed to write the bad block file on !AS>/FAO=1
	ivblknum	<!AS is an invalid block number, !AS value !UL is out of range>/FAO=1
	ivblkent	<invalid or missing bad block specifier in string "!AS">/FAO=1

	.SEVERITY FATAL

	aligndisk	<!AS contains an alignment cartridge>/FAO=1
	assign		<error assigning channel to !AS>/FAO=1
	bbfovf		<bad block file overflow on !AS>/FAO=1
	devnotblk	<!AS is not a block structured device>/FAO=1
	devnotfor	<!AS is not mounted foreign>/FAO=1
	devrct		<unable to analyze !AS, due to revector caching>/FAO=1
	fao		<error formatting report information>
	getdvi		<error obtaining device information for !AS>/FAO=1
	getmsg		<error obtaining message text>
	invalqual	<the !AS is an invalid qualifier in this context>/FAO=1
	nooutqual	<the /SHOW qualifier is invalid without specifing the /OUTPUT qualifier>
	mdbsfcrupt	<manufacturer's detected bad sector file is corrupt on !AS>/FAO=1
	mdbsfrfail	<failed to read the manufacturer detected bad sector file on !AS>/FAO=1
	sdbsffull	<software detected bad sector file is full on !AS>/FAO=1
	sdbsfrfail	<failed to read the software detected bad sector file on !AS>/FAO=1

	.END
