	.TITLE	DIRECTMSG - MESSAGES FOR THE DIRECTORY UTILITY
	.IDENT	/V04-000/

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:	DIRECTORY
!
! ABSTRACT:
!
!	This module contains all of the error messages unique to the
!	DIRECTORY facility.  It also contains messages for all of the
!	text used for headings, etc.
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, unprivileged user mode utilities.
!
!--
!
! AUTHOR:	L. Mark Pilant		CREATION DATE:  27-Sep-1983
!
! MODIFIED BY:
!
!	V03-002	LMP0225		L. Mark Pilant,		8-Apr-1984  10:10
!		Change the text of the NOBACKUP message to read "backups
!		disabled" instead of "not backed up"
!
!	V03-001	LMP0211		L. Mark Pilant,		10-Mar-1984  12:46
!		Add additional messages for the file information obtained
!		directly from the disk ACP.
!
!**

	.FACILITY	DIRECT,121/SYSTEM/PREFIX=DIR$_

! Real error messages.

	.SEVERITY	WARNING
	NOFILES		"no files found"

! Text messages.

! Common messages.

	.SEVERITY	INFORMATIONAL
	NEWDIRECT	"Directory !AD"/FAO=1

! Brief format messages.

	NOBRFILEID	"         None        "
	NOBRCREDAT	"   <None specified>"
	NOBRREVDAT	"   <None specified>"
	NOBREXPDAT	"   <None specified>"
	NOBRBAKDAT	"   <No backup done>"

! Full format messages.

	FULLFILEID	"!#* File ID:  !19<(!UW,!UW,!UW)!>"/FAO=4
	NOFUFILEID	"!#* File ID:  None"/FAO=1
	FULLSIZE	"Size:   !10UL/!10<!UL!>"/FAO=2
	FULLOWNERID	" Owner:    !%I"/FAO=1
	FULLOWNERUIC	" Owner:    !%U"/FAO=1
	NOFUCREDAT	"Created:   <None specified>"
	FULLCREDAT	"Created:  !17%D"/FAO=1
	NOFUREVDAT	"   Revised:   <None specified>"
	FULLREVDAT	"   Revised:  !17%D (!UW)"/FAO=2
	NOFUEXPDAT	"Expires:   <None specified>"
	FULLEXPDAT	"Expires:  !17%D"/FAO=1
	NOFUBAKDAT	"   Backup:    <No backup done>"
	FULLBAKDAT	"   Backup:   !17%D"/FAO=1
	FILEORG		"File organization:  "
	FILORGSEQ	"Sequential"
	FILORGREL	"Relative, maximum record number: !UL"/FAO=1
	FILORGIDX	"Indexed"
	IDXPROLOG	", Prolog: !UW, Using !UB key!%S"/FAO=2
	IDXAREA		"!29* In !UB area!%S"
	FILORGUNK	"Unknown, type: !UB"/FAO=1
	FILEATTR	"File attributes:    Allocation: !UL, Extend: !UW"/FAO=2
	MAXBKTSIZ	"Maximum bucket size: !UB"/FAO=1
	BUCKETSIZ	"Bucket size: !UB"/FAO=1
	GBLBUFCNT	"Global buffer count: !UW"/FAO=1
	VERLIMIT	"Version limit: !UW"/FAO=1
	NOVERLIMIT	"No version limit"
	FILATRCTG	"Contiguous"
	FILATRCTB	"Contiguous best try"
	FILATRLCK	"Locked"
	FILATRNOBAK	"Backups disabled"
	FILATRWRBAK	"Write back cached"
	FILATRRDCHK	"Verify read operations"
	FILATRWRCHK	"Verify write operations"
	FILATRBADACL	"Corrupted ACL"
	FILATRDIR	"Directory file"
	FILATRBADBLK	"File contains bad blocks"
	FILATRNOCHRG	"File not charged to quota"
	FILATRERASE	"Erase before deletion"
	RECFORMAT	"Record format:      "
	RECFMTFIX	"Fixed length !UL byte records"
	RECFMTVAR	"Variable length"
	RECFMTVFC	"VFC, !UL byte header"
	RECFMTUDF	"Undefined"
	RECFMTSTM	"Stream"
	RECFMTSTMLF	"Stream_LF"
	RECFMTSTMCR	"Stream_CR"
	RECFMTUNK	"Unknown, type: !UB"/FAO=1
	MAXRECSIZ	", maximum !UW byte!%S"/FAO=1
	RECATTR		"Record attributes:  "
	NORECATTR	"None"
	CRCARCTL	"Carriage return carriage control"
	FTNCARCTL	"Fortran carriage control"
	PRICARCTL	"Print file carriage control"
	NOCARCTL	"No carriage control"
	NOSPAN		"Non-spanned"
	JNLENABLED	"Journaling enabled: "
	NOJNLENB	"None"
	BIJNLNAME	"BI journal name:    !AC"/FAO=1
	NOBIJNL		"BI journal name:    None"
	AIJNLNAME	"AI journal name:    !AC"/FAO=1
	NOAIJNL		"AI journal name:    None"
	ATJNLNAME	"AT journal name:    !AC"/FAO=1
	NOATJNL		"AT journal name:    None"
	FILEPROT	"File protection:    "
	SYSPROT		"System:"
	OWNPROT		", Owner:"
	GRPPROT		", Group:"
	WORPROT		", World:"
	FILEACL		"Access Cntrl List:  "
	NOFILEACL	"Access Cntrl List:  None"
	TOTSIZALL	"Total of !UL file!%S, !UL/!UL block!%S."/FAO=3
	TOTSIZ		"Total of !UL file!%S, !UL block!%S."/FAO=2
	TOTNOSIZ	"Total of !UL file!%S."/FAO=1
	GTOTSIZALL	"Grand total of !UL directories, !UL file!%S, !UL/!UL block!%S."/FAO=4
	GTOTSIZALL1	"Grand total of !UL directory, !UL file!%S, !UL/!UL block!%S."/FAO=4
	GTOTSIZ		"Grand total of !UL directories, !UL file!%S, !UL block!%S."/FAO=3
	GTOTSIZ1	"Grand total of !UL directory, !UL file!%S, !UL block!%S."/FAO=3
	GTOTNOSIZ	"Grand total of !UL directories, !UL file!%S."/FAO=2
	GTOTNOSIZ1	"Grand total of !UL directory, !UL file!%S."/FAO=2

	.END
