!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
! MODIFIED BY:
!
!	V03-022	HWS0073		Harold Schultz	12-Jun-1984
!		Add ENTNF (ENTity Not Found)
!
!	V03-021 HWS0053		Harold Schultz	09-Apr-1984
!		Add KEYCNV.
!		Change wording in SYMTRUNC.
!		Change wording in TABEXIST.
!
!	V03-020	HWS0029		Harold Schultz	14-Mar-1984
!		Add DELSYM, SYMTRUNC
!
!	V03-019	HWS0016		Harold Schultz	23-Feb-1984
!		Add TABEXIST, TABSUPER, TABNOTFND informational messages
!		for logical name table creation.
!
!	V03-018	PCG0019		Peter George	29-Nov-1983
!		Correct spelling of TRMMBX message.
!		Remove RECALEND.
!
!	V03-017	DLB0001		David Ballenger	02-Aug-1983
!		Add CMDFILERR for MCR.
!
!	V03-016	PCG0018		Peter George	15-Jul-1983
!		Change date format in IVATIME and IVDTIME.
!		Change text of NOCCAT, NOLIST, PARMDEL, USGOTO, ONEVAL, UNDFIL,
!		NOTHEN, CONFLICT, RSLOVF, TRMMBX, SKPDAT, NOCHANGE, IVCHAR, 
!		and INVTAB.  Add TKNOVF and IGNQUAL.
!		Add "and validity" to all "check spelling" messages.
!
!	V03-015	PCG0017		Peter George	23-Jun-1983
!		Change date format in IVATIME and IVDTIME.
!
!	V03-014	PCG0016		Peter George	21-Jun-1983
!		Add NOTDISCON, IVATIME, IVDTIME, NOPAREN.
!		Modify NUMBER and NULFIL.
!
!	V03-013	MAJ0007		Melanie Johnson	20-May-1983
!		Change INSPRIV to informational.  Add NOCHANGE and NODIRCHG.
!
!	V03-012	PCG0015		Peter George	10-May-1983
!		Reword many error messages.
!
!	V03-011	PCG0014		Peter George	20-Apr-1983
!		Add ALLOC and SUPERSEDE.
!		Change text of OLDTAB.
!
!	V03-010	PCG0013		Peter George	10-Apr-1983
!		Add CMDNOTFND.
!
!	V03-009	PCG0012		Peter George	17-Feb-1983
!		Add CONFLICT, UNDKEY, INVROUT, OLDTAB, INVTAB, DEFKEY,
!		DELKEY, SETKEY, RECALEND, OKTAB, UPGTAB.
!
!	V03-008	PCG0011		Peter George	03-Feb-1983
!		Add NOTIFY.
!
!	V03-007	PCG0010		Peter George	21-Jan-1983
!		Add CMDSEG and NOCMDPROC.
!
!	V03-006 MAJ0006		Melanie Johnson	20-Jan-1983
!		Add CMDGONE.  Fix spelling error in SPR message text.
!
!	V03-005	PCG0009		Peter George	16-Nov-1982
!		Add SPR.
!
!	V03-004	PCG0008		Peter George	15-Nov-1982
!		Change PMPTOOLNG to STRTOOLNG.
!
!	V03-003	PCG0007		Peter George	18-Oct-1982
!		Add PMPTOOLNG.
!
!	V03-002	PCG0006		Peter George	19-Aug-1982
!		Add NOPREVCMD, COMMA.
!
!	V03-001	PCG0005		Peter George	18-Jun-1982
!		Add LOCPRES and LOCNEG.
!---

!
! DEFINE CLI RELATED STATUS VALUES
!
 
 
	.FACILITY	CLI,3 /SYSTEM /MACRO=$CLIMSGDEF
	.SEVERITY	WARNING

	ABVERB		<ambiguous command verb - supply more characters>
	ABKEYW		<ambiguous qualifier or keyword - supply more characters>
	BUFOVF		<command buffer overflow - shorten expression or command line>
	COMPLX		<expression too complex - simplify>
	DEFOVF		<too many command procedure parameters - limit to eight>
	DIRECT		<invalid directory syntax - check brackets and other delimiters>
	EXPSYN		<invalid expression syntax - check operators and operands>
	IMCHNG		<two images requested in one command>					! Not used by DCL nor by MCR
	INSFPRM		<missing command parameters - supply all required parameters>
	IVCHAR		<invalid numeric value - check for invalid digits>
	.LITERAL	CLI$_SPARE=229464

	.BASE		12

	IVKEYW		<unrecognized keyword - check validity and spelling>
	IVOPER		<unrecognized operator in expression - check spelling and syntax>
	IVPROT		<invalid protection code - only use combinations of R,W,E, and D>
	IVQLOC		<invalid qualifier location - place after a parameter>
	IVSYMB		<invalid symbol name - start name with an alphabetic character>
	IVVALU		<invalid value syntax - see command documentation>
	IVVERB		<unrecognized command verb - check validity and spelling>
	MAXPARM		<too many parameters - reenter command with fewer parameters>
	NOATFIL		<no file name for command procedure>					! Not used by DCL nor by MCR
	NOCCAT		<parameter concatenation not allowed - check use of plus (+)>
	NOCOMD		<no command on line - reenter with alphabetic first character>
	NOKEYW		<qualifier name is missing - append the name to the slash>
	NOLIST		<list of parameter values not allowed - check use of comma (,)>
	NOQUAL		<qualifiers not allowed - supply only verb and parameters>
	NOVALU		<value not allowed - remove value specification>
	NOTNEG		<qualifier or keyword not negatable - remove "NO" or omit>
	NULFIL		<missing or invalid file specification - respecify>
	NUMBER		<invalid numeric value - supply an integer>
	ONCOMD		<ON command too large - decrease the length of the THEN clause>
	ONERR		<invalid ON condition - use WARNING, SEVERE, ERROR, or CONTROL_Y>
	ONLEVL		<invalid ON context - use only within command procedures>
	ONOVF		<no room for ON command - symbol overflow, delete some symbols>
	PARMDEL		<invalid parameter delimiter - check use of special characters>
	RSLOVF		<buffer overflow - specify fewer command elements>
	SKPDAT		<image data (records not beginning with "$") ignored>
	STKOVF		<command procedures too deeply nested - limit to 16 levels>
	SYMDEL		<invalid symbol or value delimiter - check command syntax>
	SYMOVF		<no room for symbol definitions - delete some symbols>
	UNDSYM		<undefined symbol - check validity and spelling>
	USGOTO		<target of GOTO not found - check spelling and presence of label>
	VALREQ		<missing qualifier or keyword value - supply all required values>
	ONEVAL		<list of values not allowed - check use of comma (,)>
	OVRFLW		<too much data - modify size of field or size of data>
	UNPROQUAL	<unprocessed qualifiers>						! Old CLI interface status
	UNPROPARM	<unprocessed parameters>						! Old CLI interface status
	INVKEY		<invalid keyword>							! Old MCR status going away soon
	INVRSP		<invalid response>							! Not used by DCL nor by MCR
	UNDFIL		<file has not been opened by DCL - check logical name>
	FILOPN		<file is already open>							! Not used by DCL nor by MCR
	BADRET		<RETURN was issued without a subroutine>				! Not used by DCL nor by MCR
	ABSYMD		<abbreviated symbol definition conflict - rename symbol>
	INVUIC		<invalid UIC - must be of the form [group,member]>
	BADTEXT		<  \!AS\!AS> /FAO=2							! Not used by DCL nor by MCR
	ABFNAM		<ambiguous lexical function name - supply more characters>
	IVFNAM		<invalid lexical function name - check validity and spelling>
	BLKOVRFLOW	<block overflow>							! Not used by DCL nor by MCR
	BLKUNDFLOW	<block underflow>							! Not used by DCL nor by MCR
	BADBLK		<END issued without corresponding BEGIN>				! Not used by DCL nor by MCR
	NOLBLS		<label ignored - use only within command procedures>
	NOCHANGE	<neither directory nor UIC could be changed - see documentation>	! MCR-only status
 	ABSENT		<entity or value absent from command string>				! New CLI interface status
	NEGATED		<entity explicitly negated in command string>				! New CLI interface status
	INVFILSPE	<input or output file specification too long - shorten>
	INVLOGFIL	<invalid log file specification>					! Not used by DCL nor by MCR
	NOTHEN		<IF or ON statement syntax error - check placement of THEN keyword>
	SYMTOOLNG	<symbol !AS is too long to copy to subprocess> /FAO=1
	ASTDCL		<out-of-band or ctrl/c AST's will also be delivered to parent>		! Goes away in V4
	INVRANGE	<field specification is out of bounds - check sign and size>
	LOCNEG		<entity explicitly and locally negated in command string>		! New CLI interface status
	CMDNOTFND	<command not found - use RECALL/ALL to display saved commands>
	IVQUAL		<unrecognized qualifier - check validity, spelling, and placement>
	CMDSEG		< \!AS\> /FAO=1
	NOTIFY		</NOTIFY not allowed - do not use with /WAIT or in batch jobs>
	CONFLICT	<illegal combination of command elements - check documentation>
	UNDKEY		<!AC key !AS is undefined> /FAO=2
	ARGREQ		<missing argument - supply all required arguments>
	SYMLNG		<symbol name is too long - shorten the name>
	SYMABR		<abbreviated symbols not allowed - remove "*" from symbol name>
	IVKEYNAM	<unrecognized key name - check validity and spelling>
	NOPAREN		<value improperly delimited - supply parenthesis>
	IVATIME		<invalid absolute time - use DD-MMM-YYYY:HH:MM:SS.CC format>
	IVDTIME		<invalid delta time - use DDDD-HH:MM:SS.CC format>
	TKNOVF		<command element is too long - shorten>
	CMDFILERR	<login command file initialization error>				! MCR-only status
 
!
! DEFINE CLI RELATED "ERROR" LEVEL ERROR CODES
!	BEGIN ERROR CODE 2048 FROM WARNING TO
!	LEAVE ROOM FOR 256 WARNINGS.
!
	.SEVERITY	ERROR
	.BASE		256

	CONFQUAL	<conflicting qualifiers>						! Old CLI interface status
	INVQUAL		<invalid qualifier>							! Old CLI interface status
	REQPRMABS	<required parameter is absent>						! Old CLI interface status
	INVQUALNUM	<invalid qualifier number>						! Old CLI interface status
	INVREQTYP	<invalid request type>							! Used by call backs
	NOVALUE		<value not present>							! Old CLI interface status
	VALCNVERR	<error converting value>						! Old CLI interface status
	ILLVAL		<illegal value is present>						! Used by call backs
	NOOPTPRS	<no option present on command>						! Old CLI interface status
	CREQUEJOB	<error creating job on queue !AS> /FAO=1				! Not used by DCL nor by MCR
	SUBMITERR	<error submitting file to queue !AS> /FAO=1				! Not used by DCL nor by MCR
	DEVALSPL	<device already spooled>						! Not used by DCL nor by MCR
	DEVNOTSPL	<device not spooled>							! Not used by DCL nor by MCR
	IVDEVTYPE	<invalid device type - specify a mailbox device>			! MCR-only status
	IMGFNF		<image file not found>							! MCR-only status
	DEVNOTFOR	<device not mounted foreign>						! Not used by DCL nor by MCR
	PWDNOTVAL	<old password validation error - password unchanged>			! Set password status
	PWDNOTVER	<new password verification error - password unchanged>			! Set password status
	PWDLOCKED	<password was locked to prevent change>					! Set password status
	NOTFR		<no transfer address>							! Image activation error - part 2
	PWDSYNTAX	<illegal password syntax>						! Set password status
	IMGNAME		<image file !AS> /FAO=1							! Image activation error - part 2
	IMAGEFNF	<image file not found !AS> /FAO=1					! Image activation error - part 2
	BADSTRLVL	<unrecognized structure level for command tables>			! Not used by DCL nor by MCR
	REFUSED		<you cannot attach to that process>
	BADCTLMSK	<bad control character enable/disable mask>				! Used by call backs
	INVRFM		<invalid record format for record I/O - file not opened>
	NOCLINT		<image requested CLI interface routine that does not exist>		! MCR-only status
	NOSPAWN		<DCL cannot spawn an MCR subprocess - subprocess aborted>		! MCR-only status
	SPWNIO		<shared input or output files are not allowed - respecify>
	TRMMBX		<terminal has associated mailbox - terminate image and then SPAWN>
	STRTOOLNG	<string argument is too long - shorten>
	CMDGONE		<this is no longer a valid command - see documentation>			! MCR-only status
	NOCMDPROC	<error opening captive command procedure - access denied>
	INVROUT		<invalid routine specified in command tables - check .CLD file>
	OLDTAB		<command tables have obsolete format - use SET COMMAND to recreate>
	INVTAB		<command tables have invalid format - see documentation>
	NOTDISCON	<terminal is not disconnectable - explicitly specify LOGOUT>
	ENTNF		<specified entity not found in command tables>

!
! DEFINE INFORMATIONAL MESSAGES.
!
	.SEVERITY	INFORMATION
	.BASE		3000

	DEFKEY		<!AC key !AS has been defined> /FAO=2
	DELKEY		<!AC key !AC has been deleted> /FAO=2
	SETKEY		<keypad state has been set to !AC> /FAO=1
	SPARE1		<spare - for future use>						! Not currently used
	ALLOC		<!AS allocated> /FAO=1
	SUPERSEDE	<previous value of !AS has been superseded> /FAO=1
	INSPRIV		<insufficient privilege to change UIC - you need CMKRNL privilege>	! MCR-only status
	NODIRCHG	<directory cannot be changed to match UIC greater than [377,377]>	! MCR-only status
	IGNQUAL		<qualifiers appearing before this item were ignored>
	TABEXIST	<!AS already exists - not superseded> /FAO=1
	TABSUPER	<previous table !AS has been superseded> /FAO=1
	TABNOTFND	<previous table !AS was not found - new table created> /FAO=1
	DELSYM		<!AC symbol !AC has been deleted> /FAO=2
	SYMTRUNC	<preceding symbol value has been truncated>
	KEYCNV		<synonym key !AS has been converted to !AS> /FAO=2
!
! DEFINE SUCCESSFUL MESSAGES
!
	.SEVERITY	SUCCESS
	.BASE		4000

	SPAWNED		<process !AS spawned> /FAO=1
	ATTACHED	<terminal now attached to process !AS> /FAO=1
	RETURNED	<control returned to process !AS> /FAO=1
	PRESENT		<entity value is present in command string>				! New CLI interface status
	DEFAULTED	<entity defaulted present in command string>				! New CLI interface status
	CONCAT		<requested value is terminated by a plus sign>				! New CLI interface status
	LOCPRES		<entity value is locally present in command string>			! New CLI interface status
	COMMA		<requested value is terminated by a comma>				! New CLI interface status
	OKTAB		<command tables are already in latest format>				! CDU conversion routine status
	UPGTAB		<command tables have been upgraded to latest format>			! CDU conversion routine status

	.BASE		4094

	PROC_ID		<identification of created process is !XL> /FAO=1			! Not used by DCL nor by MCR
	QUEJOBCRE	<  Job !UW entered on queue !AC> /FAO=2					! Not used by DCL nor by MCR

	.LITERAL	CLI$_NORMAL=196609
 
	.END
