	.TITLE		SOR$MSG
	.IDENT		'V04-000'	! File: SORMSG.MSG Edit: PDG3024
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
!
! FACILITY:	VAX-11 SORT/MERGE
!
! ABSTRACT:
!
!	This file contains the definition for the SORT facility specific
!	error messages.  The facility code for SORT/MERGE is 28.
!
! ENVIRONMENT:	VAX/VMS user mode
!
! AUTHOR: P. Gilbert, CREATION DATE: 15-Feb-1982
!
! MODIFIED BY:
!
!	T03-015		Original
!	T03-018	Changed the severity of WORK_DEV from fatal to severe.
!		PDG 16-Dec-1982
!	T03-019	Added OPERFAIL, REQ_ALT and USE_ALT.  PDG 21-Dec-1982
!	T03-020	Add new messages for errors with collating sequences.
!		PDG 26-Jan-1983
!	T03-021	Added new messages for CDD errors.  PDG 11-Feb-1983
!	T03-022	Added ENDDIAGS.  PDG 16-Mar-1983
!	T03-023	Change text of COL_PAD.  PDG 20-Apr-1983
!	T03-024	Added OPREPLY.  PDG 9-May-1983
!--

!
! Some error messages were issued by old versions of VAX-11 SORT/MERGE,
! but are no longer be issued.  These must still be defined.
!
! Some error messages will be used by the new version of VAX-11 SORT/MERGE,
! but are not yet issued by the code.  These are prefixed with a "?".
!

	.FACILITY	SORT,28 /SYSTEM /PREFIX=SOR$_ /MACRO=$SORDEF
	.SEVERITY	FATAL
	.BASE		0

	MISS_KEY	<OBS>
	WORK_DEV	<work file !AS must be on random access local device>/FAO=1/ERROR
	NO_WRK		<work files required, cannot do sort in memory as requested>/ERROR
	VM_FAIL		<OBS>
	WS_FAIL		<OBS>
	SORT_ON		<sort or merge routines called in incorrect order>/FATAL
	BAD_KEY		<invalid key specification>/FATAL
	NUM_KEY		<too many keys specified>/FATAL
	BAD_LEN		<OBS>
	ONE_IN		<OBS>
	IND_OVR		<indexed output file must already exist>/FATAL
	INCONSIS	<OBS>
	VAR_FIX		<?some records may be truncated on output>/WARNING
	BAD_TYPE	<invalid sort process specified>/FATAL
	LRL_MISS	<longest record length must be specified>/FATAL
	BAD_SPEC	<?invalid specification file record, field: !AS>/FAO=1/FATAL
	BAD_LRL		<record length (!UL) greater than specified longest record length>/FAO=1/ERROR
	BAD_FILE	<OBS>
	BAD_ADR		<OBS>
	MAP		<OBS>
	EXTEND		<unable to extend work file for needed space>/FATAL
	KEY_LEN		<invalid key length, key number !SL, length !SL>/FAO=2/ERROR
	CLEAN_UP	<OBS>
	BAD_MERGE	<number of work files must be between 0 and 10>/ERROR
	BAD_ROUTIN	<OBS>
	INP_FILES	<too many input files specified>/FATAL
	BAD_ORDER	<merge input is out of order>/WARNING
!
! V3B messages are defined below
!
	DUP_OUTPUT	<output file has already been specified>/FATAL
	MISS_PARAM	<a required subroutine parameter is missing>/FATAL
	END_SORT	<sort/merge terminated, context = !XL>/FAO=1/SUCCESS
	KEYED		<mismatch between sort/merge keys and primary file key>/ERROR
	BAD_SRL		<record length (!UL) is too short to contain keys>/FAO=1/WARNING
	NODUPEXC	<equal-key routine and no-duplicates option cannot both be specified>/FATAL
	DELETE1		<delete the first record from the sort>/SUCCESS
	DELETE2		<delete the second record from the sort>/SUCCESS
	DELBOTH		<delete both records from the sort>/SUCCESS
	NYI		<functionality is not yet implemented>/ERROR
	RTNERROR	<unexpected error status from user-written routine>/ERROR
	KEYAMBINC	<key specification is ambiguous or inconsistent>/FATAL
	OBS_0		<OBS>
	ROPRAND		<utility converted a reserved operand to a valid value>/ERROR
	UNDOPTION	<undefined option flag was set>/FATAL
	STABLEEXC	<equal-key routine and stable option cannot both be specified>/FATAL
	SRTIWA		<insufficient space; specification file is too complex>/FATAL
	SPCOVR		<overridden specification, at line !UL>/WARNING/FAO=1
	SPCMIS		<invalid merge specification, at line !UL>/WARNING/FAO=1
	SPCSIS		<invalid sort specification, at line !UL>/WARNING/FAO=1
	SPCIVP		<invalid sort process, at line !UL>/FATAL/FAO=1
	SPCIVS		<invalid specification, at line !UL>/FATAL/FAO=1
	SPCIVC		<invalid collating sequence specification, at line !UL>/FATAL/FAO=1
	SPCIVF		<invalid field specification, at line !UL>/FATAL/FAO=1
	SPCIVD		<invalid data type, at line !UL>/FATAL/FAO=1
	SPCIVX		<invalid condition specification, at line !UL>/FATAL/FAO=1
	SPCIVK		<invalid key or data specification, at line !UL>/FATAL/FAO=1
	SPCIVI		<invalid include or omit specification, at line !UL>/FATAL/FAO=1
	INCNOKEY	<include specification references no keys, at line !UL>/FATAL/FAO=1
	INCNODATA	<include specification references no data, at line !UL>/FATAL/FAO=1
	INVFOLD		<FOLD has no meaning in this context, at line !UL>/ERROR/FAO=1
	OPERFAIL	<error requesting operator service>/FATAL
	REQ_ALT		"specify alternate !AC file (or nothing to simply try again)!/SORT> "/FAO=1/INFORMATIONAL
	USE_ALT		<using alternate !AC file !AS>/FAO=2/INFORMATIONAL

	COL_ADJ		<>/FATAL
	COL_CMPLX	<collating sequence is too complex>/FATAL
	COL_CHAR	<invalid character definition>/FATAL
	COL_PAD		<invalid pad character>/FATAL
	COL_THREE	<cannot define 3-byte collating values>/FATAL

	BADDTYPE	<invalid or unsupported CDD datatype>/ERROR
	BADLENOFF	<length and offset must be multiples of 8 bits>/ERROR
	BADOCCURS	<invalid OCCURS clause>/FATAL
	BADOVRLAY	<invalid overlay structure>/ERROR
	BADPROTCL	<node is an invalid CDD object>/FATAL
	CDDERROR	<CDD error at node !AS>/FATAL/FAO=1
	ILLBASE		<nondecimal base is invalid>/ERROR
	ILLLITERL	<record containing symbolic literals is unsupported>/FATAL
	ILLSCALE	<nonzero scale invalid for floating point data-item>/ERROR
	INCDIGITS	<number of digits is not consistent with the type or length of item>/ERROR
	MISLENOFF	<length and offset required>/WARNING
	MULTIDIM	<invalid multidimensional OCCURS>/ERROR
	NOTRECORD	<node !AS is a !AS, not a record definition>/FATAL/FAO=2
	SIGNCOMPQ	<Absolute Date and Time datatype represented in one second units>/WARNING
	UNSUPLEVL	<unsupported core level for record !AS>/FATAL/FAO=1
	ENDDIAGS	<completed with diagnostics>/INFORMATIONAL
	OPREPLY		<operator reply is "!AS">/FAO=1/INFORMATIONAL
	CHKPNT		<checkpoint taken at !%D>/FAO=1/SUCCESS

	.END
