	.TITLE		SRTTRNMSG
	.IDENT		'V04-000'	! File: SRTTRNMSG.MSG Edit: PDG3003
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
!
! FACILITY:	SORT/MERGE specification file translator.
!
! ABSTRACT:
!
!	This file contains the definition for the error messages specific
!	to the SORT/MERGE specification file translator.  The facility code
!	for SORT/MERGE is 28.
!
! ENVIRONMENT:	VAX/VMS user mode
!
! AUTHOR: P. Gilbert, CREATION DATE: 15-Feb-1983
!
! MODIFIED BY:
!
!	T03-001		Original
!	T03-002	Change severity of INV_LIMIT, add INV_QUAL.  PDG 3-Mar-1983
!	T03-003	Add NOSTRIP_DATA error message.  PDG 14-May-1984
!--

	.FACILITY	SRTTRN,28 /SYSTEM /PREFIX=SRTTRN$_ /MACRO=$SRTTRNDEF
	.SEVERITY	FATAL
	.BASE		0

	INV_ALT		<Invalid alternate collating sequence field in header>
	INV_CONST 	<Invalid F/C field in include or omit line>
	INV_CONT	<Invalid continuation field in include or omit line>
	INV_DATA	<Invalid data type field in include, omit, or field line>
	INV_FIELD	<Invalid field type in field line>
	INV_LIMIT	<Invalid field limit in include, omit, or field line>/ERROR
	INV_PROCESS	<Invalid sort process field in header line>/ERROR
	INV_QUAL	<Invalid qualifier>/FATAL
	INV_SEQ		<Invalid sequence field in header line>
	INV_STRIP	<Invalid key strip field in header line>
	INV_TYPE  	<Invalid line type in specification file>
	LINE_NUM	<Line numbers out of sequence>/WARN
	NO_FORCE_TO	<Missing force column information in force line>
	NO_HEADER	<Missing header line in specification file>/ERROR
	NO_PAIRS	<No replacement pairs in altseq line>/WARN
	UNX_ALTSEQ	<Unexpected altseq line, see column 26 of header>/WARN
	UNX_FORCE	<Unexpected continuation of force key>
	ADDINCKEY	<Keys added to avoid comparing incompatible keys>/INFORMATIONAL
	COMPLEX		<Specification file is very complex - verify output>/ERROR
	DATALONG	<Output record length is longer than specified>/WARNING
	NOSTRIP_DATA	<Specified output length used as default data field length (nostrip)>/INFORMATIONAL

	.END
