! SYSGTTSTR.MSG - sysgen TERMINAL/ECHO command message file
!
!	Version 'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
!
! FACILITY:  VAX/VMS System Macro Libraries
!
! ABSTRACT:
!
!	*** SAMPLE MESSAGE FILE FOR TERMINAL/ECHO COMMAND ***
!
!	This file contains the message source for the SYSGEN
!	TERMINAL/ECHO command.
!
!	To change the terminal driver echo strings for:
!
!	^C, ^O, ^Y, and ^Z, do the following:
!
!	1) Edit the messages below to include the text that you want
!	   for a given echo.
!	2) To create the SYSGTTSTR.EXE file, issue the following DCL commands:
!
!	$ MESSAGE SYSGTTSTR
!	$ LINK SYSGTTSTR
!
!	3) Then, each time the system boots (in SYSTARTUP, for example):
!
!	$ SET MESSAGE SYSGTTSTR
!	$ RUN SYS$SYSTEM:SYSGEN
!	TERMINAL/ECHO
!
!	The command requires the SYSNAM and CMKRNL privileges.
!	The echos will now be re-loaded. This must be done at each boot.
!
! ENVIRONMENT:
!
!	n/a
!
!--
!
!
! AUTHOR:  Jake VanNoy	 CREATION DATE:  15-Jul-1983
!
! MODIFICATION HISTORY:
!
!	V03-001	JLV0384		Jake VanNoy		23-JUL-1984
!		Update strings so that they closely match terminal driver.

!
! DEFINE TTDRIVER CONTROL CHARACTER ECHO STRINGS 
!
!
! DEFINE MESSAGES
!

.FACILITY	SYSGEN,124 /SYSTEM /PREFIX=SYSG_TT$_
.SEVERITY	INFORMATIONAL
.BASE 	2048

!
! !/  string is included where <CR><LF> is to be inserted
! FAO count is 1 to force calling FAO during SYSGEN command.
!
	
CTRLY		<!/*INTERRUPT*!/>		/FAO=1		! standard ^Y
CTRLC		<!/*CANCEL*!/>			/FAO=1		! standard ^C
CTRLY_REG	<\!/7[7m Interrupt [m8!/>	/FAO=1		! ^Y for DEC_CRT
CTRLC_REG	<\!/7[7m Cancel [m8!/>	/FAO=1		! ^C for DEC_CRT
CTRLY_DEC	<!/7[7m Interrupt [m8!/>	/FAO=1		! ^Y for DEC_CRT
CTRLC_DEC	<!/7[7m Cancel [m8!/>	/FAO=1		! ^C for DEC_CRT
CTRLY_DECREG	<\!/7[7m Interrupt [m8!/>	/FAO=1		! ^Y for DEC_CRT
CTRLC_DECREG	<\!/7[7m Cancel [m8!/>	/FAO=1		! ^C for DEC_CRT

CTRLZ		<*EXIT*>			/FAO=1		! Standard ^Z
CTRLZ_DEC	<7[7m Exit [m8>		/FAO=1		! ^Z for DEC_CRT

CTRLO		<!/*OUTPUT OFF*!/>		/FAO=1		! output off
CTRLO_DEC	<!/7[7m Output Off [m8!/>	/FAO=1		! output off for DEC_CRT
OUTON		<*OUTPUT ON*>			/FAO=1		! output on
OUTON_DEC	<7[7m Output On [m8>	/FAO=1		! output on for DEC_CRT

.END
