    .TITLE ENCMESSAG
    .IDENT "V04-000"
!
!	Message definitions for the Data Encryption Facility
!
!

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:
!	VAX/VMS Data Encryption Services
!
! ABSTRACT:
!
!	These are the error messages and codes used by the various
!	routines of the facility
!
! ENVIRONMENT:
!
!	VAX/VMS operating system versions 3.0 or later.
!
! AUTHOR: J. Eric Pollack, CREATION DATE: 4-Nov-1982
!
! MODIFIED BY:
!
!	V01-003 JEP0005		Eric Pollack		31-Aug-1983
!		Add messages for file encryption
!
!	V01-002	JEP0004		Eric Pollack		21-Aug-1983
!		Add NOTHEXVAL
!
!	V01-001 JEP0002		Eric Pollack		20-Mar-1983
!		Enhance status messages.
!
!--

	.FACILITY	ENCRYP,282 /SYSTEM /PREFIX=ENCRYPT$_

	.SEVERITY	SUCCESS
	.BASE		0

	SUCCESS		<Success>
	ENCSERCOM	<Encryption/Decryption test series complete>/IDENT=TESTDNE
    	FILENCBLK	<!AS encrypted to !AS (!UL block!%S)> /FAO=3 /IDENT=ENCRYPTED
    	FILDECBLK	<!AS decrypted to !AS (!UL block!%S)> /FAO=3 /IDENT=DECRYPTED
    	FILENCREC	<!AS encrypted to !AS (!UL record!%S)> /FAO=3 /IDENT=ENCRYPTED
    	FILDECREC	<!AS decrypted to !AS (!UL record!%S)> /FAO=3 /IDENT=DECRYPTED
	STATISTICS	<Encryption Stream Statistics:!/!_Total Records: !ZL!/!_Total Bytes: !+!ZL!/!_Total Time: !%T> /FAO=3
	ERASED		<!AS erased and deleted>/FAO=1


	.SEVERITY	ERROR
	.BASE		20

	INVARGCOU	<Invalid argument count for ENCRYPT$ routine>
	NOTYETIMP	<This function is not yet implemented>
    	NOTESTROU	<No test routine is available for this algorithm>
    	NOFILESER	<File encryption/decryption services are not supported>
    	FILDISKONLY	<File encryption/decryption may be from disk file to disk file only, !AS>/FAO=1
    	FILNOPPF	<File encryption of a process permenant file is not supported, !AS>/FAO=1
    	FILNODIR	<File encryption of directories is not supported, !AS>/FAO=1
	FILBADBLK	<File contains bad block(s), processing not attempted , !AS>/FAO=1

	.SEVERITY	FATAL
	.BASE		40

	INSCONSPA	<Insufficient Context space to support this algorithms needs>
	ILLALGSEL	<Algorithm selection unknown or unsupported>
	ILLALGMOD	<Algorithm sub-mode selection unknown or unsupported>
	KEYPARERR	<Key parity error>
	KEYLENERR	<Key length does not meet algorithm requirements>
	INPLENERR	<Input length does not meet algorithm requirements>
	OUTLENERR	<Output length does not meet algorithm requirements>
	CONLENERR	<Context area length error>
	CONINIERR	<Unable to initalize the work area for the algorithm selected>
	CONPOIINI	<Context area is already initialized>
	KEYTRNERR	<Unable to obtain key value from key storage>
    	ALGSUBNOT	<Algorithm sub-mode option not supported>
    	INCKEYDEF	<Incompatible key definition>
	NOTHEXVAL	<Key value not Hexadecimal constant as specified>
	KEYBUFCKS	<Checksum of encrypted file key is invalid>
	FILSTRUNS	<Structure of encrypted file is unsupported , !AS>/FAO=1
	CONNOTINI	<Context area not yet initialized>
	ILLDESTYP	<Illegal descriptor type for specifying parameter>

	.SEVERITY	WARNING
	.BASE		80
    	HIGHVER		<Creating output file for which higher versions exist, !AS>/FAo=1
    	SUPERSEDE	<Superseding output file, !AS>/FAO=1
    	CRECONTIG	<Unable to create file as contiguous, !AS>/FAO=1

	.END
