	.TITLE	CNFMSG
	.IDENT 'V04-000'
! 
! CNF MESSAGES 
! 
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!  AUTHOR:	Bob Grosso
!
!  DATE:	15-Oct-1982
!
!  MODIFIED BY:
!
!	V03-001	RPG0001		Bob Grosso		02-May-1983
!		Make CNF$_PRIV severity an ERROR instead of FATAL.
!		Add CNF$_TMPMBX and CNF$_NETMBX to indicate two required
!		privileges.
! 
    .FACILITY	NICONFIG,289 /SYSTEM /PREFIX=CNF$_

    .SEVERITY	INFORMATIONAL

	GETVM/FAO_COUNT=1	<Allocated !UL bytes of virtual memory, total of !UL>
	!
	! If the VM bit is set in NICONFIG$LOG, then every time virtual memory
	! is allocated, the amount will be tallied and the tally will be 
	! signalled.

	FREEVM/FAO_COUNT=1	<Deallocated !UL bytes of virtual memory leaving !UL>
	!
	! If the VM bit is set in NICONFIG$LOG, then every time virtual memory
	! is deallocated, the amount will be tallied and the tally will be 
	! signalled.

	LOGIO			<NICONFIG requires LOG_IO privilege>
	!
	! NICONFIG must run with LOG_IO privilege.  The simplest way to
	! ensure that it does is to install it with this privilege.

	SYSNAM			<NICONFIG requires SYSNAM privilege>
	!
	! NICONFIG must run with SYSNAM privilege in order to declare
	! itself as a known image to be eligible for multiple connects.
	! The simplest way to ensure that it does is to install it 
	! with this privilege.

	NETMBX			<NICONFIG requires NETMBX privilege>
	!
	! NICONFIG must run with NETMBX privilege in order to declare
	! itself as a known image to be eligible for multiple connects.
	! The simplest way to ensure that it does is to install it 
	! with this privilege.

	TMPMBX			<NICONFIG requires TMPMBX privilege>
	!
	! NICONFIG must run with TMPMBX privilege in order to declare
	! itself as a known image to be eligible for multiple connects.
	! The simplest way to ensure that it does is to install it 
	! with this privilege.


    .SEVERITY	WARNING

	FAILGETVM/FAO_COUNT=1	<failed to allocate !UL bytes of virtual memory>
	!
	! An error occurred when NICONFIG attempted to allocate virtual memory.
	! Check the error message which should accompany it to determine
	! whether the virtual address space has been exceeded, or whether
	! a program error has been uncovered.  An invalid address or size
	! for allocation would be indicative of a program error.

	FAILFREVM/FAO_COUNT=1	<failed to deallocate !UL bytes of virtual memory>
	!
	! Error occurred when NICONFIG attempted to deallocate virtual memory.
	! Check the error message which should accompany it to determine
	! whether the virtual address space has been exceeded, or whether
	! a program error has been uncovered.  An invalid address or size
	! for deallocation would be indicative of a program error.

    .SEVERITY	ERROR

	LINK			<Error on logical link>
	!
	! An error has occurred on a logical link, see accompanying message
	! to determine course of action.

	SYSID			<Error while obtaining system ID message>
	!
	! An error occurred during the read to the NI device driver.
	! See accompanying message for appropriate action.

	PRIV			<Privilege error>
	!
	! NICONFIG was not executing with all the privileges which it needs
	! for proper execution.  Messages enumerating the lacking privileges 
	! should accompany this message.  NICONFIG should be installed with
	! the required privileges before attempting execution.


    .SEVERITY	FATAL

	LOGIC			<Program logic error or unexpected condition>
	!
	! A condition or circumstance was encountered which the NICONFIG
	! logic was not prepared to handle.  This is a programming error
	! and should be reported.

	NETASN			<failed to declare name to network>
	!
	! An error occurred when NICONFIG attempted to declare itself
	! to the network as an known object.  See the accompanying message
	! to determine action.

	MAILBOX			<Mailbox error>
	!
	! An error has occurred reading a mailbox, see accompanying message
	! to determine course of action.

	CHAN			<Error assigning or deassigning channel>
	!
	! An error has occurred assigning or deassigning a channel, see 
	! accompanying message to determine course of action.

	DRVRSTRT		<Error while issuing startup command to driver>
	!
	! An error has occurred while attempting to issue the startup commands
	! to the NI driver in preparation to reading the broadcast system ID
	! messages.  See the accompanying message to determine effective course
	! of action.

     .END
