	.TITLE	NML_MESSAGE
! 
! Network Management Listener messages
!
! Version:	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!  AUTHOR:	Kathy Perko
!
!  DATE:	22-July-1983
!
!  MODIFIED BY:
!	V03-001	MKP0001		Kathy Perko		12-July-1984
!		Change some messages to "informational" messages.
!
!--
	.FACILITY	NML,517 /SYSTEM

	.SEVERITY	INFORMATIONAL

	RECREPLC		<Database entry updated>
	RECADDED		<Database entry added>
	RECDELET		<Database entry deleted>


	.SEVERITY	ERROR

	NULL			<> 
	READERR			<Error reading database entry>
	WRITERR			<Error writing database entry>
	DELETERR		<Error deleting database entry>
	NORECOWN		<Failed to find record owner>
	NODCVTERR		<Error converting node permanent database>
	DSCBFOVF		<Parameter descriptor buffer overflow>
	QIOBFOVF		<QIO buffer overflow>
	RECBFOVF		<Record buffer overflow>
	NCBFAIL			<Undefined object on local node>
	BADEVTUPD		<Failed to update event parameter>
	INTEVTOVF		<Internal event buffer overflow>
	NOSNKNOD		<No sink node found in logging data base entry>
	OPABTERM		<Operation abnormally terminated>
