	.TITLE	IMAGE$MESSAGE - Status Code Definition File for Image Activator
	.IDENT	'V04-000'

!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! Facility:
!
!	VAX/VMS System Message File Component
!
! Abstract:
!
!	This file contains the various status codes returned by the image
!	activator and the image header decoding subroutines.
!
! Author:
!
!	Bob Grosso and Larry Kenah
!
! Creation Date:
!
!	7 June 1983
!
! Modified By:
!
!	V03B-003	MSH0041		Michael S. Harvey	3-May-1984
!			Clean up and generalize some messages. Add some
!			new ones.
!
!	V03B-002	LJA0109 	Laurie J. Anderson 	 3-Feb-1984
!			Added some more intelligent bad header error messages.
!
!--

	.FACILITY	IMGACT,77/PREFIX=IMG$_	

!+
! The following status codes represent alternate success codes that can be
! returned by the image activator or its internal subroutines.
!-

	.SEVERITY	SUCCESS
	.BASE		0

	NORMAL		<image successfully activated>

	.SEVERITY	INFORMATIONAL
	.BASE		100

	ACTIVATED	<image already mapped>

!+
! The following status codes represent various errors that are detected
! by the image activator or its internal subroutines. Unless otherwise
! indicated, the presence of any of these errors causes the current
! activation to be aborted.
!-


	.SEVERITY 	WARNING
	.BASE		200

	ENDOFHDR	<end of image header detected, no more ISDs>

	.SEVERITY 	ERROR
	.BASE		300

	IMAGE_NOT_FOUND	<this image has not yet been mapped>

	.SEVERITY 	FATAL
	.BASE		400

	BADHDR		<an error was discovered in the image header>
	BAD_FIXUPVEC	<the fixup vector contains inconsistent data>
	BADOFFSET	<image header offset is invalid>
	CROSSLNK	<cross linker images are not yet supported>
	IMG_SIZ		<image header descriptor length is invalid>
	INCONISD	<inconsistent ISD structures detected>
	ISD_OFF		<image section descriptor offset is invalid>
	ISD_VBN		<ISD VBN greater than header block count>
	ISD_SIZ		<image section descriptor length is invalid>
	NONAME		<the image name is a required parameter>

	.END
