	.TITLE	runmsg -- Diagnostic messages for RUN
	.IDENT	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!
!++
!
! Facility:
!
!	CLI Utilities
!
! Abstract:
!
!	This module defines the utility specific diagnostic messages.
!
! Author:
!
!	Michael T. Rhodes			Creation Date:	March, 1983
!
! Modified By:
!
!	V03-001	MTR0001		Michael T. Rhodes	29-Apr-1983
!		Change PID message id to PROC_ID.
!
!--

	.FACILITY RUN, 192	/PREFIX=RUN$_

	.SEVERITY SUCCESS
	proc_id		<identification of created process is !XL>/FAO=1

	.SEVERITY WARNING
	schdwk		<failed to schedule wake up request for process !XL>/FAO=1

	.SEVERITY FATAL
	creprc		<process creation failed>
	getjpi		<failed to obtain default job and process information>
	cvterr		<could not convert entity !AS using !AS>/FAO=2
	invuic		<!AS is an invalid UIC specification>/FAO=1
	illval		<!AS is an illegal CPU time>/FAO=1

	.END
