!---
!
!	Error messages for the SET utility
!
!	Version 'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:  SET utility
!
! ABSTRACT:
!
!	These are the error messages used by the SET command
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, privileged user mode utility,
!	operates at non-AST level.
!
! AUTHOR:  Greg Robert,  June, 1981
!
! MODIFIED BY:
!
!	V03-027	AEW008		Anne E. Warner		07-Aug-1984
!		Add non-fatal error MSCPNOTLD to tell the user that
!		the MSCP-Server code is not loaded.  The original use
!		for this is in SET DEV/SERVED when trying to MSCP serve
!		a device when the server code is not loaded.
!
!	V03-026 AEW007		Anne E. Warner		25-Jul-1984
!		Add non-fatal error INVDEV to tell user that the 
!		device type specified is invalid for the operation
!		requested.  Originally for use in SET DEVICE.
!
!	V03-025 AEW006		Anne E. Warner		17-Jul-1984
!		Add non-fatal error NOTDISK telling user that he has
!		tried to SET VOLUME . . to a non-Files-11 device.
!
!	V03-024	AEW005		Anne E. Warner		05-Jul-1984
!		Change ALTPRV to ALTPRI from below because there is
!		no privilege ALTPRV.
!
!	V03-023	AEW0004		Anne E. Warner		04-Jun-1984
!		Add non-fatal error NOPRIO, from module SETPROCES.B32
!		stating that the process priority cannot be raised
!		above base because the process does not have ALTPRV.
!		(actually its ALTPRI - see above)
!
!	V03-022	LMP0232		L. Mark Pilant,		16-Apr-1984  14:59
!		Add OBJLOCKED message for SETSHOACL to indicate that
!		the attempt to get a write lock failed.
!
!	V03-021	LMP0226		L. Mark Pilant,		9-Apr-1984  11:49
!		Add IVORDER and NOSUCHACE for use by SETACL.
!
!	V03-020 AEW0004		Anne E. Warner		 6-Apr-1984
!               Add non-fatal error NOTUQPORT stating that the device
!               is not connected to a UNIBUS/Q-bus port.
!
!       V03-019 AEW0003         Anne E. Warner          22-Mar-1984
!               Add messages used when SET VOLUME attempts to modify  
!               a /FOREIGN mounted volume. Both are severity error.
!                 - NOTMOD - Volume not modified
!                 - BADFRMT- Volume is not mounted with Files-11 format
!
!	V03-018 EMD0066 	Ellen M. Dusseault	14-Mar-1984  
!		Add message, SET$_NOPERM, for SET TERMINAL.
!
!	V03-017	PRB0321		Paul Beck	11-Mar-1984  12:58
!		Add SET$_NOCLUSTER message for SET CLUSTER
!
!	V03-016	SHZ0001		Stephen H. Zalewski	14-Feb-1984
!		Add new error messages for SET PASSWORD.
!
!       V03-015 AEW0002         Anne Warner             15-Dec-1983
!               Add messages for /PROTECTION
!               PROTNOTCHG -- error message, protection not changed
!               PROERR -- error message, unable to protect file
!               PROTECTED -- information message for /LOG, shows protection change
!
!	V03-014	LMP0168		L. Mark Pilant,		11-Nov-1983  13:39
!		Add message to note that hidden ACEs cannot be modified.
!
!       V03-013 AEW0001         Anne Warner             08-Nov-1983
!               Add messages for /UNLOCK
!               UNLOCKERR -- error message
!               NOTLOCKED -- informational message
!               UNLOCKED  -- informational message with keyword /LOG
!
!	V03-012	GAS0176		Gerry Smith		 7-Sep-1983
!		Add JNLACCERR, error accessing security journal.
!
!	V03-011	GAS0143		Gerry Smith		25-Jul-1983
!		Add messages for SET AUDIT.
!
!	V03-010	GAS0139		Gerry Smith		17-Jun-1983
!		Add messages for SET PASSWORD.
!
!	V03-009	GAS0130		Gerry Smith		28-Apr-1983
!		Make UNKTERM an informational.
!
!	V03-008	GAS0117		Gerry Smith		12-Apr-1983
!		Fix some missing /FAOs and add some /ID=NOTSETs so
!		that the error messages look like NOTSET, instead
!		of WRITEERR.
!
!	V03-007	GAS0112		Gerry Smith		29-Mar-1983
!		Add new messages for SET ACCOUNTING, SET TERMINAL.
!
!	V03-006	GAS0108		Gerry Smith		12-Mar-1983
!		Add new messages for SET.
!
!	V03-005	GAS0107		Gerry Smith		10-Feb-1983
!		Add SET$_NEWLIMS and SET$_INTSET, to signal the new 
!		values for SET LOGIN and SET WORKING_SET.
!
!	V03-004	GAS0046		Gerry Smith		10-Feb-1982
!		Add SET$_SYSNOTUPD, to show that the UCB and VCB were
!		not able to be updated.
!
!	V03-003	GAS0045		Gerry Smith		 9-Feb-1982
!		Add disk name to HB$_READ and HB$_WRITE
!
!	V03-002 GAS0026		Gerry Smith		18-Dec-1981
!		Use shared message file, and lower fatal messages to
!		simple error messages.
!
!	V03-001	GAS0018		Gerry Smith		16-Nov-1981
!		Add messages for SET FILE, SET DIRECTORY, and SET VOLUME.
!
!----

	.FACILITY	SET,119 /SYSTEM

!
! Fatal errors
!
.SEVERITY FATAL
	OWNPROC		<the !AS qualifier is only valid for your own process>/FAO=1

!
! Non-fatal errors
!
.SEVERITY ERROR
	CLOSEERR	<error closing !AS> /FAO=1
	ENTERR		<error entering !AS as !AS> /FAO=2
	HBREAD		<error reading home block of !AS> /FAO=1
	HBWRITE		<error writing home block of !AS> /FAO=1
	NOHOME		<volume does not contain a valid home block>
	NONODE		<node specification not allowed>
	NOTDIR		<file is not a directory>
	NOTODS2		<!AS qualifier invalid on Files-11 Structure Level 1 disk> /FAO=1
	OPENDIR		<error opening parent directory for !AS> /FAO=1
	OPERREQ		<OPER privilege required for /ACCESSED qualifier>
	PRONOTCHG	<Protection on !AS not changed> /FAO=1 
	PROERR		<Error protecting !AS> /FAO=1
	READERR		<error reading !AS> /FAO=1
	REMERR		<error removing !AS> /FAO=1
        UNLOCKERR       <error unlocking !AS> /FAO=1
	WRITEERR	<error modifying !AS> /FAO=1/ID=NOTSET
	NONAME		<process name not set> /ID=NOTSET
	NOPRIO 		<need ALTPRI privilege to elevate above base priority> /ID=NOTSET
	NOSWAP 		<swapping mode not changed> /ID=NOTSET
	NOTPRIV 	<privileges not changed> /ID=NOTSET
	NOWAIT 		<process resource_wait mode not changed> /ID=NOTSET
	NOTRESUMED 	<process !AS, PID=!XL, not resumed> /FAO=2/ID=NOTSET
	NOTSUSPND 	<process !AS, PID=!XL, not suspended> /FAO=2/ID=NOTSET
	NONEWFILE	<new accounting file not created>
	PWDNOTVAL	<old password validation error - password not changed>
	PWDNOTVER	<new password verification error - password not changed>
	PWDLOCKED	<password is locked to prevent change>
	PWDSYNTAX	<illegal password syntax>
	SYSPWDERR	<error modifying system password>
	UAFERR		<error accessing authorization file>
	NOHIDDEN	<cannot modify hidden ACEs>
	PWDNOTDIF	<new password must be different from current password>
	INVPWDLEN	<invalid password length - password not changed>
	NOCLUSTER	<qualifier only valid for VAXcluster systems>
        NOTMOD          <!AS not modified> /FAO=1
        BADFRMT         <volume is not mounted with Files-11 format>
	NOTDISK		<device must be a Files-11 format disk>
  	NOTUQPORT	<device not connected to a UNIBUS/Q-bus port>
	IVORDER		<order of ACEs being modified is incorrect for object!/    !AS> /FAO=1
	OBJLOCKED	<object currently locked by another user>
	INVDEV		<device is invalid for requested operation>
	MSCPNOTLD	<MSCP-Server code not loaded>

!
! Warning messages
!
.SEVERITY WARNING
	BUFBLKREQ	<buffer count or block count required> 
	SYSNOTUPD	<I/O database not updated for volume !AS> /FAO=1
    	JNLACCERR	<error accessing security journal>
	JNLERR		<error creating security journal>
	VRSNERR		<error creating new journal file>
    	NOPERM		<permanent qualifier not specified>
	NOSUCHACE	<ACE for object !AS, does not exist!/!AS> /FAO=2

!
! Informational messages
!
.SEVERITY INFORMATIONAL
	ENTERED		<!AS entered as !AS> /FAO=2
	MODIFIED	<!AS modified> /FAO=1
	REMOVED		<!AS removed> /FAO=1
	INTSET		<login interactive limit = !UW, current interactive value = !UW> /FAO=2
	NEWLIMS		<new working set:  Limit = !UL  Quota = !UL  Extent = !UL> /FAO=3
	NAMESET 	<process name set to !AS> /FAO=1
	MODESET 	<process set to /!AS> /FAO=1
	PRIOSET 	<process !AS, PID=!XL, set to priority !UL> /FAO=3
	PRIVSET 	<new privileges set>
	RESUMED 	<process !AS, PID=!XL, resumed> /FAO=2
	SUSPND 		<process !AS, PID=!XL, suspended> /FAO=2
	DEVSET1		<!AS set to /!AS> /FAO=2
	DEVSET2		<!AS set to /!AS = !AS> /FAO=3
        NOTLOCKED       <!AS notlocked> /FAO=1
        UNLOCKED        <!AS unlocked> /FAO=1
	EOFSET		<end of file written on !AS> /FAO=1
	DEVPSET		<protection on !AS set to S:!AS,O:!AS,G:!AS,W:!AS, owner UIC = !%U> /FAO=6
	SPOOLED		<!AS spooled to queue !AS, intermediate device !AS> /FAO=3
	ACCDISAB	<accounting disabled>
	ACCENAB		<accounting enabled for !AS> /FAO=1
	NEWFILE		<new accounting file created>
    	TERMSET		<terminal !AS set to !AS> /FAO=2
    	UNKTERM		<unknown terminal type>
	AUDSET		<security auditing parameters set>
	JNLSYSDEV	<attempting to create security journal on SYS$SYSDEVICE>
	NEWJNL		<new security journal successfully created>
	NEWVRSN		<new security journal file successfully created>
	PROTECTED	<!AS file protection changed to !AS>  /FAO=2
.END
