!---
!
!	Error messages for the SHOW utility
!
!	Version 'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! FACILITY:  SHOW utility
!
! ABSTRACT:
!
!	These are the error messages used by the SHOW command
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, privileged user mode utility,
!	operates at non-AST level.
!
! AUTHOR:  Gerry Smith					11-Oct-1982
!
! MODIFIED BY:
!
!	V03-008	AEW0001		Anne E. Warner		07-Aug-1984
!		Add message show$_mscpnotld for when the MSCP-Server
!		code is not loaded and the user tries to SHOW DEV/SERVED.
!
!	V03-007	PRD0091		Paul R. DeStefano	06-Apr-1984
!		Restored all V3 message values by moving all new
!		messages to the end of the file.  Changes first
!		character in Show Cluster messages to lowercase.
!
!	V03-006	PRD0082		Paul R. DeStefano	25-Mar-1984
!		Added additional messages for Show Cluster.
!
!	V03-005	LMP0213		L. Mark Pilant,		24-Mar-1984  15:28
!		Add OBJLOCKED message for SETSHOACL to indicate that
!		the attempt to get a read lock failed.
!
!	V03-004	CWH3004		CW Hobbs		19-Mar-1984
!		Add LOCKERR message for SHOW DEVICE
!
!	V03-003	PRD0074		Paul R. DeStefano	28-Feb-1984
!		Add messages for SHOW CLUSTER.
!
!	V03-002 GAS0154		Gerry Smith		25-Jul-1983
!		Add messages for SHOW AUDIT.
!
!	V03-001	GAS0116		Gerry Smith		12-Apr-1983
!		Add "No device errors", to give users that nice warm
!		fuzzy feeling.
!
!----

	.FACILITY	SHOW,120/SYSTEM

!
! Fatal errors
!

!
! Non-fatal errors
!
.SEVERITY ERROR
	NOTCLASS	<!AS not a !AS !/device type is !AC>/FAO=3
	MSCPNOTLD	<MSCP-Server code not loaded>

!
! Warning messages
!
.SEVERITY WARNING

!
! Success messages
!
.SEVERITY SUCCESS
	NOTRAN		<no translation for logical name !AS>/FAO=1

!
! Informational messages
!
.SEVERITY INFORMATIONAL
    	NONET		<network unavailable>
	NOSUCHUSER	<user !AS not currently logged in>/FAO=1

!
! Fatal errors
!

!
! Non-fatal errors
!
.SEVERITY ERROR
	OBJLOCKED	<object currently locked by another user>

!
! Warning messages
!
.SEVERITY WARNING
	AUDREADERR	<error obtaining security event data>
	AUDDEVERR	<error accessing security journal>

!
! Warning messages for Show Cluster
!
	AMBIG		<ambiguous field name or class name "!AS".>/FAO_COUNT=1
	CACLS		<the "!AS" class can not be added to this report.>/FAO_COUNT=1
	CRCLS		<the "!AS" class can not be removed from this report.>/FAO_COUNT=1
	UNRCMD		<unrecognized command "!AS".>/FAO_COUNT=1
	UNRKEY		<unrecognized field or class name "!AS".>/FAO_COUNT=1
	IVADDNODE	<node "!AS" can not be added to the display.>/FAO_COUNT=1
	IVREMNODE	<node "!AS" can not be removed from the display.>/FAO_COUNT=1
	IVADDID		<system # "!AS" can not be added to the display.>/FAO_COUNT=1
	IVREMID		<system # "!AS" can not be removed from the display.>/FAO_COUNT=1
	IVTYPE		<invalid system type "!AS", - must match HW_TYPE field or ALL.>/FAO_COUNT=1
	NOAVAIL		<field "!AS" not available in this report.>/FAO_COUNT=1

!
! Success messages
!
.SEVERITY SUCCESS
    	NOERRORS	<no device errors found>

!
! Informational messages
!
.SEVERITY INFORMATIONAL
!
! Informational messages for Show Cluster
!
	HIBER		<hibernating until !AS>/FAO_COUNT=1

!
! Informational message for Show Device
!
	LOCKERR		<error examining cluster lock database for !AF> /FAO=2
.END
