!	SUBMITMSG.MSG - PRINT and SUBMIT Messages
!
!	Version	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
!
! FACILITY:
!	PRINT and SUBMIT commands.
!
! ABSTRACT:
!	This file contains the messages for the PRINT and SUBMIT commands.
!
! ENVIRONMENT:
!	VAX/VMS user mode.
!
!--
!
! AUTHOR: M. Jack, CREATION DATE: 30-Apr-1982
!
! MODIFIED BY:
!
!	VO3-003	RRB0027		Rowland R. Bradley, 23-Jul-1984	09:23
!		Remove extra "/FAO=1" phrases.
!
!	V03-002 RRB0023		Rowland R. Bradley, 03-JUL-1984  17:23
!		Add REMOINSF error message.
!
!	V03-001	MLJ0115		Martin L. Jack,	29-Jul-1983  13:40
!		Changes for job controller baselevel.
!
!**

.title SUBMITMSG
.facility PRINT,191/system
!
!	Following messages used by both PRINT and SUBMIT must be kept parallel.
!
.severity fatal
CREJOB		<error creating job>
.severity error
ADDFIL		<error adding file !AS to job>/FAO=1
INVFILSPE	<invalid file specification !AS>/FAO=1
REMOINSF	<node name specification or /REMOTE missing from command line>
.base 100


.facility SUBMIT,193/system
!
!	Following messages used by both PRINT and SUBMIT must be kept parallel.
!
.severity fatal
CREJOB		<error creating job>
.severity error
ADDFIL		<error adding file !AS to job>/FAO=1
INVFILSPE	<invalid file specification !AS>/FAO=1
REMOINSF	<node name specification or /REMOTE missing from command line>
.base 100
!
!	Following messages used by SUBMIT only.
!
INVLOGFIL	<invalid log file specification>
.end
