!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

! This file, VMSMSG.TMP, contains the definitions of the EDT
! messages for VAX/VMS.  This file is read by the MESSAGE compiler
! to build an object file containing the EDT messages.
!
        .TITLE EDT$VMSMSG EDT's message text
!
.FACILITY/SYSTEM EDT, 133
COLONREQ/WARNING <':' required>
ABOBYCC/WARNING <Aborted by CTRL/C>
BOTOFBUF/WARNING <Advance past bottom of buffer>
ASREQ/WARNING <'AS' required>
ATTCUTAPP/WARNING <Attempt to CUT or APPEND to current buffer>
ATTPASCUR/WARNING <Attempt to PASTE current buffer>
REENTRY/FATAL   <Attempt to re-enter EDT>
TOPOFBUF/WARNING <Backup past top of buffer>
NOSETTRM/WARNING <Cannot set terminal type from change mode>
CHGMODTER/WARNING <Change mode can be entered only from a terminal>
COMBUFEXH/WARNING <Command buffer exhausted>
COMEXHXLA/WARNING <Command buffer exhausted during XLATE command processing>
COMFILCLO/WARNING <Command file could not be closed>
COMFILNOP/WARNING <Command file could not be opened>
COMFILNEX/WARNING <Command file does not exist>
CONCHKFLD/WARNING <Consistency check failed, please check your file>
CLDNOTALN/WARNING <Could not align tabs with cursor>
CTRC__IGN/WARNING <CTRL/C ignored>
DSTMOVCOP/WARNING <Destination for MOVE or COPY not found>
EDITORABO/FATAL   <Editor aborted>
ENTMUSTBE/WARNING <Entity must be WORD, SENTENCE, PARAGRAPH or PAGE>
ERRCOMOPT/WARNING <Error in command option>
ERRRANSPC/WARNING <Error in range specification>
OPNINTRM/FATAL   <Error opening terminal for input>
OPNOUTTRM/FATAL   <Error opening terminal for output>
ERRINPFIL/WARNING <Error reading from input file>
ERRINPTRM/WARNING <Error reading from terminal>
ERROUTFIL/WARNING <Error writing to output file>
BADFILATR/WARNING <File attributes error>
FILNAM/WARNING <File name:>
NOFILSPC/WARNING <File specification required>
FORHLPANO/WARNING <For help on any other keypad key, press the key>
HLPFILCLO/WARNING <Help file could not be closed>
NOHLPAVL/WARNING <Help file could not be opened>
NOHLPINI/WARNING <Help File Index could not be initialized>
INCFILCLO/WARNING <Include file could not be closed>
INCFILOPN/WARNING <Include file could not be opened>
INCFILNEX/WARNING <Include file does not exist>
INPFILCLO/WARNING <Input file could not be closed>
INPFILOPN/WARNING <Input file could not be opened>
INPFILNEX/WARNING <Input file does not exist>
NONSTDFIL/INFORMA <Input file does not have standard text file format>
INSMEM/WARNING <Insufficient memory>
INTERERR/FATAL   <Internal software error - please submit an SPR>
INVBUFNAM/WARNING <Invalid buffer name>
INVASCCHR/WARNING <Invalid character code>
INVENT/WARNING <Invalid entity>
INVOPTCOM/WARNING <Invalid option for that command>
INVPARFOR/WARNING <Invalid parameter for SET or SHOW>
INVSTR/WARNING <Invalid string>
INVSUBCOM/WARNING <Invalid subcommand>
INVVALSET/WARNING <Invalid value in SET command>
IOERRWRK/FATAL   <I/O error on work file>
JOUFILCLO/WARNING <Journal file could not be closed>
NOJNLFIL/WARNING <Journal file could not be opened>
BADDEFK/WARNING <Keys cannot be defined in Nokeypad mode>
LINEXC255/WARNING <Line exceeded 255 characters, truncated>
MACKEYREQ/WARNING <MACRO or KEY required>
MAXINPLIN/FATAL   <Max input line of 2814749767 exceeded, file input terminated>
MAXLINNUM/FATAL   <Max line number exceeded; lines no longer ascending; resequence recommended>
MAXLINVAL/FATAL   <Max number of lines for this buffer exceeded>
NODEFN/WARNING <No definition>
NOKEYHLP/WARNING <No help available for that key>
BADRANGE/FATAL   <No more than 65535 lines can be processed in a single command>
NOFILWRT/WARNING <No output file written>
NOSELRAN/WARNING <No select range active>
NOSUCHLIN/WARNING <No such line>
NOWENTDEF/WARNING <Now enter the definition terminated by ENTER>
NUMVALILL/WARNING <Numeric value illegal>
NUMVALREQ/WARNING <Numeric value required>
NOORIGNUM/FATAL   <ORIGINAL line numbers no longer an EDT feature>
OUTFILCLO/WARNING <Output file could not be closed>
OUTFILCRE/WARNING <Output file could not be created>
PARENMIS/WARNING <Parenthesis mismatch>
PARSTKOVF/WARNING <Parsing stack overflow>
PLSANSYNQ/WARNING <Please answer Y(es), N(o), Q(uit), or A(ll)>
PASSTATUS/WARNING <Pass bad status to caller>
PRERETCON/WARNING <Press return to continue >
PRSKEYDEF/WARNING <Press the key you wish to define>
PRIFILCLO/WARNING <Print file could not be closed>
PRIFILCRE/WARNING <Print file could not be created>
QUOSTRREQ/WARNING <Quoted string required>
RANNONCON/WARNING <Range for RESEQUENCE must be contiguous>
RANSPCSEQ/WARNING <Range specified by /SEQUENCE would cause duplicate or non-sequential numbers>
RECTOOBIG/WARNING <Record too big, truncated to 255 characters>
SUBSTRNUL/WARNING <Search string cannot be null>
INVSRAN/WARNING <Select complete lines only>
SELALRACT/WARNING <Select range is already active>
SEQINCROV/FATAL   <Sequence increment must be less than 65536>
SEQNUMOV/FATAL   <Sequence number must be less than 65536>
NONALPNUM/WARNING <String delimiter must be non-alphanumeric>
STRNOTFND/WARNING <String was not found>
KEYNOTDEF/WARNING <That key is not definable>
TOEXITHLP/WARNING <To exit from HELP, press the spacebar>
TORETKEY/WARNING <To return to the keypad diagram, press the return key>
UNXCHRAFT/WARNING <Unexpected characters after end of command>
UNRCOM/WARNING <Unrecognized command>
UNRCOMOPT/WARNING <Unrecognized command option>
WORFILCLO/WARNING <Work file failed to close>
WORFILFAI/FATAL   <Work file failed to open>
WRKFILOVF/FATAL   <Work file overflow>
WORKING/FATAL   <Working>
WRIFILCLO/WARNING <Write file could not be closed>
WRIFILCRE/WARNING <Write file could not be created>
.END
