	.IDENT	'V04-000'
!
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:
!	Symbiont.
!
! ABSTRACT:
!	Symbiont  messages.
!
!	These are the messages common to VAX/VMS symbionts.  Message types for
!	messages sent from the symbionts to the job controller are defined by
!	the $MSGDEF macro.
!
! ENVIRONMENT:
!	VAX/VMS user and kernel mode.
!
! AUTHOR: Rowland R. Bradley, CREATION DATE: 20-July-1984
!
! MODIFIED BY:
!
!	3B-010	BLS0336		Benn Schreiber		 5-AUG-1984
!		Add .END.
!
!	3B-009	RRB0009		Rowland R. Bradley	20-Jul-184
!		Removed these definitions for SMB and placed in a separate
!		file SMBMSG.MSG.  This accomplishes the renaming of messages 
!		with a separate facility code.  Now two types of messages
!		SMB$... AND PSM$... depending on the context of the
!		error.  Audit trail begins at higher number since this is
!		a continuation of PSMMSG.MSG.
!
!**
!


.FACILITY SMB, 272 /SYSTEM /MACRO = $PSMMSGDEF
.BASE 0


.SEVERITY ERROR
NOMOREITEMS	<no more items in message>

.SEVERITY FATAL
INVSTMNBR	<invalid stream number>
INVSTRLEV	<invalid structure level>

.END
