!EDIT: MDL1004
!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************
!

!++
! FACILITY:	General Utility Library
!
! ABSTRACT:
!
!	This file, BASMSG.MSG, contains the definitions of the BASIC
!	messages for VAX/VMS.  This file is read by the MESSAGE compiler
!	to build an object file containing the BASIC messages.
!
! ENVIRONMENT:	User mode - AST reentrant
!
! AUTHOR: RTL Development, CREATION DATE: 06-May-1983
!
! MODIFIED BY:
!
!	NOTE:	Any changes to this module must also be reflected in 
!		BASERRMSG.REQ

! 1-001	- Original.  BLS 6-May-1983
! 1-002 - Change facility to BASIC instead of BAS.  LEB 2-Jun-1983
! 1-003 - nope, facility should have been BAS all along.  MDL 30-Jun-1983
! 1-004 - change text of error 178 and name from ERRFILCOR to EXRMSSHR.  MDL 29-Aug-1983
!--
        .TITLE BASIC's message text

.FACILITY/SYSTEM BAS, 26
.BASE 0
VAXBAS/INFO <VAX-11 BASIC>
BADDIRDEV/ERROR <Bad directory for device>
ILLFILNAM/ERROR <Illegal file name>
ACCDEVUSE/ERROR <Account or device in use>
NO_ROOUSE/ERROR <No room for user on device>
CANFINFIL/ERROR <Can't find file or account>
NOTVALDEV/ERROR <Not a valid device>
IO_CHAALR/ERROR <I/O channel already open>
DEVNOTAVA/ERROR <Device not available>
IO_CHANOT/ERROR <I/O channel not open>
PROVIO/ERROR <Protection violation>
ENDFILDEV/ERROR <End of file on device>
FATSYSIO_/ERROR <Fatal system I/O failure>
USEDATERR/ERROR <User data error on device>
DEVHUNWRI/ERROR <Device hung or write locked>
KEYWAIEXH/ERROR <Keyboard wait exhausted>
NAMACCNOW/ERROR <Name or account now exists>
TOOMANOPE/ERROR <Too many open files on unit>
ILLSYSUSA/ERROR <Illegal SYS() usage>
DISBLOINT/ERROR <Disk block is interlocked>
PACIDSDON/ERROR <Pack IDs don't match>
DISPACNOT/ERROR <Disk pack is not mounted>
DISPACLOC/ERROR <Disk pack is locked out>
ILLCLUSIZ/ERROR <Illegal cluster size>
DISPACPRI/ERROR <Disk pack is private>
DISPACNEE/ERROR <Disk pack needs 'CLEANing'>
FATDISPAC/ERROR <Fatal disk pack mount error>
IO_TO_DET/ERROR <I/O to detached keyboard>
PROC__TRA/ERROR <Programmable ^C trap>
CORFILSTR/ERROR <Corrupted file structure>
DEVNOTFIL/ERROR <Device not file-structured>
ILLBYTCOU/ERROR <Illegal byte count for I/O>
NO_BUFSPA/ERROR <No buffer space available>
ODDADDTRA/ERROR <Odd address trap>
RESINSTRA/SEVERE <Reserved instruction trap>
MEMMANVIO/SEVERE <Memory management violation>
SP_STAOVE/SEVERE <SP stack Overflow>
DISERRDUR/SEVERE <Disk error during swap>
MEMPARFAI/SEVERE <Memory parity (or ECC) failure>
MAGSELERR/ERROR <Magtape select error>
MAGRECLEN/ERROR <Magtape record length error>
NONRESRUN/ERROR <Non-res run-time system>
VIRBUFTOO/ERROR <Virtual buffer too large>
VIRARRDIS/ERROR <Virtual array not on disk>
MATARRTOO/ERROR <Matrix or array too big>
VIRARROPE/ERROR <Virtual array not yet open>
ILLIO_CHA/ERROR <Illegal I/O channel>
LINTOOLON/ERROR <Line too long>
FLOPOIERR/ERROR <Floating point error or overflow>
ARGTOOLAR/ERROR <Argument too large in EXP>
DATFORERR/WARNING <Data format error>
INTERR/ERROR <Integer error or overflow>
ILLNUM/ERROR <Illegal number>
ILLARGLOG/ERROR <Illegal argument in LOG>
IMASQUROO/ERROR <Imaginary square roots>
SUBOUTRAN/ERROR <Subscript out of range>
CANINVMAT/ERROR <Can't invert matrix>
OUTOF_DAT/ERROR <Out of data>
ON_STAOUT/ERROR <ON statement out of range>
NOTENODAT/ERROR <Not enough data in record>
INTOVEFOR/ERROR <Integer overflow, FOR loop>
DIVBY_ZER/ERROR <Division by 0>
NO_RUNSYS/ERROR <No run-time system>
FIEOVEBUF/ERROR <FIELD overflows buffer>
NOTRANACC/ERROR <Not a random access device>
ILLMAGUSA/ERROR <Illegal MAGTAPE() usage>
MISSPEFEA/ERROR <Missing special feature>
ILLSWIUSA/ERROR <Illegal switch usage>
UNUERR068/SEVERE <Unused>
UNUERR069/SEVERE <Unused>
UNUERR070/SEVERE <Unused>
STANOTFOU/SEVERE <Statement not found>
RETWITGOS/SEVERE <RETURN without GOSUB>
FNEWITFUN/SEVERE <FNEND without function call>
UNDFUNCAL/SEVERE <Undefined function called>
ILLSYM/SEVERE <Illegal symbol>
ILLVER/SEVERE <Illegal verb>
ILLEXP/SEVERE <Illegal expression>
ILLMODMIX/SEVERE <Illegal mode mixing>
ILLIF_STA/SEVERE <Illegal IF statement>
ILLCONCLA/SEVERE <Illegal conditional clause>
ILLFUNNAM/SEVERE <Illegal function name>
ILLDUMVAR/SEVERE <Illegal dummy variable>
ILLFN_RED/SEVERE <Illegal FN redefinition>
ILLLINNUM/SEVERE <Illegal line number(s)>
MODERR/SEVERE <Modifier error>
CANCOMSTA/ERROR <Can't compile statement>
EXPTOOCOM/SEVERE <Expression too complicated>
ARGDONMAT/SEVERE <Arguments don't match>
TOOMANARG/SEVERE <Too many arguments>
INCFUNUSA/WARNING <Inconsistent function usage>
ILLDEFNES/SEVERE <Illegal DEF nesting>
FORWITNEX/SEVERE <FOR without NEXT>
NEXWITFOR/SEVERE <NEXT without FOR>
DEFWITFNE/SEVERE <DEF without FNEND>
FNEWITDEF/SEVERE <FNEND without DEF>
LITSTRNEE/SEVERE <Literal string needed>
TOOFEWARG/SEVERE <Too few arguments>
SYNERR/SEVERE <Syntax error>
STRIS_NEE/SEVERE <String is needed>
NUMIS_NEE/SEVERE <Number is needed>
DATTYPERR/SEVERE <Data type error>
ONEOR_TWO/SEVERE <One or two dimensions only>
PROLOSSOR/SEVERE <Program lost-Sorry>
RESNO_ERR/SEVERE <RESUME and no error>
REDARR/ERROR <Redimensioned array>
INCSUBUSE/WARNING <Inconsistent subscript use>
ON_STANEE/SEVERE <ON statement needs GOTO>
ENDOF_STA/SEVERE <End of statement not seen>
WHA/INFO <What?>
BADLINNUM/SEVERE <Bad line number pair>
NOTENOAVA/SEVERE <Not enough available memory>
EXEONLFIL/SEVERE <Execute only file>
PLEUSERUN/SEVERE <Please use the RUN command>
CANCON/SEVERE <Can't CONTinue>
FILEXIREN/SEVERE <File exists-RENAME/REPLACE>
PRIUSIFOR/SEVERE <PRINT-USING format error>
MATARRWIT/SEVERE <Matrix or array without DIM>
BADNUMPRI/SEVERE <Bad number in PRINT-USING>
ILLIN_IMM/SEVERE <Illegal in immediate mode>
PRIUSIBUF/SEVERE <PRINT-USING buffer overflow>
ILLSTA/SEVERE <Illegal statement>
ILLFIEVAR/SEVERE <Illegal FIELD variable>
STO/INFO <Stop>
MATDIMERR/SEVERE <Matrix dimension error>
WROMATPAC/SEVERE <Wrong math package>
MAXMEMEXC/SEVERE <Maximum memory exceeded>
SCAFACINT/SEVERE <SCALE factor interlock>
TAPRECNOT/ERROR <Tape records not ANSI>
TAPBOTDET/ERROR <Tape BOT detected>
KEYNOTCHA/ERROR <Key not changeable>
NO_CURREC/ERROR <No current record>
RECHASBEE/ERROR <Record has been deleted>
ILLUSADEV/ERROR <Illegal usage for device>
DUPKEYDET/ERROR <Duplicate key detected>
ILLUSA/ERROR <Illegal usage>
ILLILLACC/ERROR <Illegal or illogical access>
ILLKEYATT/ERROR <Illegal key attributes>
FILIS_LOC/ERROR <File is locked>
INVFILOPT/ERROR <Invalid file options>
INDNOTINI/ERROR <Index not initialized>
ILLOPE/ERROR <Illegal operation>
ILLRECFIL/ERROR <Illegal record on file>
BADRECIDE/ERROR <Bad record identifier>
INVKEYREF/ERROR <Invalid key of reference>
KEYSIZTOO/ERROR <Key size too large>
TAPNOTANS/ERROR <Tape not ANSI labelled>
RECNUMEXC/ERROR <RECORD number exceeds maximum>
BADRECVAL/ERROR <Bad RECORDSIZE value on OPEN>
NOTENDFIL/ERROR <Not at end of file>
NO_PRIKEY/ERROR <No primary key specified>
KEYFIEBEY/ERROR <Key field beyond end of record>
ILLRECACC/ERROR <Illogical record accessing>
RECALREXI/ERROR <Record already exists>
RECBUCLOC/ERROR <Record/bucket locked>
RECNOTFOU/ERROR <Record not found>
SIZRECINV/ERROR <Size of record invalid>
RECFILTOO/ERROR <Record on file too big>
PRIKEYOUT/ERROR <Primary key out of sequence>
KEYLARTHA/ERROR <Key larger than record>
FILATTNOT/ERROR <File attributes not matched>
MOVOVEBUF/ERROR <Move overflows buffer>
CANOPEFIL/ERROR <Cannot open file>
NO_FILNAM/ERROR <No file name>
TERFORFIL/ERROR <Terminal format file required>
CANPOSEOF/ERROR <Cannot position to EOF>
NEGFILSTR/ERROR <Negative fill or string length>
ILLRECFOR/ERROR <Illegal record format>
ILLALLCLA/ERROR <Illegal ALLOW clause>
UNUERR169/SEVERE <Unused>
INDNOTFUL/ERROR <Index not fully optimized>
RRVNOTFUL/ERROR <RRV not fully updated>
RECLOCFAI/ERROR <Record lock failed>
INVRFAFIE/ERROR <Invalid RFA field>
FILEXPDAT/ERROR <File expiration date not yet reached>
NODNAMERR/ERROR <Node name error>
NEGZERTAB/WARNING <Negative or zero TAB>
TOOMUCDAT/WARNING <Too much data in record>
EXRMSSHR/ERROR <System memory for file sharing exhausted>
UNEFILDAT/ERROR <Unexpired file date>
NOSUPFOR/ERROR <No support for operation in task>
DECERR/ERROR <Decimal error or overflow>
NETOPEREJ/ERROR <Network operation rejected>
REMOVEBUF/ERROR <REMAP overflows buffer>
UNAREMVAR/SEVERE <Unaligned REMAP variable>
RECOVEMAP/SEVERE <RECORDSIZE overflows MAP buffer>
IMPERRHAN/SEVERE <Improper error handling>
ILLRECLOC/SEVERE <Illegal record locking clause>
REQRECSIZ/ERROR <UNLOCK EXPLICIT requires RECORDSIZE 512>
TOOLITDAT/WARNING <Too little data in record>
UNUERR190/SEVERE <Unused>
UNUERR191/SEVERE <Unused>
UNUERR192/SEVERE <Unused>
UNUERR193/SEVERE <Unused>
UNUERR194/SEVERE <Unused>
UNUERR195/SEVERE <Unused>
UNUERR196/SEVERE <Unused>
UNUERR197/SEVERE <Unused>
UNUERR198/SEVERE <Unused>
UNUERR199/SEVERE <Unused>
UNUERR200/SEVERE <Unused>
UNUERR201/SEVERE <Unused>
UNUERR202/SEVERE <Unused>
UNUERR203/SEVERE <Unused>
UNUERR204/SEVERE <Unused>
UNUERR205/SEVERE <Unused>
UNUERR206/SEVERE <Unused>
UNUERR207/SEVERE <Unused>
UNUERR208/SEVERE <Unused>
UNUERR209/SEVERE <Unused>
UNUERR210/SEVERE <Unused>
UNUERR211/SEVERE <Unused>
UNUERR212/SEVERE <Unused>
UNUERR213/SEVERE <Unused>
UNUERR214/SEVERE <Unused>
UNUERR215/SEVERE <Unused>
UNUERR216/SEVERE <Unused>
UNUERR217/SEVERE <Unused>
UNUERR218/SEVERE <Unused>
UNUERR219/SEVERE <Unused>
UNUERR220/SEVERE <Unused>
UNUERR221/SEVERE <Unused>
UNUERR222/SEVERE <Unused>
UNUERR223/SEVERE <Unused>
UNUERR224/SEVERE <Unused>
UNUERR225/SEVERE <Unused>
UNUERR226/SEVERE <Unused>
STRTOOLON/ERROR <String too long>
RECATTNOT/ERROR <Record attributes not matched>
DIFUSELON/SEVERE <Differing use of LONG/WORD or SINGLE/DOUBLE qualifiers>
NO_FIEIMA/ERROR <No fields in image>
ILLSTRIMA/ERROR <Illegal string image>
NULIMA/ERROR <Null image>
ILLNUMIMA/ERROR <Illegal numeric image>
NUMIMASTR/ERROR <Numeric image for string>
STRIMANUM/ERROR <String image for numeric>
TIMLIMEXC/ERROR <TIME limit exceeded>
FIRARGSEQ/ERROR <First arg to SEG$ greater than second>
ARRMUSSAM/ERROR <Arrays must be same dimension>
ARRMUSSQU/ERROR <Arrays must be square>
CANCHAARR/ERROR <Cannot change array dimensions>
FLOOVE/ERROR <Floating overflow>
FLOUND/ERROR <Floating underflow>
CHATO_NON/ERROR <CHAIN to non-existent line number>
EXPERR/ERROR <Exponentiation error>
ILLEXIDEF/SEVERE <Illegal exit from DEF*>
ERRTRANEE/SEVERE <ERROR trap needs RESUME>
ILLRESSUB/SEVERE <Illegal RESUME to subroutine>
ILLRETSUB/ERROR <Illegal return from subroutine>
ARGOUTBOU/ERROR <Argument out of bounds>
NOTIMP/ERROR <Not implemented>
RECSUBCAL/ERROR <Recursive subroutine call>
FILACPFAI/ERROR <FILE ACP failure>
DIRERR/ERROR <Directive error>
UNUERR254/SEVERE <Unused>
UNUERR255/SEVERE <Unused>
.BASE 4085
FORFILUSE/INFO <for file !AS at user PC !XL> /FAO=2
USEPC_PSL/INFO <at user PC=!XL, PSL=!XL> /FAO=2
FROIOL/INFO <from immediate mode in module !AC> /FAO=1
ON_CHAFIL/INFO <on channel !SL for file !AS at user PC !XL> /FAO=3
FROLINMOD/INFO <from line !SL in module !AC> /FAO=2
FROLINSUB/INFO <from line !SL in subprogram !AC> /FAO=2
FROLINFUN/INFO <from line !SL in external function !AC> /FAO=2
FROLINDEF/INFO <from line !SL in DEF !AC in module !AC> /FAO=3
FROLINDFS/INFO <from line !SL in DEF* !AC in module !AC> /FAO=3
FROLINGSB/INFO <from line !SL in GOSUB !SL in module !AC> /FAO=3
FROLINOEG/INFO <from line !SL in ON ERROR GOTO !SL in module !AC> /FAO=3
.END
