.title messages CDU Message Definitions
.ident 'V04-000'
.facility cdu,17/system/prefix=cdu$_

!****************************************************************************
!*									    *
!*  COPYRIGHT (c) 1978, 1980, 1982, 1984 BY				    *
!*  DIGITAL EQUIPMENT CORPORATION, MAYNARD, MASSACHUSETTS.		    *
!*  ALL RIGHTS RESERVED.						    *
!* 									    *
!*  THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND COPIED   *
!*  ONLY IN  ACCORDANCE WITH  THE  TERMS  OF  SUCH  LICENSE  AND WITH THE   *
!*  INCLUSION OF THE ABOVE COPYRIGHT NOTICE. THIS SOFTWARE OR  ANY  OTHER   *
!*  COPIES THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY   *
!*  OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE IS  HEREBY   *
!*  TRANSFERRED.							    *
!* 									    *
!*  THE INFORMATION IN THIS SOFTWARE IS  SUBJECT TO CHANGE WITHOUT NOTICE   *
!*  AND  SHOULD  NOT  BE  CONSTRUED AS  A COMMITMENT BY DIGITAL EQUIPMENT   *
!*  CORPORATION.							    *
!* 									    *
!*  DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE  OR  RELIABILITY OF ITS   *
!*  SOFTWARE ON EQUIPMENT WHICH IS NOT SUPPLIED BY DIGITAL.		    *
!* 									    *
!*									    *
!****************************************************************************

!++
! Facility:	Command Definition Utility, Message File
!
! Abstract:	This file contains the definitions of all messages specific
!		to the Command Definition Utility.
!
! Environment:	Standard CDU environment.
!
! Author:	Paul C. Anagnostopoulos
! Creation:	29 November 1982
!
! Modifications:
!
!	V04-001	ROP0014		Robert Posniak	27-JUN-1984
!		Remove periods from end of messages.
!
!--


! All new messages must be added at the bottom of the list.  Each message
! must specify its severity.

! Miscellaneous signalled messages.

success		"Normal successful completion"/success
notclitable	"Image !AD is not a CLI table"/fao=2/fatal
climismatch	"CLI type of image does not match /CLI qualifier"/fatal
nointable	"An output table image must be created using an input table"/fatal
nosuchverb	"The CLI table does not contain verb name !AS"/fao=1/warning

! Syntax errors.

invchar		"Invalid character encountered in position !UL.  It is ignored"/fao=1/error
missquote	"Quoted string not terminated before end of line"/error
symtoolong	"The symbol !AS is longer than 31 characters"/fao=1/error
invitem		<Invalid item "!AS" encountered.  Some text will be skipped>/fao=1/error
dupident	"Only one IDENT statement is allowed"/error
dupmodule	"Only one MODULE statement is allowed"/error
invdefine	"Invalid DEFINE statement"/error
dupdef		"Duplicate definition of !AC encountered"/fao=1/error
reqkey		"At least one keyword must be specified for type !AC"/fao=1/error
confroutimg	"Only one routine or image clause is allowed"/error
imagelen	"An image spec is limited to !UL characters in length"/fao=1/error
confoutputs	"Only one OUTPUTS clause is allowed"/error
confnodis	"NODISALLOWS has already been specified"/error
confdis		"A DISALLOW clause has already been specified"/error
confnoparm	"NOPARAMETERS has already been specified"/error
invparm		"Parameter identifiers must be in the form Pn"/error
confparm	"A parameter has already been defined"/error
dupprefix	"Only one PREFIX clause is allowed"/error
confnoqual	"NOQUALIFIERS has already been specified"/error
dupqual		"Qualifier !AC has already been defined"/fao=1/error
confqual	"A qualifier has already been defined"/error
dupprompt	"Only one PROMPT clause is allowed"/error
confnonneg	"NONNEGATABLE has already been specified"/error
confneg		"NEGATABLE has already been specified"/error
invplace	"Placement must be GLOBAL, LOCAL, or POSITIONAL"/error
dupplace	"Only one PLACEMENT clause is allowed"/error
dupkey		"Keyword !AC has already been defined"/fao=1/error
duplabel	"Only one LABEL clause is allowed"/error
dupsyntax	"Only one SYNTAX clause is allowed"/error
dupvalue	"Only one VALUE clause is allowed"/error
confnocon	"NOCONCATENATE has already been specified"/error
confcon		"CONCATENATE has already been specified"/error
confdefreq	"Only one DEFAULT or REQUIRED clause is allowed"/error
defaultlen	"A default is limited to !UL characters in length, including commas"/fao=1/error
duptype		"Only one TYPE clause is allowed"/error
invvalclause	"Invalid value clause encountered"/error
invtype		"Builtin type !AS is not defined"/fao=1/error
invcliflag	"Invalid CLI flag !AS encountered"/fao=1/error

! Semantic errors.

undefsyntax	"Line !UL: Syntax !AC is not defined"/fao=2/error
undeftype	"Line !UL: Type !AC is not defined"/fao=2/error
igncliflag	"Line !UL: CLI flag ignored in this context"/fao=1/error
undefoutput	"Line !UL: Output parameter/qualifier !AC is not defined"/fao=2/error
invreqparm	"Line !UL: All required parameters must precede optional ones"/fao=1/error
routreq		"Line !UL: A ROUTINE clause is required when generating an object file"/fao=1/error
invrout		"Line !UL: A ROUTINE clause is only valid when generating an object file"/fao=1/error
pathundef	"Line !UL: Path !AS refers to undefined verb or syntax"/fao=2/error
pathunres	"Line !UL: Path !AS cannot be resolved"/fao=2/error
pathambig	"Line !UL: Path !AS is ambiguous"/fao=2/error

! Messages for composing the listing file.

anything	"!AS"/fao=1/info
heading1	"!7(_)!17%D     !46ASPage !UL"/fao=3/info
heading2	"!7(_)!17%D     !46<!AD (!UL)!>"/fao=4/info
listline	"    !4UL  !AD"/fao=3/info
errorcount	"Number of errors detected: !UL"/fao=1/info
commandline	"$ !AS"/fao=1/info

! Internal errors.

inthchar	"Internal error: encountered character of class h-string"/fatal
intinvnode	"Internal error: invalid node encountered"/fatal
intnodespace	"Internal error: node space exhausted"/fatal
intpathstkov	"Internal error: path stack overflow"/fatal
.end
